/* ** GENEREATED FILE - DO NOT MODIFY ** */
package com.wilutions.mslib.outlook;
import com.wilutions.com.*;

/**
 * _TaskItem.
 * 
 */
@CoInterface(guid="{00063035-0000-0000-C000-000000000046}")
public interface _TaskItem extends IDispatch {
  @DeclDISPID(61440)  public _Application getApplication() throws ComException;
  @DeclDISPID(61450)  public OlObjectClass getClass_() throws ComException;
  @DeclDISPID(61451)  public _NameSpace getSession() throws ComException;
  @DeclDISPID(61441)  public Dispatch getParent() throws ComException;
  @DeclDISPID(63511)  public Actions getActions() throws ComException;
  @DeclDISPID(63509)  public Attachments getAttachments() throws ComException;
  @DeclDISPID(34101)  public String getBillingInformation() throws ComException;
  @DeclDISPID(34101)  public void setBillingInformation(String value) throws ComException;
  @DeclDISPID(37120)  public String getBody() throws ComException;
  @DeclDISPID(37120)  public void setBody(String value) throws ComException;
  @DeclDISPID(36865)  public String getCategories() throws ComException;
  @DeclDISPID(36865)  public void setCategories(String value) throws ComException;
  @DeclDISPID(34107)  public String getCompanies() throws ComException;
  @DeclDISPID(34107)  public void setCompanies(String value) throws ComException;
  @DeclDISPID(64192)  public String getConversationIndex() throws ComException;
  @DeclDISPID(112)  public String getConversationTopic() throws ComException;
  @DeclDISPID(12295)  public java.util.Date getCreationTime() throws ComException;
  @DeclDISPID(61470)  public String getEntryID() throws ComException;
  @DeclDISPID(61589)  public FormDescription getFormDescription() throws ComException;
  @DeclDISPID(61502)  public _Inspector getGetInspector() throws ComException;
  @DeclDISPID(23)  public OlImportance getImportance() throws ComException;
  @DeclDISPID(23)  public void setImportance(OlImportance value) throws ComException;
  @DeclDISPID(12296)  public java.util.Date getLastModificationTime() throws ComException;
  @DeclDISPID(26)  public String getMessageClass() throws ComException;
  @DeclDISPID(26)  public void setMessageClass(String value) throws ComException;
  @DeclDISPID(34100)  public String getMileage() throws ComException;
  @DeclDISPID(34100)  public void setMileage(String value) throws ComException;
  @DeclDISPID(34062)  public Boolean getNoAging() throws ComException;
  @DeclDISPID(34062)  public void setNoAging(Boolean value) throws ComException;
  @DeclDISPID(34130)  public Integer getOutlookInternalVersion() throws ComException;
  @DeclDISPID(34132)  public String getOutlookVersion() throws ComException;
  @DeclDISPID(61603)  public Boolean getSaved() throws ComException;
  @DeclDISPID(54)  public OlSensitivity getSensitivity() throws ComException;
  @DeclDISPID(54)  public void setSensitivity(OlSensitivity value) throws ComException;
  @DeclDISPID(3592)  public Integer getSize() throws ComException;
  @DeclDISPID(55)  public String getSubject() throws ComException;
  @DeclDISPID(55)  public void setSubject(String value) throws ComException;
  @DeclDISPID(61468)  public Boolean getUnRead() throws ComException;
  @DeclDISPID(61468)  public void setUnRead(Boolean value) throws ComException;
  @DeclDISPID(63510)  public UserProperties getUserProperties() throws ComException;
  @DeclDISPID(61475)  public void Close(OlInspectorClose SaveMode) throws ComException;
  @DeclDISPID(61490)  public Dispatch Copy() throws ComException;
  @DeclDISPID(61514)  public void Delete() throws ComException;
  @DeclDISPID(61606)  public void Display(Object Modal) throws ComException;
  @DeclDISPID(61492)  public Dispatch Move(MAPIFolder DestFldr) throws ComException;
  @DeclDISPID(61491)  public void PrintOut() throws ComException;
  @DeclDISPID(61512)  public void Save() throws ComException;
  @DeclDISPID(61521)  public void SaveAs(String Path, Object Type) throws ComException;
  @DeclDISPID(33040)  public Integer getActualWork() throws ComException;
  @DeclDISPID(33040)  public void setActualWork(Integer value) throws ComException;
  @DeclDISPID(33067)  public String getCardData() throws ComException;
  @DeclDISPID(33067)  public void setCardData(String value) throws ComException;
  @DeclDISPID(33052)  public Boolean getComplete() throws ComException;
  @DeclDISPID(33052)  public void setComplete(Boolean value) throws ComException;
  @DeclDISPID(34108)  public String getContactNames() throws ComException;
  @DeclDISPID(34108)  public void setContactNames(String value) throws ComException;
  @DeclDISPID(33039)  public java.util.Date getDateCompleted() throws ComException;
  @DeclDISPID(33039)  public void setDateCompleted(java.util.Date value) throws ComException;
  @DeclDISPID(33066)  public OlTaskDelegationState getDelegationState() throws ComException;
  @DeclDISPID(33057)  public String getDelegator() throws ComException;
  @DeclDISPID(33029)  public java.util.Date getDueDate() throws ComException;
  @DeclDISPID(33029)  public void setDueDate(java.util.Date value) throws ComException;
  @DeclDISPID(62999)  public Boolean getIsRecurring() throws ComException;
  @DeclDISPID(33059)  public Integer getOrdinal() throws ComException;
  @DeclDISPID(33059)  public void setOrdinal(Integer value) throws ComException;
  @DeclDISPID(33055)  public String getOwner() throws ComException;
  @DeclDISPID(33055)  public void setOwner(String value) throws ComException;
  @DeclDISPID(33065)  public OlTaskOwnership getOwnership() throws ComException;
  @DeclDISPID(63007)  public Integer getPercentComplete() throws ComException;
  @DeclDISPID(63007)  public void setPercentComplete(Integer value) throws ComException;
  @DeclDISPID(63508)  public Recipients getRecipients() throws ComException;
  @DeclDISPID(34050)  public java.util.Date getReminderTime() throws ComException;
  @DeclDISPID(34050)  public void setReminderTime(java.util.Date value) throws ComException;
  @DeclDISPID(34076)  public Boolean getReminderOverrideDefault() throws ComException;
  @DeclDISPID(34076)  public void setReminderOverrideDefault(Boolean value) throws ComException;
  @DeclDISPID(34078)  public Boolean getReminderPlaySound() throws ComException;
  @DeclDISPID(34078)  public void setReminderPlaySound(Boolean value) throws ComException;
  @DeclDISPID(34051)  public Boolean getReminderSet() throws ComException;
  @DeclDISPID(34051)  public void setReminderSet(Boolean value) throws ComException;
  @DeclDISPID(34079)  public String getReminderSoundFile() throws ComException;
  @DeclDISPID(34079)  public void setReminderSoundFile(String value) throws ComException;
  @DeclDISPID(63011)  public OlTaskResponse getResponseState() throws ComException;
  @DeclDISPID(33063)  public String getRole() throws ComException;
  @DeclDISPID(33063)  public void setRole(String value) throws ComException;
  @DeclDISPID(33071)  public String getSchedulePlusPriority() throws ComException;
  @DeclDISPID(33071)  public void setSchedulePlusPriority(String value) throws ComException;
  @DeclDISPID(33028)  public java.util.Date getStartDate() throws ComException;
  @DeclDISPID(33028)  public void setStartDate(java.util.Date value) throws ComException;
  @DeclDISPID(33025)  public OlTaskStatus getStatus() throws ComException;
  @DeclDISPID(33025)  public void setStatus(OlTaskStatus value) throws ComException;
  @DeclDISPID(3586)  public String getStatusOnCompletionRecipients() throws ComException;
  @DeclDISPID(3586)  public void setStatusOnCompletionRecipients(String value) throws ComException;
  @DeclDISPID(3587)  public String getStatusUpdateRecipients() throws ComException;
  @DeclDISPID(3587)  public void setStatusUpdateRecipients(String value) throws ComException;
  @DeclDISPID(33027)  public Boolean getTeamTask() throws ComException;
  @DeclDISPID(33027)  public void setTeamTask(Boolean value) throws ComException;
  @DeclDISPID(33041)  public Integer getTotalWork() throws ComException;
  @DeclDISPID(33041)  public void setTotalWork(Integer value) throws ComException;
  @DeclDISPID(63008)  public TaskItem Assign() throws ComException;
  @DeclDISPID(63010)  public void CancelResponseState() throws ComException;
  @DeclDISPID(61605)  public void ClearRecurrencePattern() throws ComException;
  @DeclDISPID(61604)  public RecurrencePattern GetRecurrencePattern() throws ComException;
  @DeclDISPID(62989)  public void MarkComplete() throws ComException;
  @DeclDISPID(63009)  public TaskItem Respond(OlTaskResponse Response, Object fNoUI, Object fAdditionalTextDialog) throws ComException;
  @DeclDISPID(61557)  public void Send() throws ComException;
  @DeclDISPID(63012)  public Boolean SkipRecurrence() throws ComException;
  @DeclDISPID(62994)  public Dispatch StatusReport() throws ComException;
  @DeclDISPID(64077)  public OlDownloadState getDownloadState() throws ComException;
  @DeclDISPID(64011)  public void ShowCategoriesDialog() throws ComException;
  @DeclDISPID(64009)  public ItemProperties getItemProperties() throws ComException;
  @DeclDISPID(16350)  public Integer getInternetCodepage() throws ComException;
  @DeclDISPID(16350)  public void setInternetCodepage(Integer value) throws ComException;
  @DeclDISPID(34161)  public OlRemoteStatus getMarkForDownload() throws ComException;
  @DeclDISPID(34161)  public void setMarkForDownload(OlRemoteStatus value) throws ComException;
  @DeclDISPID(64164)  public Boolean getIsConflict() throws ComException;
  @DeclDISPID(64186)  public Boolean getAutoResolvedWinner() throws ComException;
  @DeclDISPID(64187)  public Conflicts getConflicts() throws ComException;
  @DeclDISPID(64253)  public PropertyAccessor getPropertyAccessor() throws ComException;
  @DeclDISPID(64209)  public Account getSendUsingAccount() throws ComException;
  @DeclDISPID(64209)  public void setSendUsingAccount(Account value) throws ComException;
  @DeclDISPID(34208)  public java.util.Date getToDoTaskOrdinal() throws ComException;
  @DeclDISPID(34208)  public void setToDoTaskOrdinal(java.util.Date value) throws ComException;
  @DeclDISPID(64596)  public _Conversation GetConversation() throws ComException;
  @DeclDISPID(64629)  public String getConversationID() throws ComException;
  @DeclDISPID(64644)  public Object getRTFBody() throws ComException;
  @DeclDISPID(64644)  public void setRTFBody(Object value) throws ComException;
}
