/* ** GENEREATED FILE - DO NOT MODIFY ** */
package com.wilutions.mslib.outlook;
import com.wilutions.com.*;

/**
 * OlObjectClass.
 * 
 */
@SuppressWarnings("all")
@CoInterface(guid="{00000000-0000-0000-0000-000000000000}")
public class OlObjectClass {
  static boolean __typelib__loaded = __TypeLib.load();

  // Typed constants
  public final static OlObjectClass olApplication = new OlObjectClass(0);
  public final static OlObjectClass olNamespace = new OlObjectClass(1);
  public final static OlObjectClass olFolder = new OlObjectClass(2);
  public final static OlObjectClass olRecipient = new OlObjectClass(4);
  public final static OlObjectClass olAttachment = new OlObjectClass(5);
  public final static OlObjectClass olAddressList = new OlObjectClass(7);
  public final static OlObjectClass olAddressEntry = new OlObjectClass(8);
  public final static OlObjectClass olFolders = new OlObjectClass(15);
  public final static OlObjectClass olItems = new OlObjectClass(16);
  public final static OlObjectClass olRecipients = new OlObjectClass(17);
  public final static OlObjectClass olAttachments = new OlObjectClass(18);
  public final static OlObjectClass olAddressLists = new OlObjectClass(20);
  public final static OlObjectClass olAddressEntries = new OlObjectClass(21);
  public final static OlObjectClass olAppointment = new OlObjectClass(26);
  public final static OlObjectClass olMeetingRequest = new OlObjectClass(53);
  public final static OlObjectClass olMeetingCancellation = new OlObjectClass(54);
  public final static OlObjectClass olMeetingResponseNegative = new OlObjectClass(55);
  public final static OlObjectClass olMeetingResponsePositive = new OlObjectClass(56);
  public final static OlObjectClass olMeetingResponseTentative = new OlObjectClass(57);
  public final static OlObjectClass olRecurrencePattern = new OlObjectClass(28);
  public final static OlObjectClass olExceptions = new OlObjectClass(29);
  public final static OlObjectClass olException = new OlObjectClass(30);
  public final static OlObjectClass olAction = new OlObjectClass(32);
  public final static OlObjectClass olActions = new OlObjectClass(33);
  public final static OlObjectClass olExplorer = new OlObjectClass(34);
  public final static OlObjectClass olInspector = new OlObjectClass(35);
  public final static OlObjectClass olPages = new OlObjectClass(36);
  public final static OlObjectClass olFormDescription = new OlObjectClass(37);
  public final static OlObjectClass olUserProperties = new OlObjectClass(38);
  public final static OlObjectClass olUserProperty = new OlObjectClass(39);
  public final static OlObjectClass olContact = new OlObjectClass(40);
  public final static OlObjectClass olDocument = new OlObjectClass(41);
  public final static OlObjectClass olJournal = new OlObjectClass(42);
  public final static OlObjectClass olMail = new OlObjectClass(43);
  public final static OlObjectClass olNote = new OlObjectClass(44);
  public final static OlObjectClass olPost = new OlObjectClass(45);
  public final static OlObjectClass olReport = new OlObjectClass(46);
  public final static OlObjectClass olRemote = new OlObjectClass(47);
  public final static OlObjectClass olTask = new OlObjectClass(48);
  public final static OlObjectClass olTaskRequest = new OlObjectClass(49);
  public final static OlObjectClass olTaskRequestUpdate = new OlObjectClass(50);
  public final static OlObjectClass olTaskRequestAccept = new OlObjectClass(51);
  public final static OlObjectClass olTaskRequestDecline = new OlObjectClass(52);
  public final static OlObjectClass olExplorers = new OlObjectClass(60);
  public final static OlObjectClass olInspectors = new OlObjectClass(61);
  public final static OlObjectClass olPanes = new OlObjectClass(62);
  public final static OlObjectClass olOutlookBarPane = new OlObjectClass(63);
  public final static OlObjectClass olOutlookBarStorage = new OlObjectClass(64);
  public final static OlObjectClass olOutlookBarGroups = new OlObjectClass(65);
  public final static OlObjectClass olOutlookBarGroup = new OlObjectClass(66);
  public final static OlObjectClass olOutlookBarShortcuts = new OlObjectClass(67);
  public final static OlObjectClass olOutlookBarShortcut = new OlObjectClass(68);
  public final static OlObjectClass olDistributionList = new OlObjectClass(69);
  public final static OlObjectClass olPropertyPageSite = new OlObjectClass(70);
  public final static OlObjectClass olPropertyPages = new OlObjectClass(71);
  public final static OlObjectClass olSyncObject = new OlObjectClass(72);
  public final static OlObjectClass olSyncObjects = new OlObjectClass(73);
  public final static OlObjectClass olSelection = new OlObjectClass(74);
  public final static OlObjectClass olLink = new OlObjectClass(75);
  public final static OlObjectClass olLinks = new OlObjectClass(76);
  public final static OlObjectClass olSearch = new OlObjectClass(77);
  public final static OlObjectClass olResults = new OlObjectClass(78);
  public final static OlObjectClass olViews = new OlObjectClass(79);
  public final static OlObjectClass olView = new OlObjectClass(80);
  public final static OlObjectClass olItemProperties = new OlObjectClass(98);
  public final static OlObjectClass olItemProperty = new OlObjectClass(99);
  public final static OlObjectClass olReminders = new OlObjectClass(100);
  public final static OlObjectClass olReminder = new OlObjectClass(101);
  public final static OlObjectClass olConflict = new OlObjectClass(102);
  public final static OlObjectClass olConflicts = new OlObjectClass(103);
  public final static OlObjectClass olSharing = new OlObjectClass(104);
  public final static OlObjectClass olAccount = new OlObjectClass(105);
  public final static OlObjectClass olAccounts = new OlObjectClass(106);
  public final static OlObjectClass olStore = new OlObjectClass(107);
  public final static OlObjectClass olStores = new OlObjectClass(108);
  public final static OlObjectClass olSelectNamesDialog = new OlObjectClass(109);
  public final static OlObjectClass olExchangeUser = new OlObjectClass(110);
  public final static OlObjectClass olExchangeDistributionList = new OlObjectClass(111);
  public final static OlObjectClass olPropertyAccessor = new OlObjectClass(112);
  public final static OlObjectClass olStorageItem = new OlObjectClass(113);
  public final static OlObjectClass olRules = new OlObjectClass(114);
  public final static OlObjectClass olRule = new OlObjectClass(115);
  public final static OlObjectClass olRuleActions = new OlObjectClass(116);
  public final static OlObjectClass olRuleAction = new OlObjectClass(117);
  public final static OlObjectClass olMoveOrCopyRuleAction = new OlObjectClass(118);
  public final static OlObjectClass olSendRuleAction = new OlObjectClass(119);
  public final static OlObjectClass olTable = new OlObjectClass(120);
  public final static OlObjectClass olRow = new OlObjectClass(121);
  public final static OlObjectClass olAssignToCategoryRuleAction = new OlObjectClass(122);
  public final static OlObjectClass olPlaySoundRuleAction = new OlObjectClass(123);
  public final static OlObjectClass olMarkAsTaskRuleAction = new OlObjectClass(124);
  public final static OlObjectClass olNewItemAlertRuleAction = new OlObjectClass(125);
  public final static OlObjectClass olRuleConditions = new OlObjectClass(126);
  public final static OlObjectClass olRuleCondition = new OlObjectClass(127);
  public final static OlObjectClass olImportanceRuleCondition = new OlObjectClass(128);
  public final static OlObjectClass olFormRegion = new OlObjectClass(129);
  public final static OlObjectClass olCategoryRuleCondition = new OlObjectClass(130);
  public final static OlObjectClass olFormNameRuleCondition = new OlObjectClass(131);
  public final static OlObjectClass olFromRuleCondition = new OlObjectClass(132);
  public final static OlObjectClass olSenderInAddressListRuleCondition = new OlObjectClass(133);
  public final static OlObjectClass olTextRuleCondition = new OlObjectClass(134);
  public final static OlObjectClass olAccountRuleCondition = new OlObjectClass(135);
  public final static OlObjectClass olClassTableView = new OlObjectClass(136);
  public final static OlObjectClass olClassIconView = new OlObjectClass(137);
  public final static OlObjectClass olClassCardView = new OlObjectClass(138);
  public final static OlObjectClass olClassCalendarView = new OlObjectClass(139);
  public final static OlObjectClass olClassTimeLineView = new OlObjectClass(140);
  public final static OlObjectClass olViewFields = new OlObjectClass(141);
  public final static OlObjectClass olViewField = new OlObjectClass(142);
  public final static OlObjectClass olOrderField = new OlObjectClass(144);
  public final static OlObjectClass olOrderFields = new OlObjectClass(145);
  public final static OlObjectClass olViewFont = new OlObjectClass(146);
  public final static OlObjectClass olAutoFormatRule = new OlObjectClass(147);
  public final static OlObjectClass olAutoFormatRules = new OlObjectClass(148);
  public final static OlObjectClass olColumnFormat = new OlObjectClass(149);
  public final static OlObjectClass olColumns = new OlObjectClass(150);
  public final static OlObjectClass olCalendarSharing = new OlObjectClass(151);
  public final static OlObjectClass olCategory = new OlObjectClass(152);
  public final static OlObjectClass olCategories = new OlObjectClass(153);
  public final static OlObjectClass olColumn = new OlObjectClass(154);
  public final static OlObjectClass olClassNavigationPane = new OlObjectClass(155);
  public final static OlObjectClass olNavigationModules = new OlObjectClass(156);
  public final static OlObjectClass olNavigationModule = new OlObjectClass(157);
  public final static OlObjectClass olMailModule = new OlObjectClass(158);
  public final static OlObjectClass olCalendarModule = new OlObjectClass(159);
  public final static OlObjectClass olContactsModule = new OlObjectClass(160);
  public final static OlObjectClass olTasksModule = new OlObjectClass(161);
  public final static OlObjectClass olJournalModule = new OlObjectClass(162);
  public final static OlObjectClass olNotesModule = new OlObjectClass(163);
  public final static OlObjectClass olNavigationGroups = new OlObjectClass(164);
  public final static OlObjectClass olNavigationGroup = new OlObjectClass(165);
  public final static OlObjectClass olNavigationFolders = new OlObjectClass(166);
  public final static OlObjectClass olNavigationFolder = new OlObjectClass(167);
  public final static OlObjectClass olClassBusinessCardView = new OlObjectClass(168);
  public final static OlObjectClass olAttachmentSelection = new OlObjectClass(169);
  public final static OlObjectClass olAddressRuleCondition = new OlObjectClass(170);
  public final static OlObjectClass olUserDefinedProperty = new OlObjectClass(171);
  public final static OlObjectClass olUserDefinedProperties = new OlObjectClass(172);
  public final static OlObjectClass olFromRssFeedRuleCondition = new OlObjectClass(173);
  public final static OlObjectClass olClassTimeZone = new OlObjectClass(174);
  public final static OlObjectClass olClassTimeZones = new OlObjectClass(175);
  public final static OlObjectClass olMobile = new OlObjectClass(176);
  public final static OlObjectClass olSolutionsModule = new OlObjectClass(177);
  public final static OlObjectClass olConversation = new OlObjectClass(178);
  public final static OlObjectClass olSimpleItems = new OlObjectClass(179);
  public final static OlObjectClass olOutspace = new OlObjectClass(180);
  public final static OlObjectClass olMeetingForwardNotification = new OlObjectClass(181);
  public final static OlObjectClass olConversationHeader = new OlObjectClass(182);
  public final static OlObjectClass olClassPeopleView = new OlObjectClass(183);

  // Integer constants for bitsets and switch statements
  public final static int _olApplication = 0;
  public final static int _olNamespace = 1;
  public final static int _olFolder = 2;
  public final static int _olRecipient = 4;
  public final static int _olAttachment = 5;
  public final static int _olAddressList = 7;
  public final static int _olAddressEntry = 8;
  public final static int _olFolders = 15;
  public final static int _olItems = 16;
  public final static int _olRecipients = 17;
  public final static int _olAttachments = 18;
  public final static int _olAddressLists = 20;
  public final static int _olAddressEntries = 21;
  public final static int _olAppointment = 26;
  public final static int _olMeetingRequest = 53;
  public final static int _olMeetingCancellation = 54;
  public final static int _olMeetingResponseNegative = 55;
  public final static int _olMeetingResponsePositive = 56;
  public final static int _olMeetingResponseTentative = 57;
  public final static int _olRecurrencePattern = 28;
  public final static int _olExceptions = 29;
  public final static int _olException = 30;
  public final static int _olAction = 32;
  public final static int _olActions = 33;
  public final static int _olExplorer = 34;
  public final static int _olInspector = 35;
  public final static int _olPages = 36;
  public final static int _olFormDescription = 37;
  public final static int _olUserProperties = 38;
  public final static int _olUserProperty = 39;
  public final static int _olContact = 40;
  public final static int _olDocument = 41;
  public final static int _olJournal = 42;
  public final static int _olMail = 43;
  public final static int _olNote = 44;
  public final static int _olPost = 45;
  public final static int _olReport = 46;
  public final static int _olRemote = 47;
  public final static int _olTask = 48;
  public final static int _olTaskRequest = 49;
  public final static int _olTaskRequestUpdate = 50;
  public final static int _olTaskRequestAccept = 51;
  public final static int _olTaskRequestDecline = 52;
  public final static int _olExplorers = 60;
  public final static int _olInspectors = 61;
  public final static int _olPanes = 62;
  public final static int _olOutlookBarPane = 63;
  public final static int _olOutlookBarStorage = 64;
  public final static int _olOutlookBarGroups = 65;
  public final static int _olOutlookBarGroup = 66;
  public final static int _olOutlookBarShortcuts = 67;
  public final static int _olOutlookBarShortcut = 68;
  public final static int _olDistributionList = 69;
  public final static int _olPropertyPageSite = 70;
  public final static int _olPropertyPages = 71;
  public final static int _olSyncObject = 72;
  public final static int _olSyncObjects = 73;
  public final static int _olSelection = 74;
  public final static int _olLink = 75;
  public final static int _olLinks = 76;
  public final static int _olSearch = 77;
  public final static int _olResults = 78;
  public final static int _olViews = 79;
  public final static int _olView = 80;
  public final static int _olItemProperties = 98;
  public final static int _olItemProperty = 99;
  public final static int _olReminders = 100;
  public final static int _olReminder = 101;
  public final static int _olConflict = 102;
  public final static int _olConflicts = 103;
  public final static int _olSharing = 104;
  public final static int _olAccount = 105;
  public final static int _olAccounts = 106;
  public final static int _olStore = 107;
  public final static int _olStores = 108;
  public final static int _olSelectNamesDialog = 109;
  public final static int _olExchangeUser = 110;
  public final static int _olExchangeDistributionList = 111;
  public final static int _olPropertyAccessor = 112;
  public final static int _olStorageItem = 113;
  public final static int _olRules = 114;
  public final static int _olRule = 115;
  public final static int _olRuleActions = 116;
  public final static int _olRuleAction = 117;
  public final static int _olMoveOrCopyRuleAction = 118;
  public final static int _olSendRuleAction = 119;
  public final static int _olTable = 120;
  public final static int _olRow = 121;
  public final static int _olAssignToCategoryRuleAction = 122;
  public final static int _olPlaySoundRuleAction = 123;
  public final static int _olMarkAsTaskRuleAction = 124;
  public final static int _olNewItemAlertRuleAction = 125;
  public final static int _olRuleConditions = 126;
  public final static int _olRuleCondition = 127;
  public final static int _olImportanceRuleCondition = 128;
  public final static int _olFormRegion = 129;
  public final static int _olCategoryRuleCondition = 130;
  public final static int _olFormNameRuleCondition = 131;
  public final static int _olFromRuleCondition = 132;
  public final static int _olSenderInAddressListRuleCondition = 133;
  public final static int _olTextRuleCondition = 134;
  public final static int _olAccountRuleCondition = 135;
  public final static int _olClassTableView = 136;
  public final static int _olClassIconView = 137;
  public final static int _olClassCardView = 138;
  public final static int _olClassCalendarView = 139;
  public final static int _olClassTimeLineView = 140;
  public final static int _olViewFields = 141;
  public final static int _olViewField = 142;
  public final static int _olOrderField = 144;
  public final static int _olOrderFields = 145;
  public final static int _olViewFont = 146;
  public final static int _olAutoFormatRule = 147;
  public final static int _olAutoFormatRules = 148;
  public final static int _olColumnFormat = 149;
  public final static int _olColumns = 150;
  public final static int _olCalendarSharing = 151;
  public final static int _olCategory = 152;
  public final static int _olCategories = 153;
  public final static int _olColumn = 154;
  public final static int _olClassNavigationPane = 155;
  public final static int _olNavigationModules = 156;
  public final static int _olNavigationModule = 157;
  public final static int _olMailModule = 158;
  public final static int _olCalendarModule = 159;
  public final static int _olContactsModule = 160;
  public final static int _olTasksModule = 161;
  public final static int _olJournalModule = 162;
  public final static int _olNotesModule = 163;
  public final static int _olNavigationGroups = 164;
  public final static int _olNavigationGroup = 165;
  public final static int _olNavigationFolders = 166;
  public final static int _olNavigationFolder = 167;
  public final static int _olClassBusinessCardView = 168;
  public final static int _olAttachmentSelection = 169;
  public final static int _olAddressRuleCondition = 170;
  public final static int _olUserDefinedProperty = 171;
  public final static int _olUserDefinedProperties = 172;
  public final static int _olFromRssFeedRuleCondition = 173;
  public final static int _olClassTimeZone = 174;
  public final static int _olClassTimeZones = 175;
  public final static int _olMobile = 176;
  public final static int _olSolutionsModule = 177;
  public final static int _olConversation = 178;
  public final static int _olSimpleItems = 179;
  public final static int _olOutspace = 180;
  public final static int _olMeetingForwardNotification = 181;
  public final static int _olConversationHeader = 182;
  public final static int _olClassPeopleView = 183;

  // Value, readonly field.
  public final int value;

  // Private constructor, use valueOf to create an instance.
  private OlObjectClass(int value) { this.value = value; }

  // Return one of the predefined typed constants for the given value or create a new object.
  public static  OlObjectClass valueOf(int value) {
    switch(value) {
    case 0: return olApplication;
    case 1: return olNamespace;
    case 2: return olFolder;
    case 4: return olRecipient;
    case 5: return olAttachment;
    case 7: return olAddressList;
    case 8: return olAddressEntry;
    case 15: return olFolders;
    case 16: return olItems;
    case 17: return olRecipients;
    case 18: return olAttachments;
    case 20: return olAddressLists;
    case 21: return olAddressEntries;
    case 26: return olAppointment;
    case 53: return olMeetingRequest;
    case 54: return olMeetingCancellation;
    case 55: return olMeetingResponseNegative;
    case 56: return olMeetingResponsePositive;
    case 57: return olMeetingResponseTentative;
    case 28: return olRecurrencePattern;
    case 29: return olExceptions;
    case 30: return olException;
    case 32: return olAction;
    case 33: return olActions;
    case 34: return olExplorer;
    case 35: return olInspector;
    case 36: return olPages;
    case 37: return olFormDescription;
    case 38: return olUserProperties;
    case 39: return olUserProperty;
    case 40: return olContact;
    case 41: return olDocument;
    case 42: return olJournal;
    case 43: return olMail;
    case 44: return olNote;
    case 45: return olPost;
    case 46: return olReport;
    case 47: return olRemote;
    case 48: return olTask;
    case 49: return olTaskRequest;
    case 50: return olTaskRequestUpdate;
    case 51: return olTaskRequestAccept;
    case 52: return olTaskRequestDecline;
    case 60: return olExplorers;
    case 61: return olInspectors;
    case 62: return olPanes;
    case 63: return olOutlookBarPane;
    case 64: return olOutlookBarStorage;
    case 65: return olOutlookBarGroups;
    case 66: return olOutlookBarGroup;
    case 67: return olOutlookBarShortcuts;
    case 68: return olOutlookBarShortcut;
    case 69: return olDistributionList;
    case 70: return olPropertyPageSite;
    case 71: return olPropertyPages;
    case 72: return olSyncObject;
    case 73: return olSyncObjects;
    case 74: return olSelection;
    case 75: return olLink;
    case 76: return olLinks;
    case 77: return olSearch;
    case 78: return olResults;
    case 79: return olViews;
    case 80: return olView;
    case 98: return olItemProperties;
    case 99: return olItemProperty;
    case 100: return olReminders;
    case 101: return olReminder;
    case 102: return olConflict;
    case 103: return olConflicts;
    case 104: return olSharing;
    case 105: return olAccount;
    case 106: return olAccounts;
    case 107: return olStore;
    case 108: return olStores;
    case 109: return olSelectNamesDialog;
    case 110: return olExchangeUser;
    case 111: return olExchangeDistributionList;
    case 112: return olPropertyAccessor;
    case 113: return olStorageItem;
    case 114: return olRules;
    case 115: return olRule;
    case 116: return olRuleActions;
    case 117: return olRuleAction;
    case 118: return olMoveOrCopyRuleAction;
    case 119: return olSendRuleAction;
    case 120: return olTable;
    case 121: return olRow;
    case 122: return olAssignToCategoryRuleAction;
    case 123: return olPlaySoundRuleAction;
    case 124: return olMarkAsTaskRuleAction;
    case 125: return olNewItemAlertRuleAction;
    case 126: return olRuleConditions;
    case 127: return olRuleCondition;
    case 128: return olImportanceRuleCondition;
    case 129: return olFormRegion;
    case 130: return olCategoryRuleCondition;
    case 131: return olFormNameRuleCondition;
    case 132: return olFromRuleCondition;
    case 133: return olSenderInAddressListRuleCondition;
    case 134: return olTextRuleCondition;
    case 135: return olAccountRuleCondition;
    case 136: return olClassTableView;
    case 137: return olClassIconView;
    case 138: return olClassCardView;
    case 139: return olClassCalendarView;
    case 140: return olClassTimeLineView;
    case 141: return olViewFields;
    case 142: return olViewField;
    case 144: return olOrderField;
    case 145: return olOrderFields;
    case 146: return olViewFont;
    case 147: return olAutoFormatRule;
    case 148: return olAutoFormatRules;
    case 149: return olColumnFormat;
    case 150: return olColumns;
    case 151: return olCalendarSharing;
    case 152: return olCategory;
    case 153: return olCategories;
    case 154: return olColumn;
    case 155: return olClassNavigationPane;
    case 156: return olNavigationModules;
    case 157: return olNavigationModule;
    case 158: return olMailModule;
    case 159: return olCalendarModule;
    case 160: return olContactsModule;
    case 161: return olTasksModule;
    case 162: return olJournalModule;
    case 163: return olNotesModule;
    case 164: return olNavigationGroups;
    case 165: return olNavigationGroup;
    case 166: return olNavigationFolders;
    case 167: return olNavigationFolder;
    case 168: return olClassBusinessCardView;
    case 169: return olAttachmentSelection;
    case 170: return olAddressRuleCondition;
    case 171: return olUserDefinedProperty;
    case 172: return olUserDefinedProperties;
    case 173: return olFromRssFeedRuleCondition;
    case 174: return olClassTimeZone;
    case 175: return olClassTimeZones;
    case 176: return olMobile;
    case 177: return olSolutionsModule;
    case 178: return olConversation;
    case 179: return olSimpleItems;
    case 180: return olOutspace;
    case 181: return olMeetingForwardNotification;
    case 182: return olConversationHeader;
    case 183: return olClassPeopleView;
    default: return new OlObjectClass(value);
    }
  }
}
