/* ** GENEREATED FILE - DO NOT MODIFY ** */
package com.wilutions.mslib.office;
import com.wilutions.com.*;

/**
 * IMsoChart.
 * 
 */
@CoInterface(guid="{000C1709-0000-0000-C000-000000000046}")
public interface IMsoChart extends IDispatch {
  static boolean __typelib__loaded = __TypeLib.load();
  @DeclDISPID(150)  public IDispatch getParent() throws ComException;
  @DeclDISPID(1610743809)  public void setHasTitle(Boolean value) throws ComException;
  @DeclDISPID(1610743809)  public Boolean getHasTitle() throws ComException;
  @DeclDISPID(1610743811)  public IMsoChartTitle getChartTitle() throws ComException;
  @DeclDISPID(1610743812)  public Integer getDepthPercent() throws ComException;
  @DeclDISPID(1610743812)  public void setDepthPercent(Integer value) throws ComException;
  @DeclDISPID(1610743814)  public Integer getElevation() throws ComException;
  @DeclDISPID(1610743814)  public void setElevation(Integer value) throws ComException;
  @DeclDISPID(1610743816)  public Integer getGapDepth() throws ComException;
  @DeclDISPID(1610743816)  public void setGapDepth(Integer value) throws ComException;
  @DeclDISPID(1610743818)  public Integer getHeightPercent() throws ComException;
  @DeclDISPID(1610743818)  public void setHeightPercent(Integer value) throws ComException;
  @DeclDISPID(1610743820)  public Integer getPerspective() throws ComException;
  @DeclDISPID(1610743820)  public void setPerspective(Integer value) throws ComException;
  @DeclDISPID(1610743822)  public Object getRightAngleAxes() throws ComException;
  @DeclDISPID(1610743822)  public void setRightAngleAxes(Object value) throws ComException;
  @DeclDISPID(1610743824)  public Object getRotation() throws ComException;
  @DeclDISPID(1610743824)  public void setRotation(Object value) throws ComException;
  @DeclDISPID(1610743826)  public void setDisplayBlanksAs(XlDisplayBlanksAs value) throws ComException;
  @DeclDISPID(1610743826)  public XlDisplayBlanksAs getDisplayBlanksAs() throws ComException;
  @DeclDISPID(1610743828)  public void setProtectData(Boolean value) throws ComException;
  @DeclDISPID(1610743828)  public Boolean getProtectData() throws ComException;
  @DeclDISPID(1610743830)  public void setProtectFormatting(Boolean value) throws ComException;
  @DeclDISPID(1610743830)  public Boolean getProtectFormatting() throws ComException;
  @DeclDISPID(1610743832)  public void setProtectGoalSeek(Boolean value) throws ComException;
  @DeclDISPID(1610743832)  public Boolean getProtectGoalSeek() throws ComException;
  @DeclDISPID(1610743834)  public void setProtectSelection(Boolean value) throws ComException;
  @DeclDISPID(1610743834)  public Boolean getProtectSelection() throws ComException;
  @DeclDISPID(1610743836)  public void setProtectChartObjects(Boolean value) throws ComException;
  @DeclDISPID(1610743836)  public Boolean getProtectChartObjects() throws ComException;
  @DeclDISPID(1610743838)  public void UnProtect(Object Password) throws ComException;
  @DeclDISPID(1610743839)  public void Protect(Object Password, Object DrawingObjects, Object Contents, Object Scenarios, Object UserInterfaceOnly) throws ComException;
  @DeclDISPID(8)  public IDispatch getChartGroups(Object pvarIndex, Object varIgallery) throws ComException;
  @DeclDISPID(68)  public IDispatch SeriesCollection(Object Index) throws ComException;
  @DeclDISPID(1922)  public void ApplyDataLabels(XlDataLabelsType Type, Object IMsoLegendKey, Object AutoText, Object HasLeaderLines, Object ShowSeriesName, Object ShowCategoryName, Object ShowValue, Object ShowPercentage, Object ShowBubbleSize, Object Separator) throws ComException;
  @DeclDISPID(1400)  public XlChartType getChartType() throws ComException;
  @DeclDISPID(1400)  public void setChartType(XlChartType value) throws ComException;
  @DeclDISPID(1396)  public Boolean getHasDataTable() throws ComException;
  @DeclDISPID(1396)  public void setHasDataTable(Boolean value) throws ComException;
  @DeclDISPID(1401)  public void ApplyCustomType(XlChartType ChartType, Object TypeName) throws ComException;
  @DeclDISPID(1409)  public void GetChartElement(Integer x, Integer y, ByRef<Integer> ElementID, ByRef<Integer> Arg1, ByRef<Integer> Arg2) throws ComException;
  @DeclDISPID(1413)  public void SetSourceData(String Source, Object PlotBy) throws ComException;
  @DeclDISPID(202)  public XlRowCol getPlotBy() throws ComException;
  @DeclDISPID(202)  public void setPlotBy(XlRowCol value) throws ComException;
  @DeclDISPID(53)  public Boolean getHasLegend() throws ComException;
  @DeclDISPID(53)  public void setHasLegend(Boolean value) throws ComException;
  @DeclDISPID(84)  public IMsoLegend getLegend() throws ComException;
  @DeclDISPID(1610743861)  public IDispatch Axes(Object Type, XlAxisGroup AxisGroup) throws ComException;
  @DeclDISPID(1610743862)  public void setHasAxis(Object axisType, Object AxisGroup, Object value3) throws ComException;
  @DeclDISPID(1610743862)  public Object getHasAxis(Object axisType, Object AxisGroup) throws ComException;
  @DeclDISPID(1610743864)  public IMsoWalls getWalls(Boolean fBackWall) throws ComException;
  @DeclDISPID(1610743865)  public IMsoFloor getFloor() throws ComException;
  @DeclDISPID(1610743866)  public IMsoPlotArea getPlotArea() throws ComException;
  @DeclDISPID(92)  public Boolean getPlotVisibleOnly() throws ComException;
  @DeclDISPID(92)  public void setPlotVisibleOnly(Boolean value) throws ComException;
  @DeclDISPID(1610743869)  public IMsoChartArea getChartArea() throws ComException;
  @DeclDISPID(1610743870)  public void AutoFormat(Integer rGallery, Object varFormat) throws ComException;
  @DeclDISPID(1610743871)  public Boolean getAutoScaling() throws ComException;
  @DeclDISPID(1610743871)  public void setAutoScaling(Boolean value) throws ComException;
  @DeclDISPID(1610743873)  public void SetBackgroundPicture(String bstr) throws ComException;
  @DeclDISPID(1610743874)  public void ChartWizard(Object varSource, Object varGallery, Object varFormat, Object varPlotBy, Object varCategoryLabels, Object varSeriesLabels, Object varHasLegend, Object varTitle, Object varCategoryTitle, Object varValueTitle, Object varExtraTitle) throws ComException;
  @DeclDISPID(1610743875)  public void CopyPicture(Integer Appearance, Integer Format, Integer Size) throws ComException;
  @DeclDISPID(1610743876)  public IMsoDataTable getDataTable() throws ComException;
  @DeclDISPID(1610743877)  public Object Evaluate(Object varName, Integer LocaleID, ByRef<Integer> ObjType) throws ComException;
  @DeclDISPID(1610743878)  public Object _Evaluate(Object varName, Integer LocaleID) throws ComException;
  @DeclDISPID(1610743879)  public void Paste(Object varType) throws ComException;
  @DeclDISPID(1610743880)  public XlBarShape getBarShape() throws ComException;
  @DeclDISPID(1610743880)  public void setBarShape(XlBarShape value) throws ComException;
  @DeclDISPID(1610743882)  public Boolean Export(String bstr, Object varFilterName, Object varInteractive) throws ComException;
  @DeclDISPID(1610743883)  public void SetDefaultChart(Object varName) throws ComException;
  @DeclDISPID(1610743884)  public void ApplyChartTemplate(String bstrFileName) throws ComException;
  @DeclDISPID(1610743885)  public void SaveChartTemplate(String bstrFileName) throws ComException;
  @DeclDISPID(2377)  public IMsoWalls getSideWall() throws ComException;
  @DeclDISPID(2378)  public IMsoWalls getBackWall() throws ComException;
  @DeclDISPID(2465)  public Object getChartStyle() throws ComException;
  @DeclDISPID(2465)  public void setChartStyle(Object value) throws ComException;
  @DeclDISPID(2466)  public void ClearToMatchStyle() throws ComException;
  @DeclDISPID(1814)  public IDispatch getPivotLayout() throws ComException;
  @DeclDISPID(1610743894)  public void RefreshPivotTable() throws ComException;
  @DeclDISPID(1610743895)  public void setShowDataLabelsOverMaximum(Boolean value) throws ComException;
  @DeclDISPID(1610743895)  public Boolean getShowDataLabelsOverMaximum() throws ComException;
  @DeclDISPID(2468)  public void ApplyLayout(Integer Layout, Object varChartType) throws ComException;
  @DeclDISPID(1610743898)  public IDispatch getSelection() throws ComException;
  @DeclDISPID(1610743899)  public void Refresh() throws ComException;
  @DeclDISPID(1610743900)  public void SetElement(MsoChartElementType RHS) throws ComException;
  @DeclDISPID(1610743901)  public IMsoChartData getChartData() throws ComException;
  @DeclDISPID(1610743902)  public IMsoChartFormat getFormat() throws ComException;
  @DeclDISPID(1610743903)  public Shapes getShapes() throws ComException;
  @DeclDISPID(148)  public IDispatch getApplication() throws ComException;
  @DeclDISPID(149)  public Integer getCreator() throws ComException;
  @DeclDISPID(117)  public Object Delete() throws ComException;
  @DeclDISPID(551)  public Object Copy() throws ComException;
  @DeclDISPID(235)  public Object Select(Object Replace) throws ComException;
  @DeclDISPID(1610743923)  public Boolean getShowReportFilterFieldButtons() throws ComException;
  @DeclDISPID(1610743923)  public void setShowReportFilterFieldButtons(Boolean value) throws ComException;
  @DeclDISPID(1610743925)  public Boolean getShowLegendFieldButtons() throws ComException;
  @DeclDISPID(1610743925)  public void setShowLegendFieldButtons(Boolean value) throws ComException;
  @DeclDISPID(1610743927)  public Boolean getShowAxisFieldButtons() throws ComException;
  @DeclDISPID(1610743927)  public void setShowAxisFieldButtons(Boolean value) throws ComException;
  @DeclDISPID(1610743929)  public Boolean getShowValueFieldButtons() throws ComException;
  @DeclDISPID(1610743929)  public void setShowValueFieldButtons(Boolean value) throws ComException;
  @DeclDISPID(1610743931)  public Boolean getShowAllFieldButtons() throws ComException;
  @DeclDISPID(1610743931)  public void setShowAllFieldButtons(Boolean value) throws ComException;
  @DeclDISPID(1610743933)  public void setProtectChartSheetFormatting(Boolean value) throws ComException;
  @DeclDISPID(236)  public IDispatch FullSeriesCollection(Object Index) throws ComException;
  @DeclDISPID(237)  public void setCategoryLabelLevel(XlCategoryLabelLevel value) throws ComException;
  @DeclDISPID(237)  public XlCategoryLabelLevel getCategoryLabelLevel() throws ComException;
  @DeclDISPID(238)  public void setSeriesNameLevel(XlSeriesNameLevel value) throws ComException;
  @DeclDISPID(238)  public XlSeriesNameLevel getSeriesNameLevel() throws ComException;
  @DeclDISPID(2467)  public Object getChartColor() throws ComException;
  @DeclDISPID(2467)  public void setChartColor(Object value) throws ComException;
  @DeclDISPID(2469)  public void ClearToMatchColorStyle() throws ComException;
}
