/* ** GENEREATED FILE - DO NOT MODIFY ** */
package com.wilutions.mslib.office;
import com.wilutions.com.*;

/**
 * MsoAutoShapeType.
 * 
 */
@SuppressWarnings("all")
@CoInterface(guid="{00000000-0000-0000-0000-000000000000}")
public class MsoAutoShapeType {
  static boolean __typelib__loaded = __TypeLib.load();

  // Typed constants
  public final static MsoAutoShapeType msoShapeMixed = new MsoAutoShapeType(-2);
  public final static MsoAutoShapeType msoShapeRectangle = new MsoAutoShapeType(1);
  public final static MsoAutoShapeType msoShapeParallelogram = new MsoAutoShapeType(2);
  public final static MsoAutoShapeType msoShapeTrapezoid = new MsoAutoShapeType(3);
  public final static MsoAutoShapeType msoShapeDiamond = new MsoAutoShapeType(4);
  public final static MsoAutoShapeType msoShapeRoundedRectangle = new MsoAutoShapeType(5);
  public final static MsoAutoShapeType msoShapeOctagon = new MsoAutoShapeType(6);
  public final static MsoAutoShapeType msoShapeIsoscelesTriangle = new MsoAutoShapeType(7);
  public final static MsoAutoShapeType msoShapeRightTriangle = new MsoAutoShapeType(8);
  public final static MsoAutoShapeType msoShapeOval = new MsoAutoShapeType(9);
  public final static MsoAutoShapeType msoShapeHexagon = new MsoAutoShapeType(10);
  public final static MsoAutoShapeType msoShapeCross = new MsoAutoShapeType(11);
  public final static MsoAutoShapeType msoShapeRegularPentagon = new MsoAutoShapeType(12);
  public final static MsoAutoShapeType msoShapeCan = new MsoAutoShapeType(13);
  public final static MsoAutoShapeType msoShapeCube = new MsoAutoShapeType(14);
  public final static MsoAutoShapeType msoShapeBevel = new MsoAutoShapeType(15);
  public final static MsoAutoShapeType msoShapeFoldedCorner = new MsoAutoShapeType(16);
  public final static MsoAutoShapeType msoShapeSmileyFace = new MsoAutoShapeType(17);
  public final static MsoAutoShapeType msoShapeDonut = new MsoAutoShapeType(18);
  public final static MsoAutoShapeType msoShapeNoSymbol = new MsoAutoShapeType(19);
  public final static MsoAutoShapeType msoShapeBlockArc = new MsoAutoShapeType(20);
  public final static MsoAutoShapeType msoShapeHeart = new MsoAutoShapeType(21);
  public final static MsoAutoShapeType msoShapeLightningBolt = new MsoAutoShapeType(22);
  public final static MsoAutoShapeType msoShapeSun = new MsoAutoShapeType(23);
  public final static MsoAutoShapeType msoShapeMoon = new MsoAutoShapeType(24);
  public final static MsoAutoShapeType msoShapeArc = new MsoAutoShapeType(25);
  public final static MsoAutoShapeType msoShapeDoubleBracket = new MsoAutoShapeType(26);
  public final static MsoAutoShapeType msoShapeDoubleBrace = new MsoAutoShapeType(27);
  public final static MsoAutoShapeType msoShapePlaque = new MsoAutoShapeType(28);
  public final static MsoAutoShapeType msoShapeLeftBracket = new MsoAutoShapeType(29);
  public final static MsoAutoShapeType msoShapeRightBracket = new MsoAutoShapeType(30);
  public final static MsoAutoShapeType msoShapeLeftBrace = new MsoAutoShapeType(31);
  public final static MsoAutoShapeType msoShapeRightBrace = new MsoAutoShapeType(32);
  public final static MsoAutoShapeType msoShapeRightArrow = new MsoAutoShapeType(33);
  public final static MsoAutoShapeType msoShapeLeftArrow = new MsoAutoShapeType(34);
  public final static MsoAutoShapeType msoShapeUpArrow = new MsoAutoShapeType(35);
  public final static MsoAutoShapeType msoShapeDownArrow = new MsoAutoShapeType(36);
  public final static MsoAutoShapeType msoShapeLeftRightArrow = new MsoAutoShapeType(37);
  public final static MsoAutoShapeType msoShapeUpDownArrow = new MsoAutoShapeType(38);
  public final static MsoAutoShapeType msoShapeQuadArrow = new MsoAutoShapeType(39);
  public final static MsoAutoShapeType msoShapeLeftRightUpArrow = new MsoAutoShapeType(40);
  public final static MsoAutoShapeType msoShapeBentArrow = new MsoAutoShapeType(41);
  public final static MsoAutoShapeType msoShapeUTurnArrow = new MsoAutoShapeType(42);
  public final static MsoAutoShapeType msoShapeLeftUpArrow = new MsoAutoShapeType(43);
  public final static MsoAutoShapeType msoShapeBentUpArrow = new MsoAutoShapeType(44);
  public final static MsoAutoShapeType msoShapeCurvedRightArrow = new MsoAutoShapeType(45);
  public final static MsoAutoShapeType msoShapeCurvedLeftArrow = new MsoAutoShapeType(46);
  public final static MsoAutoShapeType msoShapeCurvedUpArrow = new MsoAutoShapeType(47);
  public final static MsoAutoShapeType msoShapeCurvedDownArrow = new MsoAutoShapeType(48);
  public final static MsoAutoShapeType msoShapeStripedRightArrow = new MsoAutoShapeType(49);
  public final static MsoAutoShapeType msoShapeNotchedRightArrow = new MsoAutoShapeType(50);
  public final static MsoAutoShapeType msoShapePentagon = new MsoAutoShapeType(51);
  public final static MsoAutoShapeType msoShapeChevron = new MsoAutoShapeType(52);
  public final static MsoAutoShapeType msoShapeRightArrowCallout = new MsoAutoShapeType(53);
  public final static MsoAutoShapeType msoShapeLeftArrowCallout = new MsoAutoShapeType(54);
  public final static MsoAutoShapeType msoShapeUpArrowCallout = new MsoAutoShapeType(55);
  public final static MsoAutoShapeType msoShapeDownArrowCallout = new MsoAutoShapeType(56);
  public final static MsoAutoShapeType msoShapeLeftRightArrowCallout = new MsoAutoShapeType(57);
  public final static MsoAutoShapeType msoShapeUpDownArrowCallout = new MsoAutoShapeType(58);
  public final static MsoAutoShapeType msoShapeQuadArrowCallout = new MsoAutoShapeType(59);
  public final static MsoAutoShapeType msoShapeCircularArrow = new MsoAutoShapeType(60);
  public final static MsoAutoShapeType msoShapeFlowchartProcess = new MsoAutoShapeType(61);
  public final static MsoAutoShapeType msoShapeFlowchartAlternateProcess = new MsoAutoShapeType(62);
  public final static MsoAutoShapeType msoShapeFlowchartDecision = new MsoAutoShapeType(63);
  public final static MsoAutoShapeType msoShapeFlowchartData = new MsoAutoShapeType(64);
  public final static MsoAutoShapeType msoShapeFlowchartPredefinedProcess = new MsoAutoShapeType(65);
  public final static MsoAutoShapeType msoShapeFlowchartInternalStorage = new MsoAutoShapeType(66);
  public final static MsoAutoShapeType msoShapeFlowchartDocument = new MsoAutoShapeType(67);
  public final static MsoAutoShapeType msoShapeFlowchartMultidocument = new MsoAutoShapeType(68);
  public final static MsoAutoShapeType msoShapeFlowchartTerminator = new MsoAutoShapeType(69);
  public final static MsoAutoShapeType msoShapeFlowchartPreparation = new MsoAutoShapeType(70);
  public final static MsoAutoShapeType msoShapeFlowchartManualInput = new MsoAutoShapeType(71);
  public final static MsoAutoShapeType msoShapeFlowchartManualOperation = new MsoAutoShapeType(72);
  public final static MsoAutoShapeType msoShapeFlowchartConnector = new MsoAutoShapeType(73);
  public final static MsoAutoShapeType msoShapeFlowchartOffpageConnector = new MsoAutoShapeType(74);
  public final static MsoAutoShapeType msoShapeFlowchartCard = new MsoAutoShapeType(75);
  public final static MsoAutoShapeType msoShapeFlowchartPunchedTape = new MsoAutoShapeType(76);
  public final static MsoAutoShapeType msoShapeFlowchartSummingJunction = new MsoAutoShapeType(77);
  public final static MsoAutoShapeType msoShapeFlowchartOr = new MsoAutoShapeType(78);
  public final static MsoAutoShapeType msoShapeFlowchartCollate = new MsoAutoShapeType(79);
  public final static MsoAutoShapeType msoShapeFlowchartSort = new MsoAutoShapeType(80);
  public final static MsoAutoShapeType msoShapeFlowchartExtract = new MsoAutoShapeType(81);
  public final static MsoAutoShapeType msoShapeFlowchartMerge = new MsoAutoShapeType(82);
  public final static MsoAutoShapeType msoShapeFlowchartStoredData = new MsoAutoShapeType(83);
  public final static MsoAutoShapeType msoShapeFlowchartDelay = new MsoAutoShapeType(84);
  public final static MsoAutoShapeType msoShapeFlowchartSequentialAccessStorage = new MsoAutoShapeType(85);
  public final static MsoAutoShapeType msoShapeFlowchartMagneticDisk = new MsoAutoShapeType(86);
  public final static MsoAutoShapeType msoShapeFlowchartDirectAccessStorage = new MsoAutoShapeType(87);
  public final static MsoAutoShapeType msoShapeFlowchartDisplay = new MsoAutoShapeType(88);
  public final static MsoAutoShapeType msoShapeExplosion1 = new MsoAutoShapeType(89);
  public final static MsoAutoShapeType msoShapeExplosion2 = new MsoAutoShapeType(90);
  public final static MsoAutoShapeType msoShape4pointStar = new MsoAutoShapeType(91);
  public final static MsoAutoShapeType msoShape5pointStar = new MsoAutoShapeType(92);
  public final static MsoAutoShapeType msoShape8pointStar = new MsoAutoShapeType(93);
  public final static MsoAutoShapeType msoShape16pointStar = new MsoAutoShapeType(94);
  public final static MsoAutoShapeType msoShape24pointStar = new MsoAutoShapeType(95);
  public final static MsoAutoShapeType msoShape32pointStar = new MsoAutoShapeType(96);
  public final static MsoAutoShapeType msoShapeUpRibbon = new MsoAutoShapeType(97);
  public final static MsoAutoShapeType msoShapeDownRibbon = new MsoAutoShapeType(98);
  public final static MsoAutoShapeType msoShapeCurvedUpRibbon = new MsoAutoShapeType(99);
  public final static MsoAutoShapeType msoShapeCurvedDownRibbon = new MsoAutoShapeType(100);
  public final static MsoAutoShapeType msoShapeVerticalScroll = new MsoAutoShapeType(101);
  public final static MsoAutoShapeType msoShapeHorizontalScroll = new MsoAutoShapeType(102);
  public final static MsoAutoShapeType msoShapeWave = new MsoAutoShapeType(103);
  public final static MsoAutoShapeType msoShapeDoubleWave = new MsoAutoShapeType(104);
  public final static MsoAutoShapeType msoShapeRectangularCallout = new MsoAutoShapeType(105);
  public final static MsoAutoShapeType msoShapeRoundedRectangularCallout = new MsoAutoShapeType(106);
  public final static MsoAutoShapeType msoShapeOvalCallout = new MsoAutoShapeType(107);
  public final static MsoAutoShapeType msoShapeCloudCallout = new MsoAutoShapeType(108);
  public final static MsoAutoShapeType msoShapeLineCallout1 = new MsoAutoShapeType(109);
  public final static MsoAutoShapeType msoShapeLineCallout2 = new MsoAutoShapeType(110);
  public final static MsoAutoShapeType msoShapeLineCallout3 = new MsoAutoShapeType(111);
  public final static MsoAutoShapeType msoShapeLineCallout4 = new MsoAutoShapeType(112);
  public final static MsoAutoShapeType msoShapeLineCallout1AccentBar = new MsoAutoShapeType(113);
  public final static MsoAutoShapeType msoShapeLineCallout2AccentBar = new MsoAutoShapeType(114);
  public final static MsoAutoShapeType msoShapeLineCallout3AccentBar = new MsoAutoShapeType(115);
  public final static MsoAutoShapeType msoShapeLineCallout4AccentBar = new MsoAutoShapeType(116);
  public final static MsoAutoShapeType msoShapeLineCallout1NoBorder = new MsoAutoShapeType(117);
  public final static MsoAutoShapeType msoShapeLineCallout2NoBorder = new MsoAutoShapeType(118);
  public final static MsoAutoShapeType msoShapeLineCallout3NoBorder = new MsoAutoShapeType(119);
  public final static MsoAutoShapeType msoShapeLineCallout4NoBorder = new MsoAutoShapeType(120);
  public final static MsoAutoShapeType msoShapeLineCallout1BorderandAccentBar = new MsoAutoShapeType(121);
  public final static MsoAutoShapeType msoShapeLineCallout2BorderandAccentBar = new MsoAutoShapeType(122);
  public final static MsoAutoShapeType msoShapeLineCallout3BorderandAccentBar = new MsoAutoShapeType(123);
  public final static MsoAutoShapeType msoShapeLineCallout4BorderandAccentBar = new MsoAutoShapeType(124);
  public final static MsoAutoShapeType msoShapeActionButtonCustom = new MsoAutoShapeType(125);
  public final static MsoAutoShapeType msoShapeActionButtonHome = new MsoAutoShapeType(126);
  public final static MsoAutoShapeType msoShapeActionButtonHelp = new MsoAutoShapeType(127);
  public final static MsoAutoShapeType msoShapeActionButtonInformation = new MsoAutoShapeType(128);
  public final static MsoAutoShapeType msoShapeActionButtonBackorPrevious = new MsoAutoShapeType(129);
  public final static MsoAutoShapeType msoShapeActionButtonForwardorNext = new MsoAutoShapeType(130);
  public final static MsoAutoShapeType msoShapeActionButtonBeginning = new MsoAutoShapeType(131);
  public final static MsoAutoShapeType msoShapeActionButtonEnd = new MsoAutoShapeType(132);
  public final static MsoAutoShapeType msoShapeActionButtonReturn = new MsoAutoShapeType(133);
  public final static MsoAutoShapeType msoShapeActionButtonDocument = new MsoAutoShapeType(134);
  public final static MsoAutoShapeType msoShapeActionButtonSound = new MsoAutoShapeType(135);
  public final static MsoAutoShapeType msoShapeActionButtonMovie = new MsoAutoShapeType(136);
  public final static MsoAutoShapeType msoShapeBalloon = new MsoAutoShapeType(137);
  public final static MsoAutoShapeType msoShapeNotPrimitive = new MsoAutoShapeType(138);
  public final static MsoAutoShapeType msoShapeFlowchartOfflineStorage = new MsoAutoShapeType(139);
  public final static MsoAutoShapeType msoShapeLeftRightRibbon = new MsoAutoShapeType(140);
  public final static MsoAutoShapeType msoShapeDiagonalStripe = new MsoAutoShapeType(141);
  public final static MsoAutoShapeType msoShapePie = new MsoAutoShapeType(142);
  public final static MsoAutoShapeType msoShapeNonIsoscelesTrapezoid = new MsoAutoShapeType(143);
  public final static MsoAutoShapeType msoShapeDecagon = new MsoAutoShapeType(144);
  public final static MsoAutoShapeType msoShapeHeptagon = new MsoAutoShapeType(145);
  public final static MsoAutoShapeType msoShapeDodecagon = new MsoAutoShapeType(146);
  public final static MsoAutoShapeType msoShape6pointStar = new MsoAutoShapeType(147);
  public final static MsoAutoShapeType msoShape7pointStar = new MsoAutoShapeType(148);
  public final static MsoAutoShapeType msoShape10pointStar = new MsoAutoShapeType(149);
  public final static MsoAutoShapeType msoShape12pointStar = new MsoAutoShapeType(150);
  public final static MsoAutoShapeType msoShapeRound1Rectangle = new MsoAutoShapeType(151);
  public final static MsoAutoShapeType msoShapeRound2SameRectangle = new MsoAutoShapeType(152);
  public final static MsoAutoShapeType msoShapeRound2DiagRectangle = new MsoAutoShapeType(153);
  public final static MsoAutoShapeType msoShapeSnipRoundRectangle = new MsoAutoShapeType(154);
  public final static MsoAutoShapeType msoShapeSnip1Rectangle = new MsoAutoShapeType(155);
  public final static MsoAutoShapeType msoShapeSnip2SameRectangle = new MsoAutoShapeType(156);
  public final static MsoAutoShapeType msoShapeSnip2DiagRectangle = new MsoAutoShapeType(157);
  public final static MsoAutoShapeType msoShapeFrame = new MsoAutoShapeType(158);
  public final static MsoAutoShapeType msoShapeHalfFrame = new MsoAutoShapeType(159);
  public final static MsoAutoShapeType msoShapeTear = new MsoAutoShapeType(160);
  public final static MsoAutoShapeType msoShapeChord = new MsoAutoShapeType(161);
  public final static MsoAutoShapeType msoShapeCorner = new MsoAutoShapeType(162);
  public final static MsoAutoShapeType msoShapeMathPlus = new MsoAutoShapeType(163);
  public final static MsoAutoShapeType msoShapeMathMinus = new MsoAutoShapeType(164);
  public final static MsoAutoShapeType msoShapeMathMultiply = new MsoAutoShapeType(165);
  public final static MsoAutoShapeType msoShapeMathDivide = new MsoAutoShapeType(166);
  public final static MsoAutoShapeType msoShapeMathEqual = new MsoAutoShapeType(167);
  public final static MsoAutoShapeType msoShapeMathNotEqual = new MsoAutoShapeType(168);
  public final static MsoAutoShapeType msoShapeCornerTabs = new MsoAutoShapeType(169);
  public final static MsoAutoShapeType msoShapeSquareTabs = new MsoAutoShapeType(170);
  public final static MsoAutoShapeType msoShapePlaqueTabs = new MsoAutoShapeType(171);
  public final static MsoAutoShapeType msoShapeGear6 = new MsoAutoShapeType(172);
  public final static MsoAutoShapeType msoShapeGear9 = new MsoAutoShapeType(173);
  public final static MsoAutoShapeType msoShapeFunnel = new MsoAutoShapeType(174);
  public final static MsoAutoShapeType msoShapePieWedge = new MsoAutoShapeType(175);
  public final static MsoAutoShapeType msoShapeLeftCircularArrow = new MsoAutoShapeType(176);
  public final static MsoAutoShapeType msoShapeLeftRightCircularArrow = new MsoAutoShapeType(177);
  public final static MsoAutoShapeType msoShapeSwooshArrow = new MsoAutoShapeType(178);
  public final static MsoAutoShapeType msoShapeCloud = new MsoAutoShapeType(179);
  public final static MsoAutoShapeType msoShapeChartX = new MsoAutoShapeType(180);
  public final static MsoAutoShapeType msoShapeChartStar = new MsoAutoShapeType(181);
  public final static MsoAutoShapeType msoShapeChartPlus = new MsoAutoShapeType(182);
  public final static MsoAutoShapeType msoShapeLineInverse = new MsoAutoShapeType(183);

  // Integer constants for bitsets and switch statements
  public final static int _msoShapeMixed = -2;
  public final static int _msoShapeRectangle = 1;
  public final static int _msoShapeParallelogram = 2;
  public final static int _msoShapeTrapezoid = 3;
  public final static int _msoShapeDiamond = 4;
  public final static int _msoShapeRoundedRectangle = 5;
  public final static int _msoShapeOctagon = 6;
  public final static int _msoShapeIsoscelesTriangle = 7;
  public final static int _msoShapeRightTriangle = 8;
  public final static int _msoShapeOval = 9;
  public final static int _msoShapeHexagon = 10;
  public final static int _msoShapeCross = 11;
  public final static int _msoShapeRegularPentagon = 12;
  public final static int _msoShapeCan = 13;
  public final static int _msoShapeCube = 14;
  public final static int _msoShapeBevel = 15;
  public final static int _msoShapeFoldedCorner = 16;
  public final static int _msoShapeSmileyFace = 17;
  public final static int _msoShapeDonut = 18;
  public final static int _msoShapeNoSymbol = 19;
  public final static int _msoShapeBlockArc = 20;
  public final static int _msoShapeHeart = 21;
  public final static int _msoShapeLightningBolt = 22;
  public final static int _msoShapeSun = 23;
  public final static int _msoShapeMoon = 24;
  public final static int _msoShapeArc = 25;
  public final static int _msoShapeDoubleBracket = 26;
  public final static int _msoShapeDoubleBrace = 27;
  public final static int _msoShapePlaque = 28;
  public final static int _msoShapeLeftBracket = 29;
  public final static int _msoShapeRightBracket = 30;
  public final static int _msoShapeLeftBrace = 31;
  public final static int _msoShapeRightBrace = 32;
  public final static int _msoShapeRightArrow = 33;
  public final static int _msoShapeLeftArrow = 34;
  public final static int _msoShapeUpArrow = 35;
  public final static int _msoShapeDownArrow = 36;
  public final static int _msoShapeLeftRightArrow = 37;
  public final static int _msoShapeUpDownArrow = 38;
  public final static int _msoShapeQuadArrow = 39;
  public final static int _msoShapeLeftRightUpArrow = 40;
  public final static int _msoShapeBentArrow = 41;
  public final static int _msoShapeUTurnArrow = 42;
  public final static int _msoShapeLeftUpArrow = 43;
  public final static int _msoShapeBentUpArrow = 44;
  public final static int _msoShapeCurvedRightArrow = 45;
  public final static int _msoShapeCurvedLeftArrow = 46;
  public final static int _msoShapeCurvedUpArrow = 47;
  public final static int _msoShapeCurvedDownArrow = 48;
  public final static int _msoShapeStripedRightArrow = 49;
  public final static int _msoShapeNotchedRightArrow = 50;
  public final static int _msoShapePentagon = 51;
  public final static int _msoShapeChevron = 52;
  public final static int _msoShapeRightArrowCallout = 53;
  public final static int _msoShapeLeftArrowCallout = 54;
  public final static int _msoShapeUpArrowCallout = 55;
  public final static int _msoShapeDownArrowCallout = 56;
  public final static int _msoShapeLeftRightArrowCallout = 57;
  public final static int _msoShapeUpDownArrowCallout = 58;
  public final static int _msoShapeQuadArrowCallout = 59;
  public final static int _msoShapeCircularArrow = 60;
  public final static int _msoShapeFlowchartProcess = 61;
  public final static int _msoShapeFlowchartAlternateProcess = 62;
  public final static int _msoShapeFlowchartDecision = 63;
  public final static int _msoShapeFlowchartData = 64;
  public final static int _msoShapeFlowchartPredefinedProcess = 65;
  public final static int _msoShapeFlowchartInternalStorage = 66;
  public final static int _msoShapeFlowchartDocument = 67;
  public final static int _msoShapeFlowchartMultidocument = 68;
  public final static int _msoShapeFlowchartTerminator = 69;
  public final static int _msoShapeFlowchartPreparation = 70;
  public final static int _msoShapeFlowchartManualInput = 71;
  public final static int _msoShapeFlowchartManualOperation = 72;
  public final static int _msoShapeFlowchartConnector = 73;
  public final static int _msoShapeFlowchartOffpageConnector = 74;
  public final static int _msoShapeFlowchartCard = 75;
  public final static int _msoShapeFlowchartPunchedTape = 76;
  public final static int _msoShapeFlowchartSummingJunction = 77;
  public final static int _msoShapeFlowchartOr = 78;
  public final static int _msoShapeFlowchartCollate = 79;
  public final static int _msoShapeFlowchartSort = 80;
  public final static int _msoShapeFlowchartExtract = 81;
  public final static int _msoShapeFlowchartMerge = 82;
  public final static int _msoShapeFlowchartStoredData = 83;
  public final static int _msoShapeFlowchartDelay = 84;
  public final static int _msoShapeFlowchartSequentialAccessStorage = 85;
  public final static int _msoShapeFlowchartMagneticDisk = 86;
  public final static int _msoShapeFlowchartDirectAccessStorage = 87;
  public final static int _msoShapeFlowchartDisplay = 88;
  public final static int _msoShapeExplosion1 = 89;
  public final static int _msoShapeExplosion2 = 90;
  public final static int _msoShape4pointStar = 91;
  public final static int _msoShape5pointStar = 92;
  public final static int _msoShape8pointStar = 93;
  public final static int _msoShape16pointStar = 94;
  public final static int _msoShape24pointStar = 95;
  public final static int _msoShape32pointStar = 96;
  public final static int _msoShapeUpRibbon = 97;
  public final static int _msoShapeDownRibbon = 98;
  public final static int _msoShapeCurvedUpRibbon = 99;
  public final static int _msoShapeCurvedDownRibbon = 100;
  public final static int _msoShapeVerticalScroll = 101;
  public final static int _msoShapeHorizontalScroll = 102;
  public final static int _msoShapeWave = 103;
  public final static int _msoShapeDoubleWave = 104;
  public final static int _msoShapeRectangularCallout = 105;
  public final static int _msoShapeRoundedRectangularCallout = 106;
  public final static int _msoShapeOvalCallout = 107;
  public final static int _msoShapeCloudCallout = 108;
  public final static int _msoShapeLineCallout1 = 109;
  public final static int _msoShapeLineCallout2 = 110;
  public final static int _msoShapeLineCallout3 = 111;
  public final static int _msoShapeLineCallout4 = 112;
  public final static int _msoShapeLineCallout1AccentBar = 113;
  public final static int _msoShapeLineCallout2AccentBar = 114;
  public final static int _msoShapeLineCallout3AccentBar = 115;
  public final static int _msoShapeLineCallout4AccentBar = 116;
  public final static int _msoShapeLineCallout1NoBorder = 117;
  public final static int _msoShapeLineCallout2NoBorder = 118;
  public final static int _msoShapeLineCallout3NoBorder = 119;
  public final static int _msoShapeLineCallout4NoBorder = 120;
  public final static int _msoShapeLineCallout1BorderandAccentBar = 121;
  public final static int _msoShapeLineCallout2BorderandAccentBar = 122;
  public final static int _msoShapeLineCallout3BorderandAccentBar = 123;
  public final static int _msoShapeLineCallout4BorderandAccentBar = 124;
  public final static int _msoShapeActionButtonCustom = 125;
  public final static int _msoShapeActionButtonHome = 126;
  public final static int _msoShapeActionButtonHelp = 127;
  public final static int _msoShapeActionButtonInformation = 128;
  public final static int _msoShapeActionButtonBackorPrevious = 129;
  public final static int _msoShapeActionButtonForwardorNext = 130;
  public final static int _msoShapeActionButtonBeginning = 131;
  public final static int _msoShapeActionButtonEnd = 132;
  public final static int _msoShapeActionButtonReturn = 133;
  public final static int _msoShapeActionButtonDocument = 134;
  public final static int _msoShapeActionButtonSound = 135;
  public final static int _msoShapeActionButtonMovie = 136;
  public final static int _msoShapeBalloon = 137;
  public final static int _msoShapeNotPrimitive = 138;
  public final static int _msoShapeFlowchartOfflineStorage = 139;
  public final static int _msoShapeLeftRightRibbon = 140;
  public final static int _msoShapeDiagonalStripe = 141;
  public final static int _msoShapePie = 142;
  public final static int _msoShapeNonIsoscelesTrapezoid = 143;
  public final static int _msoShapeDecagon = 144;
  public final static int _msoShapeHeptagon = 145;
  public final static int _msoShapeDodecagon = 146;
  public final static int _msoShape6pointStar = 147;
  public final static int _msoShape7pointStar = 148;
  public final static int _msoShape10pointStar = 149;
  public final static int _msoShape12pointStar = 150;
  public final static int _msoShapeRound1Rectangle = 151;
  public final static int _msoShapeRound2SameRectangle = 152;
  public final static int _msoShapeRound2DiagRectangle = 153;
  public final static int _msoShapeSnipRoundRectangle = 154;
  public final static int _msoShapeSnip1Rectangle = 155;
  public final static int _msoShapeSnip2SameRectangle = 156;
  public final static int _msoShapeSnip2DiagRectangle = 157;
  public final static int _msoShapeFrame = 158;
  public final static int _msoShapeHalfFrame = 159;
  public final static int _msoShapeTear = 160;
  public final static int _msoShapeChord = 161;
  public final static int _msoShapeCorner = 162;
  public final static int _msoShapeMathPlus = 163;
  public final static int _msoShapeMathMinus = 164;
  public final static int _msoShapeMathMultiply = 165;
  public final static int _msoShapeMathDivide = 166;
  public final static int _msoShapeMathEqual = 167;
  public final static int _msoShapeMathNotEqual = 168;
  public final static int _msoShapeCornerTabs = 169;
  public final static int _msoShapeSquareTabs = 170;
  public final static int _msoShapePlaqueTabs = 171;
  public final static int _msoShapeGear6 = 172;
  public final static int _msoShapeGear9 = 173;
  public final static int _msoShapeFunnel = 174;
  public final static int _msoShapePieWedge = 175;
  public final static int _msoShapeLeftCircularArrow = 176;
  public final static int _msoShapeLeftRightCircularArrow = 177;
  public final static int _msoShapeSwooshArrow = 178;
  public final static int _msoShapeCloud = 179;
  public final static int _msoShapeChartX = 180;
  public final static int _msoShapeChartStar = 181;
  public final static int _msoShapeChartPlus = 182;
  public final static int _msoShapeLineInverse = 183;

  // Value, readonly field.
  public final int value;

  // Private constructor, use valueOf to create an instance.
  private MsoAutoShapeType(int value) { this.value = value; }

  // Return one of the predefined typed constants for the given value or create a new object.
  public static  MsoAutoShapeType valueOf(int value) {
    switch(value) {
    case -2: return msoShapeMixed;
    case 1: return msoShapeRectangle;
    case 2: return msoShapeParallelogram;
    case 3: return msoShapeTrapezoid;
    case 4: return msoShapeDiamond;
    case 5: return msoShapeRoundedRectangle;
    case 6: return msoShapeOctagon;
    case 7: return msoShapeIsoscelesTriangle;
    case 8: return msoShapeRightTriangle;
    case 9: return msoShapeOval;
    case 10: return msoShapeHexagon;
    case 11: return msoShapeCross;
    case 12: return msoShapeRegularPentagon;
    case 13: return msoShapeCan;
    case 14: return msoShapeCube;
    case 15: return msoShapeBevel;
    case 16: return msoShapeFoldedCorner;
    case 17: return msoShapeSmileyFace;
    case 18: return msoShapeDonut;
    case 19: return msoShapeNoSymbol;
    case 20: return msoShapeBlockArc;
    case 21: return msoShapeHeart;
    case 22: return msoShapeLightningBolt;
    case 23: return msoShapeSun;
    case 24: return msoShapeMoon;
    case 25: return msoShapeArc;
    case 26: return msoShapeDoubleBracket;
    case 27: return msoShapeDoubleBrace;
    case 28: return msoShapePlaque;
    case 29: return msoShapeLeftBracket;
    case 30: return msoShapeRightBracket;
    case 31: return msoShapeLeftBrace;
    case 32: return msoShapeRightBrace;
    case 33: return msoShapeRightArrow;
    case 34: return msoShapeLeftArrow;
    case 35: return msoShapeUpArrow;
    case 36: return msoShapeDownArrow;
    case 37: return msoShapeLeftRightArrow;
    case 38: return msoShapeUpDownArrow;
    case 39: return msoShapeQuadArrow;
    case 40: return msoShapeLeftRightUpArrow;
    case 41: return msoShapeBentArrow;
    case 42: return msoShapeUTurnArrow;
    case 43: return msoShapeLeftUpArrow;
    case 44: return msoShapeBentUpArrow;
    case 45: return msoShapeCurvedRightArrow;
    case 46: return msoShapeCurvedLeftArrow;
    case 47: return msoShapeCurvedUpArrow;
    case 48: return msoShapeCurvedDownArrow;
    case 49: return msoShapeStripedRightArrow;
    case 50: return msoShapeNotchedRightArrow;
    case 51: return msoShapePentagon;
    case 52: return msoShapeChevron;
    case 53: return msoShapeRightArrowCallout;
    case 54: return msoShapeLeftArrowCallout;
    case 55: return msoShapeUpArrowCallout;
    case 56: return msoShapeDownArrowCallout;
    case 57: return msoShapeLeftRightArrowCallout;
    case 58: return msoShapeUpDownArrowCallout;
    case 59: return msoShapeQuadArrowCallout;
    case 60: return msoShapeCircularArrow;
    case 61: return msoShapeFlowchartProcess;
    case 62: return msoShapeFlowchartAlternateProcess;
    case 63: return msoShapeFlowchartDecision;
    case 64: return msoShapeFlowchartData;
    case 65: return msoShapeFlowchartPredefinedProcess;
    case 66: return msoShapeFlowchartInternalStorage;
    case 67: return msoShapeFlowchartDocument;
    case 68: return msoShapeFlowchartMultidocument;
    case 69: return msoShapeFlowchartTerminator;
    case 70: return msoShapeFlowchartPreparation;
    case 71: return msoShapeFlowchartManualInput;
    case 72: return msoShapeFlowchartManualOperation;
    case 73: return msoShapeFlowchartConnector;
    case 74: return msoShapeFlowchartOffpageConnector;
    case 75: return msoShapeFlowchartCard;
    case 76: return msoShapeFlowchartPunchedTape;
    case 77: return msoShapeFlowchartSummingJunction;
    case 78: return msoShapeFlowchartOr;
    case 79: return msoShapeFlowchartCollate;
    case 80: return msoShapeFlowchartSort;
    case 81: return msoShapeFlowchartExtract;
    case 82: return msoShapeFlowchartMerge;
    case 83: return msoShapeFlowchartStoredData;
    case 84: return msoShapeFlowchartDelay;
    case 85: return msoShapeFlowchartSequentialAccessStorage;
    case 86: return msoShapeFlowchartMagneticDisk;
    case 87: return msoShapeFlowchartDirectAccessStorage;
    case 88: return msoShapeFlowchartDisplay;
    case 89: return msoShapeExplosion1;
    case 90: return msoShapeExplosion2;
    case 91: return msoShape4pointStar;
    case 92: return msoShape5pointStar;
    case 93: return msoShape8pointStar;
    case 94: return msoShape16pointStar;
    case 95: return msoShape24pointStar;
    case 96: return msoShape32pointStar;
    case 97: return msoShapeUpRibbon;
    case 98: return msoShapeDownRibbon;
    case 99: return msoShapeCurvedUpRibbon;
    case 100: return msoShapeCurvedDownRibbon;
    case 101: return msoShapeVerticalScroll;
    case 102: return msoShapeHorizontalScroll;
    case 103: return msoShapeWave;
    case 104: return msoShapeDoubleWave;
    case 105: return msoShapeRectangularCallout;
    case 106: return msoShapeRoundedRectangularCallout;
    case 107: return msoShapeOvalCallout;
    case 108: return msoShapeCloudCallout;
    case 109: return msoShapeLineCallout1;
    case 110: return msoShapeLineCallout2;
    case 111: return msoShapeLineCallout3;
    case 112: return msoShapeLineCallout4;
    case 113: return msoShapeLineCallout1AccentBar;
    case 114: return msoShapeLineCallout2AccentBar;
    case 115: return msoShapeLineCallout3AccentBar;
    case 116: return msoShapeLineCallout4AccentBar;
    case 117: return msoShapeLineCallout1NoBorder;
    case 118: return msoShapeLineCallout2NoBorder;
    case 119: return msoShapeLineCallout3NoBorder;
    case 120: return msoShapeLineCallout4NoBorder;
    case 121: return msoShapeLineCallout1BorderandAccentBar;
    case 122: return msoShapeLineCallout2BorderandAccentBar;
    case 123: return msoShapeLineCallout3BorderandAccentBar;
    case 124: return msoShapeLineCallout4BorderandAccentBar;
    case 125: return msoShapeActionButtonCustom;
    case 126: return msoShapeActionButtonHome;
    case 127: return msoShapeActionButtonHelp;
    case 128: return msoShapeActionButtonInformation;
    case 129: return msoShapeActionButtonBackorPrevious;
    case 130: return msoShapeActionButtonForwardorNext;
    case 131: return msoShapeActionButtonBeginning;
    case 132: return msoShapeActionButtonEnd;
    case 133: return msoShapeActionButtonReturn;
    case 134: return msoShapeActionButtonDocument;
    case 135: return msoShapeActionButtonSound;
    case 136: return msoShapeActionButtonMovie;
    case 137: return msoShapeBalloon;
    case 138: return msoShapeNotPrimitive;
    case 139: return msoShapeFlowchartOfflineStorage;
    case 140: return msoShapeLeftRightRibbon;
    case 141: return msoShapeDiagonalStripe;
    case 142: return msoShapePie;
    case 143: return msoShapeNonIsoscelesTrapezoid;
    case 144: return msoShapeDecagon;
    case 145: return msoShapeHeptagon;
    case 146: return msoShapeDodecagon;
    case 147: return msoShape6pointStar;
    case 148: return msoShape7pointStar;
    case 149: return msoShape10pointStar;
    case 150: return msoShape12pointStar;
    case 151: return msoShapeRound1Rectangle;
    case 152: return msoShapeRound2SameRectangle;
    case 153: return msoShapeRound2DiagRectangle;
    case 154: return msoShapeSnipRoundRectangle;
    case 155: return msoShapeSnip1Rectangle;
    case 156: return msoShapeSnip2SameRectangle;
    case 157: return msoShapeSnip2DiagRectangle;
    case 158: return msoShapeFrame;
    case 159: return msoShapeHalfFrame;
    case 160: return msoShapeTear;
    case 161: return msoShapeChord;
    case 162: return msoShapeCorner;
    case 163: return msoShapeMathPlus;
    case 164: return msoShapeMathMinus;
    case 165: return msoShapeMathMultiply;
    case 166: return msoShapeMathDivide;
    case 167: return msoShapeMathEqual;
    case 168: return msoShapeMathNotEqual;
    case 169: return msoShapeCornerTabs;
    case 170: return msoShapeSquareTabs;
    case 171: return msoShapePlaqueTabs;
    case 172: return msoShapeGear6;
    case 173: return msoShapeGear9;
    case 174: return msoShapeFunnel;
    case 175: return msoShapePieWedge;
    case 176: return msoShapeLeftCircularArrow;
    case 177: return msoShapeLeftRightCircularArrow;
    case 178: return msoShapeSwooshArrow;
    case 179: return msoShapeCloud;
    case 180: return msoShapeChartX;
    case 181: return msoShapeChartStar;
    case 182: return msoShapeChartPlus;
    case 183: return msoShapeLineInverse;
    default: return new MsoAutoShapeType(value);
    }
  }
}
