/* ** GENEREATED FILE - DO NOT MODIFY ** */
package com.wilutions.mslib.office;
import com.wilutions.com.*;

/**
 * MsoChartElementType.
 * 
 */
@SuppressWarnings("all")
@CoInterface(guid="{00000000-0000-0000-0000-000000000000}")
public class MsoChartElementType {
  static boolean __typelib__loaded = __TypeLib.load();

  // Typed constants
  public final static MsoChartElementType msoElementChartTitleNone = new MsoChartElementType(0);
  public final static MsoChartElementType msoElementChartTitleCenteredOverlay = new MsoChartElementType(1);
  public final static MsoChartElementType msoElementChartTitleAboveChart = new MsoChartElementType(2);
  public final static MsoChartElementType msoElementLegendNone = new MsoChartElementType(100);
  public final static MsoChartElementType msoElementLegendRight = new MsoChartElementType(101);
  public final static MsoChartElementType msoElementLegendTop = new MsoChartElementType(102);
  public final static MsoChartElementType msoElementLegendLeft = new MsoChartElementType(103);
  public final static MsoChartElementType msoElementLegendBottom = new MsoChartElementType(104);
  public final static MsoChartElementType msoElementLegendRightOverlay = new MsoChartElementType(105);
  public final static MsoChartElementType msoElementLegendLeftOverlay = new MsoChartElementType(106);
  public final static MsoChartElementType msoElementDataLabelNone = new MsoChartElementType(200);
  public final static MsoChartElementType msoElementDataLabelShow = new MsoChartElementType(201);
  public final static MsoChartElementType msoElementDataLabelCenter = new MsoChartElementType(202);
  public final static MsoChartElementType msoElementDataLabelInsideEnd = new MsoChartElementType(203);
  public final static MsoChartElementType msoElementDataLabelInsideBase = new MsoChartElementType(204);
  public final static MsoChartElementType msoElementDataLabelOutSideEnd = new MsoChartElementType(205);
  public final static MsoChartElementType msoElementDataLabelLeft = new MsoChartElementType(206);
  public final static MsoChartElementType msoElementDataLabelRight = new MsoChartElementType(207);
  public final static MsoChartElementType msoElementDataLabelTop = new MsoChartElementType(208);
  public final static MsoChartElementType msoElementDataLabelBottom = new MsoChartElementType(209);
  public final static MsoChartElementType msoElementDataLabelBestFit = new MsoChartElementType(210);
  public final static MsoChartElementType msoElementDataLabelCallout = new MsoChartElementType(211);
  public final static MsoChartElementType msoElementPrimaryCategoryAxisTitleNone = new MsoChartElementType(300);
  public final static MsoChartElementType msoElementPrimaryCategoryAxisTitleAdjacentToAxis = new MsoChartElementType(301);
  public final static MsoChartElementType msoElementPrimaryCategoryAxisTitleBelowAxis = new MsoChartElementType(302);
  public final static MsoChartElementType msoElementPrimaryCategoryAxisTitleRotated = new MsoChartElementType(303);
  public final static MsoChartElementType msoElementPrimaryCategoryAxisTitleVertical = new MsoChartElementType(304);
  public final static MsoChartElementType msoElementPrimaryCategoryAxisTitleHorizontal = new MsoChartElementType(305);
  public final static MsoChartElementType msoElementPrimaryValueAxisTitleNone = new MsoChartElementType(306);
  public final static MsoChartElementType msoElementPrimaryValueAxisTitleAdjacentToAxis = new MsoChartElementType(306);
  public final static MsoChartElementType msoElementPrimaryValueAxisTitleBelowAxis = new MsoChartElementType(308);
  public final static MsoChartElementType msoElementPrimaryValueAxisTitleRotated = new MsoChartElementType(309);
  public final static MsoChartElementType msoElementPrimaryValueAxisTitleVertical = new MsoChartElementType(310);
  public final static MsoChartElementType msoElementPrimaryValueAxisTitleHorizontal = new MsoChartElementType(311);
  public final static MsoChartElementType msoElementSecondaryCategoryAxisTitleNone = new MsoChartElementType(312);
  public final static MsoChartElementType msoElementSecondaryCategoryAxisTitleAdjacentToAxis = new MsoChartElementType(313);
  public final static MsoChartElementType msoElementSecondaryCategoryAxisTitleBelowAxis = new MsoChartElementType(314);
  public final static MsoChartElementType msoElementSecondaryCategoryAxisTitleRotated = new MsoChartElementType(315);
  public final static MsoChartElementType msoElementSecondaryCategoryAxisTitleVertical = new MsoChartElementType(316);
  public final static MsoChartElementType msoElementSecondaryCategoryAxisTitleHorizontal = new MsoChartElementType(317);
  public final static MsoChartElementType msoElementSecondaryValueAxisTitleNone = new MsoChartElementType(318);
  public final static MsoChartElementType msoElementSecondaryValueAxisTitleAdjacentToAxis = new MsoChartElementType(319);
  public final static MsoChartElementType msoElementSecondaryValueAxisTitleBelowAxis = new MsoChartElementType(320);
  public final static MsoChartElementType msoElementSecondaryValueAxisTitleRotated = new MsoChartElementType(321);
  public final static MsoChartElementType msoElementSecondaryValueAxisTitleVertical = new MsoChartElementType(322);
  public final static MsoChartElementType msoElementSecondaryValueAxisTitleHorizontal = new MsoChartElementType(323);
  public final static MsoChartElementType msoElementSeriesAxisTitleNone = new MsoChartElementType(324);
  public final static MsoChartElementType msoElementSeriesAxisTitleRotated = new MsoChartElementType(325);
  public final static MsoChartElementType msoElementSeriesAxisTitleVertical = new MsoChartElementType(326);
  public final static MsoChartElementType msoElementSeriesAxisTitleHorizontal = new MsoChartElementType(327);
  public final static MsoChartElementType msoElementPrimaryValueGridLinesNone = new MsoChartElementType(328);
  public final static MsoChartElementType msoElementPrimaryValueGridLinesMinor = new MsoChartElementType(329);
  public final static MsoChartElementType msoElementPrimaryValueGridLinesMajor = new MsoChartElementType(330);
  public final static MsoChartElementType msoElementPrimaryValueGridLinesMinorMajor = new MsoChartElementType(331);
  public final static MsoChartElementType msoElementPrimaryCategoryGridLinesNone = new MsoChartElementType(332);
  public final static MsoChartElementType msoElementPrimaryCategoryGridLinesMinor = new MsoChartElementType(333);
  public final static MsoChartElementType msoElementPrimaryCategoryGridLinesMajor = new MsoChartElementType(334);
  public final static MsoChartElementType msoElementPrimaryCategoryGridLinesMinorMajor = new MsoChartElementType(335);
  public final static MsoChartElementType msoElementSecondaryValueGridLinesNone = new MsoChartElementType(336);
  public final static MsoChartElementType msoElementSecondaryValueGridLinesMinor = new MsoChartElementType(337);
  public final static MsoChartElementType msoElementSecondaryValueGridLinesMajor = new MsoChartElementType(338);
  public final static MsoChartElementType msoElementSecondaryValueGridLinesMinorMajor = new MsoChartElementType(339);
  public final static MsoChartElementType msoElementSecondaryCategoryGridLinesNone = new MsoChartElementType(340);
  public final static MsoChartElementType msoElementSecondaryCategoryGridLinesMinor = new MsoChartElementType(341);
  public final static MsoChartElementType msoElementSecondaryCategoryGridLinesMajor = new MsoChartElementType(342);
  public final static MsoChartElementType msoElementSecondaryCategoryGridLinesMinorMajor = new MsoChartElementType(343);
  public final static MsoChartElementType msoElementSeriesAxisGridLinesNone = new MsoChartElementType(344);
  public final static MsoChartElementType msoElementSeriesAxisGridLinesMinor = new MsoChartElementType(345);
  public final static MsoChartElementType msoElementSeriesAxisGridLinesMajor = new MsoChartElementType(346);
  public final static MsoChartElementType msoElementSeriesAxisGridLinesMinorMajor = new MsoChartElementType(347);
  public final static MsoChartElementType msoElementPrimaryCategoryAxisNone = new MsoChartElementType(348);
  public final static MsoChartElementType msoElementPrimaryCategoryAxisShow = new MsoChartElementType(349);
  public final static MsoChartElementType msoElementPrimaryCategoryAxisWithoutLabels = new MsoChartElementType(350);
  public final static MsoChartElementType msoElementPrimaryCategoryAxisReverse = new MsoChartElementType(351);
  public final static MsoChartElementType msoElementPrimaryValueAxisNone = new MsoChartElementType(352);
  public final static MsoChartElementType msoElementPrimaryValueAxisShow = new MsoChartElementType(353);
  public final static MsoChartElementType msoElementPrimaryValueAxisThousands = new MsoChartElementType(354);
  public final static MsoChartElementType msoElementPrimaryValueAxisMillions = new MsoChartElementType(355);
  public final static MsoChartElementType msoElementPrimaryValueAxisBillions = new MsoChartElementType(356);
  public final static MsoChartElementType msoElementPrimaryValueAxisLogScale = new MsoChartElementType(357);
  public final static MsoChartElementType msoElementSecondaryCategoryAxisNone = new MsoChartElementType(358);
  public final static MsoChartElementType msoElementSecondaryCategoryAxisShow = new MsoChartElementType(359);
  public final static MsoChartElementType msoElementSecondaryCategoryAxisWithoutLabels = new MsoChartElementType(360);
  public final static MsoChartElementType msoElementSecondaryCategoryAxisReverse = new MsoChartElementType(361);
  public final static MsoChartElementType msoElementSecondaryValueAxisNone = new MsoChartElementType(362);
  public final static MsoChartElementType msoElementSecondaryValueAxisShow = new MsoChartElementType(363);
  public final static MsoChartElementType msoElementSecondaryValueAxisThousands = new MsoChartElementType(364);
  public final static MsoChartElementType msoElementSecondaryValueAxisMillions = new MsoChartElementType(365);
  public final static MsoChartElementType msoElementSecondaryValueAxisBillions = new MsoChartElementType(366);
  public final static MsoChartElementType msoElementSecondaryValueAxisLogScale = new MsoChartElementType(367);
  public final static MsoChartElementType msoElementSeriesAxisNone = new MsoChartElementType(368);
  public final static MsoChartElementType msoElementSeriesAxisShow = new MsoChartElementType(369);
  public final static MsoChartElementType msoElementSeriesAxisWithoutLabeling = new MsoChartElementType(370);
  public final static MsoChartElementType msoElementSeriesAxisReverse = new MsoChartElementType(371);
  public final static MsoChartElementType msoElementPrimaryCategoryAxisThousands = new MsoChartElementType(372);
  public final static MsoChartElementType msoElementPrimaryCategoryAxisMillions = new MsoChartElementType(373);
  public final static MsoChartElementType msoElementPrimaryCategoryAxisBillions = new MsoChartElementType(374);
  public final static MsoChartElementType msoElementPrimaryCategoryAxisLogScale = new MsoChartElementType(375);
  public final static MsoChartElementType msoElementSecondaryCategoryAxisThousands = new MsoChartElementType(376);
  public final static MsoChartElementType msoElementSecondaryCategoryAxisMillions = new MsoChartElementType(377);
  public final static MsoChartElementType msoElementSecondaryCategoryAxisBillions = new MsoChartElementType(378);
  public final static MsoChartElementType msoElementSecondaryCategoryAxisLogScale = new MsoChartElementType(379);
  public final static MsoChartElementType msoElementDataTableNone = new MsoChartElementType(500);
  public final static MsoChartElementType msoElementDataTableShow = new MsoChartElementType(501);
  public final static MsoChartElementType msoElementDataTableWithLegendKeys = new MsoChartElementType(502);
  public final static MsoChartElementType msoElementTrendlineNone = new MsoChartElementType(600);
  public final static MsoChartElementType msoElementTrendlineAddLinear = new MsoChartElementType(601);
  public final static MsoChartElementType msoElementTrendlineAddExponential = new MsoChartElementType(602);
  public final static MsoChartElementType msoElementTrendlineAddLinearForecast = new MsoChartElementType(603);
  public final static MsoChartElementType msoElementTrendlineAddTwoPeriodMovingAverage = new MsoChartElementType(604);
  public final static MsoChartElementType msoElementErrorBarNone = new MsoChartElementType(700);
  public final static MsoChartElementType msoElementErrorBarStandardError = new MsoChartElementType(701);
  public final static MsoChartElementType msoElementErrorBarPercentage = new MsoChartElementType(702);
  public final static MsoChartElementType msoElementErrorBarStandardDeviation = new MsoChartElementType(703);
  public final static MsoChartElementType msoElementLineNone = new MsoChartElementType(800);
  public final static MsoChartElementType msoElementLineDropLine = new MsoChartElementType(801);
  public final static MsoChartElementType msoElementLineHiLoLine = new MsoChartElementType(802);
  public final static MsoChartElementType msoElementLineSeriesLine = new MsoChartElementType(803);
  public final static MsoChartElementType msoElementLineDropHiLoLine = new MsoChartElementType(804);
  public final static MsoChartElementType msoElementUpDownBarsNone = new MsoChartElementType(900);
  public final static MsoChartElementType msoElementUpDownBarsShow = new MsoChartElementType(901);
  public final static MsoChartElementType msoElementPlotAreaNone = new MsoChartElementType(1000);
  public final static MsoChartElementType msoElementPlotAreaShow = new MsoChartElementType(1001);
  public final static MsoChartElementType msoElementChartWallNone = new MsoChartElementType(1100);
  public final static MsoChartElementType msoElementChartWallShow = new MsoChartElementType(1101);
  public final static MsoChartElementType msoElementChartFloorNone = new MsoChartElementType(1200);
  public final static MsoChartElementType msoElementChartFloorShow = new MsoChartElementType(1201);

  // Integer constants for bitsets and switch statements
  public final static int _msoElementChartTitleNone = 0;
  public final static int _msoElementChartTitleCenteredOverlay = 1;
  public final static int _msoElementChartTitleAboveChart = 2;
  public final static int _msoElementLegendNone = 100;
  public final static int _msoElementLegendRight = 101;
  public final static int _msoElementLegendTop = 102;
  public final static int _msoElementLegendLeft = 103;
  public final static int _msoElementLegendBottom = 104;
  public final static int _msoElementLegendRightOverlay = 105;
  public final static int _msoElementLegendLeftOverlay = 106;
  public final static int _msoElementDataLabelNone = 200;
  public final static int _msoElementDataLabelShow = 201;
  public final static int _msoElementDataLabelCenter = 202;
  public final static int _msoElementDataLabelInsideEnd = 203;
  public final static int _msoElementDataLabelInsideBase = 204;
  public final static int _msoElementDataLabelOutSideEnd = 205;
  public final static int _msoElementDataLabelLeft = 206;
  public final static int _msoElementDataLabelRight = 207;
  public final static int _msoElementDataLabelTop = 208;
  public final static int _msoElementDataLabelBottom = 209;
  public final static int _msoElementDataLabelBestFit = 210;
  public final static int _msoElementDataLabelCallout = 211;
  public final static int _msoElementPrimaryCategoryAxisTitleNone = 300;
  public final static int _msoElementPrimaryCategoryAxisTitleAdjacentToAxis = 301;
  public final static int _msoElementPrimaryCategoryAxisTitleBelowAxis = 302;
  public final static int _msoElementPrimaryCategoryAxisTitleRotated = 303;
  public final static int _msoElementPrimaryCategoryAxisTitleVertical = 304;
  public final static int _msoElementPrimaryCategoryAxisTitleHorizontal = 305;
  public final static int _msoElementPrimaryValueAxisTitleNone = 306;
  public final static int _msoElementPrimaryValueAxisTitleAdjacentToAxis = 306;
  public final static int _msoElementPrimaryValueAxisTitleBelowAxis = 308;
  public final static int _msoElementPrimaryValueAxisTitleRotated = 309;
  public final static int _msoElementPrimaryValueAxisTitleVertical = 310;
  public final static int _msoElementPrimaryValueAxisTitleHorizontal = 311;
  public final static int _msoElementSecondaryCategoryAxisTitleNone = 312;
  public final static int _msoElementSecondaryCategoryAxisTitleAdjacentToAxis = 313;
  public final static int _msoElementSecondaryCategoryAxisTitleBelowAxis = 314;
  public final static int _msoElementSecondaryCategoryAxisTitleRotated = 315;
  public final static int _msoElementSecondaryCategoryAxisTitleVertical = 316;
  public final static int _msoElementSecondaryCategoryAxisTitleHorizontal = 317;
  public final static int _msoElementSecondaryValueAxisTitleNone = 318;
  public final static int _msoElementSecondaryValueAxisTitleAdjacentToAxis = 319;
  public final static int _msoElementSecondaryValueAxisTitleBelowAxis = 320;
  public final static int _msoElementSecondaryValueAxisTitleRotated = 321;
  public final static int _msoElementSecondaryValueAxisTitleVertical = 322;
  public final static int _msoElementSecondaryValueAxisTitleHorizontal = 323;
  public final static int _msoElementSeriesAxisTitleNone = 324;
  public final static int _msoElementSeriesAxisTitleRotated = 325;
  public final static int _msoElementSeriesAxisTitleVertical = 326;
  public final static int _msoElementSeriesAxisTitleHorizontal = 327;
  public final static int _msoElementPrimaryValueGridLinesNone = 328;
  public final static int _msoElementPrimaryValueGridLinesMinor = 329;
  public final static int _msoElementPrimaryValueGridLinesMajor = 330;
  public final static int _msoElementPrimaryValueGridLinesMinorMajor = 331;
  public final static int _msoElementPrimaryCategoryGridLinesNone = 332;
  public final static int _msoElementPrimaryCategoryGridLinesMinor = 333;
  public final static int _msoElementPrimaryCategoryGridLinesMajor = 334;
  public final static int _msoElementPrimaryCategoryGridLinesMinorMajor = 335;
  public final static int _msoElementSecondaryValueGridLinesNone = 336;
  public final static int _msoElementSecondaryValueGridLinesMinor = 337;
  public final static int _msoElementSecondaryValueGridLinesMajor = 338;
  public final static int _msoElementSecondaryValueGridLinesMinorMajor = 339;
  public final static int _msoElementSecondaryCategoryGridLinesNone = 340;
  public final static int _msoElementSecondaryCategoryGridLinesMinor = 341;
  public final static int _msoElementSecondaryCategoryGridLinesMajor = 342;
  public final static int _msoElementSecondaryCategoryGridLinesMinorMajor = 343;
  public final static int _msoElementSeriesAxisGridLinesNone = 344;
  public final static int _msoElementSeriesAxisGridLinesMinor = 345;
  public final static int _msoElementSeriesAxisGridLinesMajor = 346;
  public final static int _msoElementSeriesAxisGridLinesMinorMajor = 347;
  public final static int _msoElementPrimaryCategoryAxisNone = 348;
  public final static int _msoElementPrimaryCategoryAxisShow = 349;
  public final static int _msoElementPrimaryCategoryAxisWithoutLabels = 350;
  public final static int _msoElementPrimaryCategoryAxisReverse = 351;
  public final static int _msoElementPrimaryValueAxisNone = 352;
  public final static int _msoElementPrimaryValueAxisShow = 353;
  public final static int _msoElementPrimaryValueAxisThousands = 354;
  public final static int _msoElementPrimaryValueAxisMillions = 355;
  public final static int _msoElementPrimaryValueAxisBillions = 356;
  public final static int _msoElementPrimaryValueAxisLogScale = 357;
  public final static int _msoElementSecondaryCategoryAxisNone = 358;
  public final static int _msoElementSecondaryCategoryAxisShow = 359;
  public final static int _msoElementSecondaryCategoryAxisWithoutLabels = 360;
  public final static int _msoElementSecondaryCategoryAxisReverse = 361;
  public final static int _msoElementSecondaryValueAxisNone = 362;
  public final static int _msoElementSecondaryValueAxisShow = 363;
  public final static int _msoElementSecondaryValueAxisThousands = 364;
  public final static int _msoElementSecondaryValueAxisMillions = 365;
  public final static int _msoElementSecondaryValueAxisBillions = 366;
  public final static int _msoElementSecondaryValueAxisLogScale = 367;
  public final static int _msoElementSeriesAxisNone = 368;
  public final static int _msoElementSeriesAxisShow = 369;
  public final static int _msoElementSeriesAxisWithoutLabeling = 370;
  public final static int _msoElementSeriesAxisReverse = 371;
  public final static int _msoElementPrimaryCategoryAxisThousands = 372;
  public final static int _msoElementPrimaryCategoryAxisMillions = 373;
  public final static int _msoElementPrimaryCategoryAxisBillions = 374;
  public final static int _msoElementPrimaryCategoryAxisLogScale = 375;
  public final static int _msoElementSecondaryCategoryAxisThousands = 376;
  public final static int _msoElementSecondaryCategoryAxisMillions = 377;
  public final static int _msoElementSecondaryCategoryAxisBillions = 378;
  public final static int _msoElementSecondaryCategoryAxisLogScale = 379;
  public final static int _msoElementDataTableNone = 500;
  public final static int _msoElementDataTableShow = 501;
  public final static int _msoElementDataTableWithLegendKeys = 502;
  public final static int _msoElementTrendlineNone = 600;
  public final static int _msoElementTrendlineAddLinear = 601;
  public final static int _msoElementTrendlineAddExponential = 602;
  public final static int _msoElementTrendlineAddLinearForecast = 603;
  public final static int _msoElementTrendlineAddTwoPeriodMovingAverage = 604;
  public final static int _msoElementErrorBarNone = 700;
  public final static int _msoElementErrorBarStandardError = 701;
  public final static int _msoElementErrorBarPercentage = 702;
  public final static int _msoElementErrorBarStandardDeviation = 703;
  public final static int _msoElementLineNone = 800;
  public final static int _msoElementLineDropLine = 801;
  public final static int _msoElementLineHiLoLine = 802;
  public final static int _msoElementLineSeriesLine = 803;
  public final static int _msoElementLineDropHiLoLine = 804;
  public final static int _msoElementUpDownBarsNone = 900;
  public final static int _msoElementUpDownBarsShow = 901;
  public final static int _msoElementPlotAreaNone = 1000;
  public final static int _msoElementPlotAreaShow = 1001;
  public final static int _msoElementChartWallNone = 1100;
  public final static int _msoElementChartWallShow = 1101;
  public final static int _msoElementChartFloorNone = 1200;
  public final static int _msoElementChartFloorShow = 1201;

  // Value, readonly field.
  public final int value;

  // Private constructor, use valueOf to create an instance.
  private MsoChartElementType(int value) { this.value = value; }

  // Return one of the predefined typed constants for the given value or create a new object.
  public static  MsoChartElementType valueOf(int value) {
    switch(value) {
    case 0: return msoElementChartTitleNone;
    case 1: return msoElementChartTitleCenteredOverlay;
    case 2: return msoElementChartTitleAboveChart;
    case 100: return msoElementLegendNone;
    case 101: return msoElementLegendRight;
    case 102: return msoElementLegendTop;
    case 103: return msoElementLegendLeft;
    case 104: return msoElementLegendBottom;
    case 105: return msoElementLegendRightOverlay;
    case 106: return msoElementLegendLeftOverlay;
    case 200: return msoElementDataLabelNone;
    case 201: return msoElementDataLabelShow;
    case 202: return msoElementDataLabelCenter;
    case 203: return msoElementDataLabelInsideEnd;
    case 204: return msoElementDataLabelInsideBase;
    case 205: return msoElementDataLabelOutSideEnd;
    case 206: return msoElementDataLabelLeft;
    case 207: return msoElementDataLabelRight;
    case 208: return msoElementDataLabelTop;
    case 209: return msoElementDataLabelBottom;
    case 210: return msoElementDataLabelBestFit;
    case 211: return msoElementDataLabelCallout;
    case 300: return msoElementPrimaryCategoryAxisTitleNone;
    case 301: return msoElementPrimaryCategoryAxisTitleAdjacentToAxis;
    case 302: return msoElementPrimaryCategoryAxisTitleBelowAxis;
    case 303: return msoElementPrimaryCategoryAxisTitleRotated;
    case 304: return msoElementPrimaryCategoryAxisTitleVertical;
    case 305: return msoElementPrimaryCategoryAxisTitleHorizontal;
    case 306: return msoElementPrimaryValueAxisTitleNone;
    //se 306: return msoElementPrimaryValueAxisTitleAdjacentToAxis; // same as msoElementPrimaryValueAxisTitleNone
    case 308: return msoElementPrimaryValueAxisTitleBelowAxis;
    case 309: return msoElementPrimaryValueAxisTitleRotated;
    case 310: return msoElementPrimaryValueAxisTitleVertical;
    case 311: return msoElementPrimaryValueAxisTitleHorizontal;
    case 312: return msoElementSecondaryCategoryAxisTitleNone;
    case 313: return msoElementSecondaryCategoryAxisTitleAdjacentToAxis;
    case 314: return msoElementSecondaryCategoryAxisTitleBelowAxis;
    case 315: return msoElementSecondaryCategoryAxisTitleRotated;
    case 316: return msoElementSecondaryCategoryAxisTitleVertical;
    case 317: return msoElementSecondaryCategoryAxisTitleHorizontal;
    case 318: return msoElementSecondaryValueAxisTitleNone;
    case 319: return msoElementSecondaryValueAxisTitleAdjacentToAxis;
    case 320: return msoElementSecondaryValueAxisTitleBelowAxis;
    case 321: return msoElementSecondaryValueAxisTitleRotated;
    case 322: return msoElementSecondaryValueAxisTitleVertical;
    case 323: return msoElementSecondaryValueAxisTitleHorizontal;
    case 324: return msoElementSeriesAxisTitleNone;
    case 325: return msoElementSeriesAxisTitleRotated;
    case 326: return msoElementSeriesAxisTitleVertical;
    case 327: return msoElementSeriesAxisTitleHorizontal;
    case 328: return msoElementPrimaryValueGridLinesNone;
    case 329: return msoElementPrimaryValueGridLinesMinor;
    case 330: return msoElementPrimaryValueGridLinesMajor;
    case 331: return msoElementPrimaryValueGridLinesMinorMajor;
    case 332: return msoElementPrimaryCategoryGridLinesNone;
    case 333: return msoElementPrimaryCategoryGridLinesMinor;
    case 334: return msoElementPrimaryCategoryGridLinesMajor;
    case 335: return msoElementPrimaryCategoryGridLinesMinorMajor;
    case 336: return msoElementSecondaryValueGridLinesNone;
    case 337: return msoElementSecondaryValueGridLinesMinor;
    case 338: return msoElementSecondaryValueGridLinesMajor;
    case 339: return msoElementSecondaryValueGridLinesMinorMajor;
    case 340: return msoElementSecondaryCategoryGridLinesNone;
    case 341: return msoElementSecondaryCategoryGridLinesMinor;
    case 342: return msoElementSecondaryCategoryGridLinesMajor;
    case 343: return msoElementSecondaryCategoryGridLinesMinorMajor;
    case 344: return msoElementSeriesAxisGridLinesNone;
    case 345: return msoElementSeriesAxisGridLinesMinor;
    case 346: return msoElementSeriesAxisGridLinesMajor;
    case 347: return msoElementSeriesAxisGridLinesMinorMajor;
    case 348: return msoElementPrimaryCategoryAxisNone;
    case 349: return msoElementPrimaryCategoryAxisShow;
    case 350: return msoElementPrimaryCategoryAxisWithoutLabels;
    case 351: return msoElementPrimaryCategoryAxisReverse;
    case 352: return msoElementPrimaryValueAxisNone;
    case 353: return msoElementPrimaryValueAxisShow;
    case 354: return msoElementPrimaryValueAxisThousands;
    case 355: return msoElementPrimaryValueAxisMillions;
    case 356: return msoElementPrimaryValueAxisBillions;
    case 357: return msoElementPrimaryValueAxisLogScale;
    case 358: return msoElementSecondaryCategoryAxisNone;
    case 359: return msoElementSecondaryCategoryAxisShow;
    case 360: return msoElementSecondaryCategoryAxisWithoutLabels;
    case 361: return msoElementSecondaryCategoryAxisReverse;
    case 362: return msoElementSecondaryValueAxisNone;
    case 363: return msoElementSecondaryValueAxisShow;
    case 364: return msoElementSecondaryValueAxisThousands;
    case 365: return msoElementSecondaryValueAxisMillions;
    case 366: return msoElementSecondaryValueAxisBillions;
    case 367: return msoElementSecondaryValueAxisLogScale;
    case 368: return msoElementSeriesAxisNone;
    case 369: return msoElementSeriesAxisShow;
    case 370: return msoElementSeriesAxisWithoutLabeling;
    case 371: return msoElementSeriesAxisReverse;
    case 372: return msoElementPrimaryCategoryAxisThousands;
    case 373: return msoElementPrimaryCategoryAxisMillions;
    case 374: return msoElementPrimaryCategoryAxisBillions;
    case 375: return msoElementPrimaryCategoryAxisLogScale;
    case 376: return msoElementSecondaryCategoryAxisThousands;
    case 377: return msoElementSecondaryCategoryAxisMillions;
    case 378: return msoElementSecondaryCategoryAxisBillions;
    case 379: return msoElementSecondaryCategoryAxisLogScale;
    case 500: return msoElementDataTableNone;
    case 501: return msoElementDataTableShow;
    case 502: return msoElementDataTableWithLegendKeys;
    case 600: return msoElementTrendlineNone;
    case 601: return msoElementTrendlineAddLinear;
    case 602: return msoElementTrendlineAddExponential;
    case 603: return msoElementTrendlineAddLinearForecast;
    case 604: return msoElementTrendlineAddTwoPeriodMovingAverage;
    case 700: return msoElementErrorBarNone;
    case 701: return msoElementErrorBarStandardError;
    case 702: return msoElementErrorBarPercentage;
    case 703: return msoElementErrorBarStandardDeviation;
    case 800: return msoElementLineNone;
    case 801: return msoElementLineDropLine;
    case 802: return msoElementLineHiLoLine;
    case 803: return msoElementLineSeriesLine;
    case 804: return msoElementLineDropHiLoLine;
    case 900: return msoElementUpDownBarsNone;
    case 901: return msoElementUpDownBarsShow;
    case 1000: return msoElementPlotAreaNone;
    case 1001: return msoElementPlotAreaShow;
    case 1100: return msoElementChartWallNone;
    case 1101: return msoElementChartWallShow;
    case 1200: return msoElementChartFloorNone;
    case 1201: return msoElementChartFloorShow;
    default: return new MsoChartElementType(value);
    }
  }
}
