/* ** GENEREATED FILE - DO NOT MODIFY ** */
package com.wilutions.mslib.office;
import com.wilutions.com.*;

/**
 * MsoLanguageID.
 * 
 */
@SuppressWarnings("all")
@CoInterface(guid="{00000000-0000-0000-0000-000000000000}")
public class MsoLanguageID implements ComEnum {
  static boolean __typelib__loaded = __TypeLib.load();

  // Typed constants
  public final static MsoLanguageID msoLanguageIDMixed = new MsoLanguageID(-2);
  public final static MsoLanguageID msoLanguageIDNone = new MsoLanguageID(0);
  public final static MsoLanguageID msoLanguageIDNoProofing = new MsoLanguageID(1024);
  public final static MsoLanguageID msoLanguageIDAfrikaans = new MsoLanguageID(1078);
  public final static MsoLanguageID msoLanguageIDAlbanian = new MsoLanguageID(1052);
  public final static MsoLanguageID msoLanguageIDAmharic = new MsoLanguageID(1118);
  public final static MsoLanguageID msoLanguageIDArabicAlgeria = new MsoLanguageID(5121);
  public final static MsoLanguageID msoLanguageIDArabicBahrain = new MsoLanguageID(15361);
  public final static MsoLanguageID msoLanguageIDArabicEgypt = new MsoLanguageID(3073);
  public final static MsoLanguageID msoLanguageIDArabicIraq = new MsoLanguageID(2049);
  public final static MsoLanguageID msoLanguageIDArabicJordan = new MsoLanguageID(11265);
  public final static MsoLanguageID msoLanguageIDArabicKuwait = new MsoLanguageID(13313);
  public final static MsoLanguageID msoLanguageIDArabicLebanon = new MsoLanguageID(12289);
  public final static MsoLanguageID msoLanguageIDArabicLibya = new MsoLanguageID(4097);
  public final static MsoLanguageID msoLanguageIDArabicMorocco = new MsoLanguageID(6145);
  public final static MsoLanguageID msoLanguageIDArabicOman = new MsoLanguageID(8193);
  public final static MsoLanguageID msoLanguageIDArabicQatar = new MsoLanguageID(16385);
  public final static MsoLanguageID msoLanguageIDArabic = new MsoLanguageID(1025);
  public final static MsoLanguageID msoLanguageIDArabicSyria = new MsoLanguageID(10241);
  public final static MsoLanguageID msoLanguageIDArabicTunisia = new MsoLanguageID(7169);
  public final static MsoLanguageID msoLanguageIDArabicUAE = new MsoLanguageID(14337);
  public final static MsoLanguageID msoLanguageIDArabicYemen = new MsoLanguageID(9217);
  public final static MsoLanguageID msoLanguageIDArmenian = new MsoLanguageID(1067);
  public final static MsoLanguageID msoLanguageIDAssamese = new MsoLanguageID(1101);
  public final static MsoLanguageID msoLanguageIDAzeriCyrillic = new MsoLanguageID(2092);
  public final static MsoLanguageID msoLanguageIDAzeriLatin = new MsoLanguageID(1068);
  public final static MsoLanguageID msoLanguageIDBasque = new MsoLanguageID(1069);
  public final static MsoLanguageID msoLanguageIDByelorussian = new MsoLanguageID(1059);
  public final static MsoLanguageID msoLanguageIDBengali = new MsoLanguageID(1093);
  public final static MsoLanguageID msoLanguageIDBosnian = new MsoLanguageID(4122);
  public final static MsoLanguageID msoLanguageIDBosnianBosniaHerzegovinaCyrillic = new MsoLanguageID(8218);
  public final static MsoLanguageID msoLanguageIDBosnianBosniaHerzegovinaLatin = new MsoLanguageID(5146);
  public final static MsoLanguageID msoLanguageIDBulgarian = new MsoLanguageID(1026);
  public final static MsoLanguageID msoLanguageIDBurmese = new MsoLanguageID(1109);
  public final static MsoLanguageID msoLanguageIDCatalan = new MsoLanguageID(1027);
  public final static MsoLanguageID msoLanguageIDChineseHongKongSAR = new MsoLanguageID(3076);
  public final static MsoLanguageID msoLanguageIDChineseMacaoSAR = new MsoLanguageID(5124);
  public final static MsoLanguageID msoLanguageIDSimplifiedChinese = new MsoLanguageID(2052);
  public final static MsoLanguageID msoLanguageIDChineseSingapore = new MsoLanguageID(4100);
  public final static MsoLanguageID msoLanguageIDTraditionalChinese = new MsoLanguageID(1028);
  public final static MsoLanguageID msoLanguageIDCherokee = new MsoLanguageID(1116);
  public final static MsoLanguageID msoLanguageIDCroatian = new MsoLanguageID(1050);
  public final static MsoLanguageID msoLanguageIDCzech = new MsoLanguageID(1029);
  public final static MsoLanguageID msoLanguageIDDanish = new MsoLanguageID(1030);
  public final static MsoLanguageID msoLanguageIDDivehi = new MsoLanguageID(1125);
  public final static MsoLanguageID msoLanguageIDBelgianDutch = new MsoLanguageID(2067);
  public final static MsoLanguageID msoLanguageIDDutch = new MsoLanguageID(1043);
  public final static MsoLanguageID msoLanguageIDDzongkhaBhutan = new MsoLanguageID(2129);
  public final static MsoLanguageID msoLanguageIDEdo = new MsoLanguageID(1126);
  public final static MsoLanguageID msoLanguageIDEnglishAUS = new MsoLanguageID(3081);
  public final static MsoLanguageID msoLanguageIDEnglishBelize = new MsoLanguageID(10249);
  public final static MsoLanguageID msoLanguageIDEnglishCanadian = new MsoLanguageID(4105);
  public final static MsoLanguageID msoLanguageIDEnglishCaribbean = new MsoLanguageID(9225);
  public final static MsoLanguageID msoLanguageIDEnglishIndonesia = new MsoLanguageID(14345);
  public final static MsoLanguageID msoLanguageIDEnglishIreland = new MsoLanguageID(6153);
  public final static MsoLanguageID msoLanguageIDEnglishJamaica = new MsoLanguageID(8201);
  public final static MsoLanguageID msoLanguageIDEnglishNewZealand = new MsoLanguageID(5129);
  public final static MsoLanguageID msoLanguageIDEnglishPhilippines = new MsoLanguageID(13321);
  public final static MsoLanguageID msoLanguageIDEnglishSouthAfrica = new MsoLanguageID(7177);
  public final static MsoLanguageID msoLanguageIDEnglishTrinidadTobago = new MsoLanguageID(11273);
  public final static MsoLanguageID msoLanguageIDEnglishUK = new MsoLanguageID(2057);
  public final static MsoLanguageID msoLanguageIDEnglishUS = new MsoLanguageID(1033);
  public final static MsoLanguageID msoLanguageIDEnglishZimbabwe = new MsoLanguageID(12297);
  public final static MsoLanguageID msoLanguageIDEstonian = new MsoLanguageID(1061);
  public final static MsoLanguageID msoLanguageIDFaeroese = new MsoLanguageID(1080);
  public final static MsoLanguageID msoLanguageIDFarsi = new MsoLanguageID(1065);
  public final static MsoLanguageID msoLanguageIDFilipino = new MsoLanguageID(1124);
  public final static MsoLanguageID msoLanguageIDFinnish = new MsoLanguageID(1035);
  public final static MsoLanguageID msoLanguageIDBelgianFrench = new MsoLanguageID(2060);
  public final static MsoLanguageID msoLanguageIDFrenchCameroon = new MsoLanguageID(11276);
  public final static MsoLanguageID msoLanguageIDFrenchCanadian = new MsoLanguageID(3084);
  public final static MsoLanguageID msoLanguageIDFrenchCotedIvoire = new MsoLanguageID(12300);
  public final static MsoLanguageID msoLanguageIDFrench = new MsoLanguageID(1036);
  public final static MsoLanguageID msoLanguageIDFrenchHaiti = new MsoLanguageID(15372);
  public final static MsoLanguageID msoLanguageIDFrenchLuxembourg = new MsoLanguageID(5132);
  public final static MsoLanguageID msoLanguageIDFrenchMali = new MsoLanguageID(13324);
  public final static MsoLanguageID msoLanguageIDFrenchMonaco = new MsoLanguageID(6156);
  public final static MsoLanguageID msoLanguageIDFrenchMorocco = new MsoLanguageID(14348);
  public final static MsoLanguageID msoLanguageIDFrenchReunion = new MsoLanguageID(8204);
  public final static MsoLanguageID msoLanguageIDFrenchSenegal = new MsoLanguageID(10252);
  public final static MsoLanguageID msoLanguageIDSwissFrench = new MsoLanguageID(4108);
  public final static MsoLanguageID msoLanguageIDFrenchWestIndies = new MsoLanguageID(7180);
  public final static MsoLanguageID msoLanguageIDFrenchZaire = new MsoLanguageID(9228);
  public final static MsoLanguageID msoLanguageIDFrenchCongoDRC = new MsoLanguageID(9228);
  public final static MsoLanguageID msoLanguageIDFrisianNetherlands = new MsoLanguageID(1122);
  public final static MsoLanguageID msoLanguageIDFulfulde = new MsoLanguageID(1127);
  public final static MsoLanguageID msoLanguageIDGaelicIreland = new MsoLanguageID(2108);
  public final static MsoLanguageID msoLanguageIDGaelicScotland = new MsoLanguageID(1084);
  public final static MsoLanguageID msoLanguageIDGalician = new MsoLanguageID(1110);
  public final static MsoLanguageID msoLanguageIDGeorgian = new MsoLanguageID(1079);
  public final static MsoLanguageID msoLanguageIDGermanAustria = new MsoLanguageID(3079);
  public final static MsoLanguageID msoLanguageIDGerman = new MsoLanguageID(1031);
  public final static MsoLanguageID msoLanguageIDGermanLiechtenstein = new MsoLanguageID(5127);
  public final static MsoLanguageID msoLanguageIDGermanLuxembourg = new MsoLanguageID(4103);
  public final static MsoLanguageID msoLanguageIDSwissGerman = new MsoLanguageID(2055);
  public final static MsoLanguageID msoLanguageIDGreek = new MsoLanguageID(1032);
  public final static MsoLanguageID msoLanguageIDGuarani = new MsoLanguageID(1140);
  public final static MsoLanguageID msoLanguageIDGujarati = new MsoLanguageID(1095);
  public final static MsoLanguageID msoLanguageIDHausa = new MsoLanguageID(1128);
  public final static MsoLanguageID msoLanguageIDHawaiian = new MsoLanguageID(1141);
  public final static MsoLanguageID msoLanguageIDHebrew = new MsoLanguageID(1037);
  public final static MsoLanguageID msoLanguageIDHindi = new MsoLanguageID(1081);
  public final static MsoLanguageID msoLanguageIDHungarian = new MsoLanguageID(1038);
  public final static MsoLanguageID msoLanguageIDIbibio = new MsoLanguageID(1129);
  public final static MsoLanguageID msoLanguageIDIcelandic = new MsoLanguageID(1039);
  public final static MsoLanguageID msoLanguageIDIgbo = new MsoLanguageID(1136);
  public final static MsoLanguageID msoLanguageIDIndonesian = new MsoLanguageID(1057);
  public final static MsoLanguageID msoLanguageIDInuktitut = new MsoLanguageID(1117);
  public final static MsoLanguageID msoLanguageIDItalian = new MsoLanguageID(1040);
  public final static MsoLanguageID msoLanguageIDSwissItalian = new MsoLanguageID(2064);
  public final static MsoLanguageID msoLanguageIDJapanese = new MsoLanguageID(1041);
  public final static MsoLanguageID msoLanguageIDKannada = new MsoLanguageID(1099);
  public final static MsoLanguageID msoLanguageIDKanuri = new MsoLanguageID(1137);
  public final static MsoLanguageID msoLanguageIDKashmiri = new MsoLanguageID(1120);
  public final static MsoLanguageID msoLanguageIDKashmiriDevanagari = new MsoLanguageID(2144);
  public final static MsoLanguageID msoLanguageIDKazakh = new MsoLanguageID(1087);
  public final static MsoLanguageID msoLanguageIDKhmer = new MsoLanguageID(1107);
  public final static MsoLanguageID msoLanguageIDKirghiz = new MsoLanguageID(1088);
  public final static MsoLanguageID msoLanguageIDKonkani = new MsoLanguageID(1111);
  public final static MsoLanguageID msoLanguageIDKorean = new MsoLanguageID(1042);
  public final static MsoLanguageID msoLanguageIDKyrgyz = new MsoLanguageID(1088);
  public final static MsoLanguageID msoLanguageIDLatin = new MsoLanguageID(1142);
  public final static MsoLanguageID msoLanguageIDLao = new MsoLanguageID(1108);
  public final static MsoLanguageID msoLanguageIDLatvian = new MsoLanguageID(1062);
  public final static MsoLanguageID msoLanguageIDLithuanian = new MsoLanguageID(1063);
  public final static MsoLanguageID msoLanguageIDMacedonian = new MsoLanguageID(1071);
  public final static MsoLanguageID msoLanguageIDMacedonianFYROM = new MsoLanguageID(1071);
  public final static MsoLanguageID msoLanguageIDMalaysian = new MsoLanguageID(1086);
  public final static MsoLanguageID msoLanguageIDMalayBruneiDarussalam = new MsoLanguageID(2110);
  public final static MsoLanguageID msoLanguageIDMalayalam = new MsoLanguageID(1100);
  public final static MsoLanguageID msoLanguageIDMaltese = new MsoLanguageID(1082);
  public final static MsoLanguageID msoLanguageIDManipuri = new MsoLanguageID(1112);
  public final static MsoLanguageID msoLanguageIDMaori = new MsoLanguageID(1153);
  public final static MsoLanguageID msoLanguageIDMarathi = new MsoLanguageID(1102);
  public final static MsoLanguageID msoLanguageIDMongolian = new MsoLanguageID(1104);
  public final static MsoLanguageID msoLanguageIDNepali = new MsoLanguageID(1121);
  public final static MsoLanguageID msoLanguageIDNorwegianBokmol = new MsoLanguageID(1044);
  public final static MsoLanguageID msoLanguageIDNorwegianNynorsk = new MsoLanguageID(2068);
  public final static MsoLanguageID msoLanguageIDOriya = new MsoLanguageID(1096);
  public final static MsoLanguageID msoLanguageIDOromo = new MsoLanguageID(1138);
  public final static MsoLanguageID msoLanguageIDPashto = new MsoLanguageID(1123);
  public final static MsoLanguageID msoLanguageIDPolish = new MsoLanguageID(1045);
  public final static MsoLanguageID msoLanguageIDBrazilianPortuguese = new MsoLanguageID(1046);
  public final static MsoLanguageID msoLanguageIDPortuguese = new MsoLanguageID(2070);
  public final static MsoLanguageID msoLanguageIDPunjabi = new MsoLanguageID(1094);
  public final static MsoLanguageID msoLanguageIDQuechuaBolivia = new MsoLanguageID(1131);
  public final static MsoLanguageID msoLanguageIDQuechuaEcuador = new MsoLanguageID(2155);
  public final static MsoLanguageID msoLanguageIDQuechuaPeru = new MsoLanguageID(3179);
  public final static MsoLanguageID msoLanguageIDRhaetoRomanic = new MsoLanguageID(1047);
  public final static MsoLanguageID msoLanguageIDRomanianMoldova = new MsoLanguageID(2072);
  public final static MsoLanguageID msoLanguageIDRomanian = new MsoLanguageID(1048);
  public final static MsoLanguageID msoLanguageIDRussianMoldova = new MsoLanguageID(2073);
  public final static MsoLanguageID msoLanguageIDRussian = new MsoLanguageID(1049);
  public final static MsoLanguageID msoLanguageIDSamiLappish = new MsoLanguageID(1083);
  public final static MsoLanguageID msoLanguageIDSanskrit = new MsoLanguageID(1103);
  public final static MsoLanguageID msoLanguageIDSepedi = new MsoLanguageID(1132);
  public final static MsoLanguageID msoLanguageIDSerbianBosniaHerzegovinaCyrillic = new MsoLanguageID(7194);
  public final static MsoLanguageID msoLanguageIDSerbianBosniaHerzegovinaLatin = new MsoLanguageID(6170);
  public final static MsoLanguageID msoLanguageIDSerbianCyrillic = new MsoLanguageID(3098);
  public final static MsoLanguageID msoLanguageIDSerbianLatin = new MsoLanguageID(2074);
  public final static MsoLanguageID msoLanguageIDSesotho = new MsoLanguageID(1072);
  public final static MsoLanguageID msoLanguageIDSindhi = new MsoLanguageID(1113);
  public final static MsoLanguageID msoLanguageIDSindhiPakistan = new MsoLanguageID(2137);
  public final static MsoLanguageID msoLanguageIDSinhalese = new MsoLanguageID(1115);
  public final static MsoLanguageID msoLanguageIDSlovak = new MsoLanguageID(1051);
  public final static MsoLanguageID msoLanguageIDSlovenian = new MsoLanguageID(1060);
  public final static MsoLanguageID msoLanguageIDSomali = new MsoLanguageID(1143);
  public final static MsoLanguageID msoLanguageIDSorbian = new MsoLanguageID(1070);
  public final static MsoLanguageID msoLanguageIDSpanishArgentina = new MsoLanguageID(11274);
  public final static MsoLanguageID msoLanguageIDSpanishBolivia = new MsoLanguageID(16394);
  public final static MsoLanguageID msoLanguageIDSpanishChile = new MsoLanguageID(13322);
  public final static MsoLanguageID msoLanguageIDSpanishColombia = new MsoLanguageID(9226);
  public final static MsoLanguageID msoLanguageIDSpanishCostaRica = new MsoLanguageID(5130);
  public final static MsoLanguageID msoLanguageIDSpanishDominicanRepublic = new MsoLanguageID(7178);
  public final static MsoLanguageID msoLanguageIDSpanishEcuador = new MsoLanguageID(12298);
  public final static MsoLanguageID msoLanguageIDSpanishElSalvador = new MsoLanguageID(17418);
  public final static MsoLanguageID msoLanguageIDSpanishGuatemala = new MsoLanguageID(4106);
  public final static MsoLanguageID msoLanguageIDSpanishHonduras = new MsoLanguageID(18442);
  public final static MsoLanguageID msoLanguageIDMexicanSpanish = new MsoLanguageID(2058);
  public final static MsoLanguageID msoLanguageIDSpanishNicaragua = new MsoLanguageID(19466);
  public final static MsoLanguageID msoLanguageIDSpanishPanama = new MsoLanguageID(6154);
  public final static MsoLanguageID msoLanguageIDSpanishParaguay = new MsoLanguageID(15370);
  public final static MsoLanguageID msoLanguageIDSpanishPeru = new MsoLanguageID(10250);
  public final static MsoLanguageID msoLanguageIDSpanishPuertoRico = new MsoLanguageID(20490);
  public final static MsoLanguageID msoLanguageIDSpanishModernSort = new MsoLanguageID(3082);
  public final static MsoLanguageID msoLanguageIDSpanish = new MsoLanguageID(1034);
  public final static MsoLanguageID msoLanguageIDSpanishUruguay = new MsoLanguageID(14346);
  public final static MsoLanguageID msoLanguageIDSpanishVenezuela = new MsoLanguageID(8202);
  public final static MsoLanguageID msoLanguageIDSutu = new MsoLanguageID(1072);
  public final static MsoLanguageID msoLanguageIDSwahili = new MsoLanguageID(1089);
  public final static MsoLanguageID msoLanguageIDSwedishFinland = new MsoLanguageID(2077);
  public final static MsoLanguageID msoLanguageIDSwedish = new MsoLanguageID(1053);
  public final static MsoLanguageID msoLanguageIDSyriac = new MsoLanguageID(1114);
  public final static MsoLanguageID msoLanguageIDTajik = new MsoLanguageID(1064);
  public final static MsoLanguageID msoLanguageIDTamil = new MsoLanguageID(1097);
  public final static MsoLanguageID msoLanguageIDTamazight = new MsoLanguageID(1119);
  public final static MsoLanguageID msoLanguageIDTamazightLatin = new MsoLanguageID(2143);
  public final static MsoLanguageID msoLanguageIDTatar = new MsoLanguageID(1092);
  public final static MsoLanguageID msoLanguageIDTelugu = new MsoLanguageID(1098);
  public final static MsoLanguageID msoLanguageIDThai = new MsoLanguageID(1054);
  public final static MsoLanguageID msoLanguageIDTibetan = new MsoLanguageID(1105);
  public final static MsoLanguageID msoLanguageIDTigrignaEthiopic = new MsoLanguageID(1139);
  public final static MsoLanguageID msoLanguageIDTigrignaEritrea = new MsoLanguageID(2163);
  public final static MsoLanguageID msoLanguageIDTsonga = new MsoLanguageID(1073);
  public final static MsoLanguageID msoLanguageIDTswana = new MsoLanguageID(1074);
  public final static MsoLanguageID msoLanguageIDTurkish = new MsoLanguageID(1055);
  public final static MsoLanguageID msoLanguageIDTurkmen = new MsoLanguageID(1090);
  public final static MsoLanguageID msoLanguageIDUkrainian = new MsoLanguageID(1058);
  public final static MsoLanguageID msoLanguageIDUrdu = new MsoLanguageID(1056);
  public final static MsoLanguageID msoLanguageIDUzbekCyrillic = new MsoLanguageID(2115);
  public final static MsoLanguageID msoLanguageIDUzbekLatin = new MsoLanguageID(1091);
  public final static MsoLanguageID msoLanguageIDVenda = new MsoLanguageID(1075);
  public final static MsoLanguageID msoLanguageIDVietnamese = new MsoLanguageID(1066);
  public final static MsoLanguageID msoLanguageIDWelsh = new MsoLanguageID(1106);
  public final static MsoLanguageID msoLanguageIDXhosa = new MsoLanguageID(1076);
  public final static MsoLanguageID msoLanguageIDYi = new MsoLanguageID(1144);
  public final static MsoLanguageID msoLanguageIDYiddish = new MsoLanguageID(1085);
  public final static MsoLanguageID msoLanguageIDYoruba = new MsoLanguageID(1130);
  public final static MsoLanguageID msoLanguageIDZulu = new MsoLanguageID(1077);

  // Integer constants for bitsets and switch statements
  public final static int _msoLanguageIDMixed = -2;
  public final static int _msoLanguageIDNone = 0;
  public final static int _msoLanguageIDNoProofing = 1024;
  public final static int _msoLanguageIDAfrikaans = 1078;
  public final static int _msoLanguageIDAlbanian = 1052;
  public final static int _msoLanguageIDAmharic = 1118;
  public final static int _msoLanguageIDArabicAlgeria = 5121;
  public final static int _msoLanguageIDArabicBahrain = 15361;
  public final static int _msoLanguageIDArabicEgypt = 3073;
  public final static int _msoLanguageIDArabicIraq = 2049;
  public final static int _msoLanguageIDArabicJordan = 11265;
  public final static int _msoLanguageIDArabicKuwait = 13313;
  public final static int _msoLanguageIDArabicLebanon = 12289;
  public final static int _msoLanguageIDArabicLibya = 4097;
  public final static int _msoLanguageIDArabicMorocco = 6145;
  public final static int _msoLanguageIDArabicOman = 8193;
  public final static int _msoLanguageIDArabicQatar = 16385;
  public final static int _msoLanguageIDArabic = 1025;
  public final static int _msoLanguageIDArabicSyria = 10241;
  public final static int _msoLanguageIDArabicTunisia = 7169;
  public final static int _msoLanguageIDArabicUAE = 14337;
  public final static int _msoLanguageIDArabicYemen = 9217;
  public final static int _msoLanguageIDArmenian = 1067;
  public final static int _msoLanguageIDAssamese = 1101;
  public final static int _msoLanguageIDAzeriCyrillic = 2092;
  public final static int _msoLanguageIDAzeriLatin = 1068;
  public final static int _msoLanguageIDBasque = 1069;
  public final static int _msoLanguageIDByelorussian = 1059;
  public final static int _msoLanguageIDBengali = 1093;
  public final static int _msoLanguageIDBosnian = 4122;
  public final static int _msoLanguageIDBosnianBosniaHerzegovinaCyrillic = 8218;
  public final static int _msoLanguageIDBosnianBosniaHerzegovinaLatin = 5146;
  public final static int _msoLanguageIDBulgarian = 1026;
  public final static int _msoLanguageIDBurmese = 1109;
  public final static int _msoLanguageIDCatalan = 1027;
  public final static int _msoLanguageIDChineseHongKongSAR = 3076;
  public final static int _msoLanguageIDChineseMacaoSAR = 5124;
  public final static int _msoLanguageIDSimplifiedChinese = 2052;
  public final static int _msoLanguageIDChineseSingapore = 4100;
  public final static int _msoLanguageIDTraditionalChinese = 1028;
  public final static int _msoLanguageIDCherokee = 1116;
  public final static int _msoLanguageIDCroatian = 1050;
  public final static int _msoLanguageIDCzech = 1029;
  public final static int _msoLanguageIDDanish = 1030;
  public final static int _msoLanguageIDDivehi = 1125;
  public final static int _msoLanguageIDBelgianDutch = 2067;
  public final static int _msoLanguageIDDutch = 1043;
  public final static int _msoLanguageIDDzongkhaBhutan = 2129;
  public final static int _msoLanguageIDEdo = 1126;
  public final static int _msoLanguageIDEnglishAUS = 3081;
  public final static int _msoLanguageIDEnglishBelize = 10249;
  public final static int _msoLanguageIDEnglishCanadian = 4105;
  public final static int _msoLanguageIDEnglishCaribbean = 9225;
  public final static int _msoLanguageIDEnglishIndonesia = 14345;
  public final static int _msoLanguageIDEnglishIreland = 6153;
  public final static int _msoLanguageIDEnglishJamaica = 8201;
  public final static int _msoLanguageIDEnglishNewZealand = 5129;
  public final static int _msoLanguageIDEnglishPhilippines = 13321;
  public final static int _msoLanguageIDEnglishSouthAfrica = 7177;
  public final static int _msoLanguageIDEnglishTrinidadTobago = 11273;
  public final static int _msoLanguageIDEnglishUK = 2057;
  public final static int _msoLanguageIDEnglishUS = 1033;
  public final static int _msoLanguageIDEnglishZimbabwe = 12297;
  public final static int _msoLanguageIDEstonian = 1061;
  public final static int _msoLanguageIDFaeroese = 1080;
  public final static int _msoLanguageIDFarsi = 1065;
  public final static int _msoLanguageIDFilipino = 1124;
  public final static int _msoLanguageIDFinnish = 1035;
  public final static int _msoLanguageIDBelgianFrench = 2060;
  public final static int _msoLanguageIDFrenchCameroon = 11276;
  public final static int _msoLanguageIDFrenchCanadian = 3084;
  public final static int _msoLanguageIDFrenchCotedIvoire = 12300;
  public final static int _msoLanguageIDFrench = 1036;
  public final static int _msoLanguageIDFrenchHaiti = 15372;
  public final static int _msoLanguageIDFrenchLuxembourg = 5132;
  public final static int _msoLanguageIDFrenchMali = 13324;
  public final static int _msoLanguageIDFrenchMonaco = 6156;
  public final static int _msoLanguageIDFrenchMorocco = 14348;
  public final static int _msoLanguageIDFrenchReunion = 8204;
  public final static int _msoLanguageIDFrenchSenegal = 10252;
  public final static int _msoLanguageIDSwissFrench = 4108;
  public final static int _msoLanguageIDFrenchWestIndies = 7180;
  public final static int _msoLanguageIDFrenchZaire = 9228;
  public final static int _msoLanguageIDFrenchCongoDRC = 9228;
  public final static int _msoLanguageIDFrisianNetherlands = 1122;
  public final static int _msoLanguageIDFulfulde = 1127;
  public final static int _msoLanguageIDGaelicIreland = 2108;
  public final static int _msoLanguageIDGaelicScotland = 1084;
  public final static int _msoLanguageIDGalician = 1110;
  public final static int _msoLanguageIDGeorgian = 1079;
  public final static int _msoLanguageIDGermanAustria = 3079;
  public final static int _msoLanguageIDGerman = 1031;
  public final static int _msoLanguageIDGermanLiechtenstein = 5127;
  public final static int _msoLanguageIDGermanLuxembourg = 4103;
  public final static int _msoLanguageIDSwissGerman = 2055;
  public final static int _msoLanguageIDGreek = 1032;
  public final static int _msoLanguageIDGuarani = 1140;
  public final static int _msoLanguageIDGujarati = 1095;
  public final static int _msoLanguageIDHausa = 1128;
  public final static int _msoLanguageIDHawaiian = 1141;
  public final static int _msoLanguageIDHebrew = 1037;
  public final static int _msoLanguageIDHindi = 1081;
  public final static int _msoLanguageIDHungarian = 1038;
  public final static int _msoLanguageIDIbibio = 1129;
  public final static int _msoLanguageIDIcelandic = 1039;
  public final static int _msoLanguageIDIgbo = 1136;
  public final static int _msoLanguageIDIndonesian = 1057;
  public final static int _msoLanguageIDInuktitut = 1117;
  public final static int _msoLanguageIDItalian = 1040;
  public final static int _msoLanguageIDSwissItalian = 2064;
  public final static int _msoLanguageIDJapanese = 1041;
  public final static int _msoLanguageIDKannada = 1099;
  public final static int _msoLanguageIDKanuri = 1137;
  public final static int _msoLanguageIDKashmiri = 1120;
  public final static int _msoLanguageIDKashmiriDevanagari = 2144;
  public final static int _msoLanguageIDKazakh = 1087;
  public final static int _msoLanguageIDKhmer = 1107;
  public final static int _msoLanguageIDKirghiz = 1088;
  public final static int _msoLanguageIDKonkani = 1111;
  public final static int _msoLanguageIDKorean = 1042;
  public final static int _msoLanguageIDKyrgyz = 1088;
  public final static int _msoLanguageIDLatin = 1142;
  public final static int _msoLanguageIDLao = 1108;
  public final static int _msoLanguageIDLatvian = 1062;
  public final static int _msoLanguageIDLithuanian = 1063;
  public final static int _msoLanguageIDMacedonian = 1071;
  public final static int _msoLanguageIDMacedonianFYROM = 1071;
  public final static int _msoLanguageIDMalaysian = 1086;
  public final static int _msoLanguageIDMalayBruneiDarussalam = 2110;
  public final static int _msoLanguageIDMalayalam = 1100;
  public final static int _msoLanguageIDMaltese = 1082;
  public final static int _msoLanguageIDManipuri = 1112;
  public final static int _msoLanguageIDMaori = 1153;
  public final static int _msoLanguageIDMarathi = 1102;
  public final static int _msoLanguageIDMongolian = 1104;
  public final static int _msoLanguageIDNepali = 1121;
  public final static int _msoLanguageIDNorwegianBokmol = 1044;
  public final static int _msoLanguageIDNorwegianNynorsk = 2068;
  public final static int _msoLanguageIDOriya = 1096;
  public final static int _msoLanguageIDOromo = 1138;
  public final static int _msoLanguageIDPashto = 1123;
  public final static int _msoLanguageIDPolish = 1045;
  public final static int _msoLanguageIDBrazilianPortuguese = 1046;
  public final static int _msoLanguageIDPortuguese = 2070;
  public final static int _msoLanguageIDPunjabi = 1094;
  public final static int _msoLanguageIDQuechuaBolivia = 1131;
  public final static int _msoLanguageIDQuechuaEcuador = 2155;
  public final static int _msoLanguageIDQuechuaPeru = 3179;
  public final static int _msoLanguageIDRhaetoRomanic = 1047;
  public final static int _msoLanguageIDRomanianMoldova = 2072;
  public final static int _msoLanguageIDRomanian = 1048;
  public final static int _msoLanguageIDRussianMoldova = 2073;
  public final static int _msoLanguageIDRussian = 1049;
  public final static int _msoLanguageIDSamiLappish = 1083;
  public final static int _msoLanguageIDSanskrit = 1103;
  public final static int _msoLanguageIDSepedi = 1132;
  public final static int _msoLanguageIDSerbianBosniaHerzegovinaCyrillic = 7194;
  public final static int _msoLanguageIDSerbianBosniaHerzegovinaLatin = 6170;
  public final static int _msoLanguageIDSerbianCyrillic = 3098;
  public final static int _msoLanguageIDSerbianLatin = 2074;
  public final static int _msoLanguageIDSesotho = 1072;
  public final static int _msoLanguageIDSindhi = 1113;
  public final static int _msoLanguageIDSindhiPakistan = 2137;
  public final static int _msoLanguageIDSinhalese = 1115;
  public final static int _msoLanguageIDSlovak = 1051;
  public final static int _msoLanguageIDSlovenian = 1060;
  public final static int _msoLanguageIDSomali = 1143;
  public final static int _msoLanguageIDSorbian = 1070;
  public final static int _msoLanguageIDSpanishArgentina = 11274;
  public final static int _msoLanguageIDSpanishBolivia = 16394;
  public final static int _msoLanguageIDSpanishChile = 13322;
  public final static int _msoLanguageIDSpanishColombia = 9226;
  public final static int _msoLanguageIDSpanishCostaRica = 5130;
  public final static int _msoLanguageIDSpanishDominicanRepublic = 7178;
  public final static int _msoLanguageIDSpanishEcuador = 12298;
  public final static int _msoLanguageIDSpanishElSalvador = 17418;
  public final static int _msoLanguageIDSpanishGuatemala = 4106;
  public final static int _msoLanguageIDSpanishHonduras = 18442;
  public final static int _msoLanguageIDMexicanSpanish = 2058;
  public final static int _msoLanguageIDSpanishNicaragua = 19466;
  public final static int _msoLanguageIDSpanishPanama = 6154;
  public final static int _msoLanguageIDSpanishParaguay = 15370;
  public final static int _msoLanguageIDSpanishPeru = 10250;
  public final static int _msoLanguageIDSpanishPuertoRico = 20490;
  public final static int _msoLanguageIDSpanishModernSort = 3082;
  public final static int _msoLanguageIDSpanish = 1034;
  public final static int _msoLanguageIDSpanishUruguay = 14346;
  public final static int _msoLanguageIDSpanishVenezuela = 8202;
  public final static int _msoLanguageIDSutu = 1072;
  public final static int _msoLanguageIDSwahili = 1089;
  public final static int _msoLanguageIDSwedishFinland = 2077;
  public final static int _msoLanguageIDSwedish = 1053;
  public final static int _msoLanguageIDSyriac = 1114;
  public final static int _msoLanguageIDTajik = 1064;
  public final static int _msoLanguageIDTamil = 1097;
  public final static int _msoLanguageIDTamazight = 1119;
  public final static int _msoLanguageIDTamazightLatin = 2143;
  public final static int _msoLanguageIDTatar = 1092;
  public final static int _msoLanguageIDTelugu = 1098;
  public final static int _msoLanguageIDThai = 1054;
  public final static int _msoLanguageIDTibetan = 1105;
  public final static int _msoLanguageIDTigrignaEthiopic = 1139;
  public final static int _msoLanguageIDTigrignaEritrea = 2163;
  public final static int _msoLanguageIDTsonga = 1073;
  public final static int _msoLanguageIDTswana = 1074;
  public final static int _msoLanguageIDTurkish = 1055;
  public final static int _msoLanguageIDTurkmen = 1090;
  public final static int _msoLanguageIDUkrainian = 1058;
  public final static int _msoLanguageIDUrdu = 1056;
  public final static int _msoLanguageIDUzbekCyrillic = 2115;
  public final static int _msoLanguageIDUzbekLatin = 1091;
  public final static int _msoLanguageIDVenda = 1075;
  public final static int _msoLanguageIDVietnamese = 1066;
  public final static int _msoLanguageIDWelsh = 1106;
  public final static int _msoLanguageIDXhosa = 1076;
  public final static int _msoLanguageIDYi = 1144;
  public final static int _msoLanguageIDYiddish = 1085;
  public final static int _msoLanguageIDYoruba = 1130;
  public final static int _msoLanguageIDZulu = 1077;

  // Value, readonly field.
  public final int value;

  // Private constructor, use valueOf to create an instance.
  private MsoLanguageID(int value) { this.value = value; }

  // Return one of the predefined typed constants for the given value or create a new object.
  public static  MsoLanguageID valueOf(int value) {
    switch(value) {
    case -2: return msoLanguageIDMixed;
    case 0: return msoLanguageIDNone;
    case 1024: return msoLanguageIDNoProofing;
    case 1078: return msoLanguageIDAfrikaans;
    case 1052: return msoLanguageIDAlbanian;
    case 1118: return msoLanguageIDAmharic;
    case 5121: return msoLanguageIDArabicAlgeria;
    case 15361: return msoLanguageIDArabicBahrain;
    case 3073: return msoLanguageIDArabicEgypt;
    case 2049: return msoLanguageIDArabicIraq;
    case 11265: return msoLanguageIDArabicJordan;
    case 13313: return msoLanguageIDArabicKuwait;
    case 12289: return msoLanguageIDArabicLebanon;
    case 4097: return msoLanguageIDArabicLibya;
    case 6145: return msoLanguageIDArabicMorocco;
    case 8193: return msoLanguageIDArabicOman;
    case 16385: return msoLanguageIDArabicQatar;
    case 1025: return msoLanguageIDArabic;
    case 10241: return msoLanguageIDArabicSyria;
    case 7169: return msoLanguageIDArabicTunisia;
    case 14337: return msoLanguageIDArabicUAE;
    case 9217: return msoLanguageIDArabicYemen;
    case 1067: return msoLanguageIDArmenian;
    case 1101: return msoLanguageIDAssamese;
    case 2092: return msoLanguageIDAzeriCyrillic;
    case 1068: return msoLanguageIDAzeriLatin;
    case 1069: return msoLanguageIDBasque;
    case 1059: return msoLanguageIDByelorussian;
    case 1093: return msoLanguageIDBengali;
    case 4122: return msoLanguageIDBosnian;
    case 8218: return msoLanguageIDBosnianBosniaHerzegovinaCyrillic;
    case 5146: return msoLanguageIDBosnianBosniaHerzegovinaLatin;
    case 1026: return msoLanguageIDBulgarian;
    case 1109: return msoLanguageIDBurmese;
    case 1027: return msoLanguageIDCatalan;
    case 3076: return msoLanguageIDChineseHongKongSAR;
    case 5124: return msoLanguageIDChineseMacaoSAR;
    case 2052: return msoLanguageIDSimplifiedChinese;
    case 4100: return msoLanguageIDChineseSingapore;
    case 1028: return msoLanguageIDTraditionalChinese;
    case 1116: return msoLanguageIDCherokee;
    case 1050: return msoLanguageIDCroatian;
    case 1029: return msoLanguageIDCzech;
    case 1030: return msoLanguageIDDanish;
    case 1125: return msoLanguageIDDivehi;
    case 2067: return msoLanguageIDBelgianDutch;
    case 1043: return msoLanguageIDDutch;
    case 2129: return msoLanguageIDDzongkhaBhutan;
    case 1126: return msoLanguageIDEdo;
    case 3081: return msoLanguageIDEnglishAUS;
    case 10249: return msoLanguageIDEnglishBelize;
    case 4105: return msoLanguageIDEnglishCanadian;
    case 9225: return msoLanguageIDEnglishCaribbean;
    case 14345: return msoLanguageIDEnglishIndonesia;
    case 6153: return msoLanguageIDEnglishIreland;
    case 8201: return msoLanguageIDEnglishJamaica;
    case 5129: return msoLanguageIDEnglishNewZealand;
    case 13321: return msoLanguageIDEnglishPhilippines;
    case 7177: return msoLanguageIDEnglishSouthAfrica;
    case 11273: return msoLanguageIDEnglishTrinidadTobago;
    case 2057: return msoLanguageIDEnglishUK;
    case 1033: return msoLanguageIDEnglishUS;
    case 12297: return msoLanguageIDEnglishZimbabwe;
    case 1061: return msoLanguageIDEstonian;
    case 1080: return msoLanguageIDFaeroese;
    case 1065: return msoLanguageIDFarsi;
    case 1124: return msoLanguageIDFilipino;
    case 1035: return msoLanguageIDFinnish;
    case 2060: return msoLanguageIDBelgianFrench;
    case 11276: return msoLanguageIDFrenchCameroon;
    case 3084: return msoLanguageIDFrenchCanadian;
    case 12300: return msoLanguageIDFrenchCotedIvoire;
    case 1036: return msoLanguageIDFrench;
    case 15372: return msoLanguageIDFrenchHaiti;
    case 5132: return msoLanguageIDFrenchLuxembourg;
    case 13324: return msoLanguageIDFrenchMali;
    case 6156: return msoLanguageIDFrenchMonaco;
    case 14348: return msoLanguageIDFrenchMorocco;
    case 8204: return msoLanguageIDFrenchReunion;
    case 10252: return msoLanguageIDFrenchSenegal;
    case 4108: return msoLanguageIDSwissFrench;
    case 7180: return msoLanguageIDFrenchWestIndies;
    case 9228: return msoLanguageIDFrenchZaire;
    //se 9228: return msoLanguageIDFrenchCongoDRC; // same as msoLanguageIDFrenchZaire
    case 1122: return msoLanguageIDFrisianNetherlands;
    case 1127: return msoLanguageIDFulfulde;
    case 2108: return msoLanguageIDGaelicIreland;
    case 1084: return msoLanguageIDGaelicScotland;
    case 1110: return msoLanguageIDGalician;
    case 1079: return msoLanguageIDGeorgian;
    case 3079: return msoLanguageIDGermanAustria;
    case 1031: return msoLanguageIDGerman;
    case 5127: return msoLanguageIDGermanLiechtenstein;
    case 4103: return msoLanguageIDGermanLuxembourg;
    case 2055: return msoLanguageIDSwissGerman;
    case 1032: return msoLanguageIDGreek;
    case 1140: return msoLanguageIDGuarani;
    case 1095: return msoLanguageIDGujarati;
    case 1128: return msoLanguageIDHausa;
    case 1141: return msoLanguageIDHawaiian;
    case 1037: return msoLanguageIDHebrew;
    case 1081: return msoLanguageIDHindi;
    case 1038: return msoLanguageIDHungarian;
    case 1129: return msoLanguageIDIbibio;
    case 1039: return msoLanguageIDIcelandic;
    case 1136: return msoLanguageIDIgbo;
    case 1057: return msoLanguageIDIndonesian;
    case 1117: return msoLanguageIDInuktitut;
    case 1040: return msoLanguageIDItalian;
    case 2064: return msoLanguageIDSwissItalian;
    case 1041: return msoLanguageIDJapanese;
    case 1099: return msoLanguageIDKannada;
    case 1137: return msoLanguageIDKanuri;
    case 1120: return msoLanguageIDKashmiri;
    case 2144: return msoLanguageIDKashmiriDevanagari;
    case 1087: return msoLanguageIDKazakh;
    case 1107: return msoLanguageIDKhmer;
    case 1088: return msoLanguageIDKirghiz;
    case 1111: return msoLanguageIDKonkani;
    case 1042: return msoLanguageIDKorean;
    //se 1088: return msoLanguageIDKyrgyz; // same as msoLanguageIDKirghiz
    case 1142: return msoLanguageIDLatin;
    case 1108: return msoLanguageIDLao;
    case 1062: return msoLanguageIDLatvian;
    case 1063: return msoLanguageIDLithuanian;
    case 1071: return msoLanguageIDMacedonian;
    //se 1071: return msoLanguageIDMacedonianFYROM; // same as msoLanguageIDMacedonian
    case 1086: return msoLanguageIDMalaysian;
    case 2110: return msoLanguageIDMalayBruneiDarussalam;
    case 1100: return msoLanguageIDMalayalam;
    case 1082: return msoLanguageIDMaltese;
    case 1112: return msoLanguageIDManipuri;
    case 1153: return msoLanguageIDMaori;
    case 1102: return msoLanguageIDMarathi;
    case 1104: return msoLanguageIDMongolian;
    case 1121: return msoLanguageIDNepali;
    case 1044: return msoLanguageIDNorwegianBokmol;
    case 2068: return msoLanguageIDNorwegianNynorsk;
    case 1096: return msoLanguageIDOriya;
    case 1138: return msoLanguageIDOromo;
    case 1123: return msoLanguageIDPashto;
    case 1045: return msoLanguageIDPolish;
    case 1046: return msoLanguageIDBrazilianPortuguese;
    case 2070: return msoLanguageIDPortuguese;
    case 1094: return msoLanguageIDPunjabi;
    case 1131: return msoLanguageIDQuechuaBolivia;
    case 2155: return msoLanguageIDQuechuaEcuador;
    case 3179: return msoLanguageIDQuechuaPeru;
    case 1047: return msoLanguageIDRhaetoRomanic;
    case 2072: return msoLanguageIDRomanianMoldova;
    case 1048: return msoLanguageIDRomanian;
    case 2073: return msoLanguageIDRussianMoldova;
    case 1049: return msoLanguageIDRussian;
    case 1083: return msoLanguageIDSamiLappish;
    case 1103: return msoLanguageIDSanskrit;
    case 1132: return msoLanguageIDSepedi;
    case 7194: return msoLanguageIDSerbianBosniaHerzegovinaCyrillic;
    case 6170: return msoLanguageIDSerbianBosniaHerzegovinaLatin;
    case 3098: return msoLanguageIDSerbianCyrillic;
    case 2074: return msoLanguageIDSerbianLatin;
    case 1072: return msoLanguageIDSesotho;
    case 1113: return msoLanguageIDSindhi;
    case 2137: return msoLanguageIDSindhiPakistan;
    case 1115: return msoLanguageIDSinhalese;
    case 1051: return msoLanguageIDSlovak;
    case 1060: return msoLanguageIDSlovenian;
    case 1143: return msoLanguageIDSomali;
    case 1070: return msoLanguageIDSorbian;
    case 11274: return msoLanguageIDSpanishArgentina;
    case 16394: return msoLanguageIDSpanishBolivia;
    case 13322: return msoLanguageIDSpanishChile;
    case 9226: return msoLanguageIDSpanishColombia;
    case 5130: return msoLanguageIDSpanishCostaRica;
    case 7178: return msoLanguageIDSpanishDominicanRepublic;
    case 12298: return msoLanguageIDSpanishEcuador;
    case 17418: return msoLanguageIDSpanishElSalvador;
    case 4106: return msoLanguageIDSpanishGuatemala;
    case 18442: return msoLanguageIDSpanishHonduras;
    case 2058: return msoLanguageIDMexicanSpanish;
    case 19466: return msoLanguageIDSpanishNicaragua;
    case 6154: return msoLanguageIDSpanishPanama;
    case 15370: return msoLanguageIDSpanishParaguay;
    case 10250: return msoLanguageIDSpanishPeru;
    case 20490: return msoLanguageIDSpanishPuertoRico;
    case 3082: return msoLanguageIDSpanishModernSort;
    case 1034: return msoLanguageIDSpanish;
    case 14346: return msoLanguageIDSpanishUruguay;
    case 8202: return msoLanguageIDSpanishVenezuela;
    //se 1072: return msoLanguageIDSutu; // same as msoLanguageIDSesotho
    case 1089: return msoLanguageIDSwahili;
    case 2077: return msoLanguageIDSwedishFinland;
    case 1053: return msoLanguageIDSwedish;
    case 1114: return msoLanguageIDSyriac;
    case 1064: return msoLanguageIDTajik;
    case 1097: return msoLanguageIDTamil;
    case 1119: return msoLanguageIDTamazight;
    case 2143: return msoLanguageIDTamazightLatin;
    case 1092: return msoLanguageIDTatar;
    case 1098: return msoLanguageIDTelugu;
    case 1054: return msoLanguageIDThai;
    case 1105: return msoLanguageIDTibetan;
    case 1139: return msoLanguageIDTigrignaEthiopic;
    case 2163: return msoLanguageIDTigrignaEritrea;
    case 1073: return msoLanguageIDTsonga;
    case 1074: return msoLanguageIDTswana;
    case 1055: return msoLanguageIDTurkish;
    case 1090: return msoLanguageIDTurkmen;
    case 1058: return msoLanguageIDUkrainian;
    case 1056: return msoLanguageIDUrdu;
    case 2115: return msoLanguageIDUzbekCyrillic;
    case 1091: return msoLanguageIDUzbekLatin;
    case 1075: return msoLanguageIDVenda;
    case 1066: return msoLanguageIDVietnamese;
    case 1106: return msoLanguageIDWelsh;
    case 1076: return msoLanguageIDXhosa;
    case 1144: return msoLanguageIDYi;
    case 1085: return msoLanguageIDYiddish;
    case 1130: return msoLanguageIDYoruba;
    case 1077: return msoLanguageIDZulu;
    default: return new MsoLanguageID(value);
    }
  }

  public String toString() {
    switch(value) {
    case 1043: return "msoLanguageIDDutch";
    case 5121: return "msoLanguageIDArabicAlgeria";
    case -2: return "msoLanguageIDMixed";
    case 1052: return "msoLanguageIDAlbanian";
    case 1104: return "msoLanguageIDMongolian";
    case 2049: return "msoLanguageIDArabicIraq";
    case 1078: return "msoLanguageIDAfrikaans";
    case 1113: return "msoLanguageIDSindhi";
    case 3081: return "msoLanguageIDEnglishAUS";
    case 1067: return "msoLanguageIDArmenian";
    case 1085: return "msoLanguageIDYiddish";
    case 0: return "msoLanguageIDNone";
    case 1129: return "msoLanguageIDIbibio";
    case 1033: return "msoLanguageIDEnglishUS";
    case 1060: return "msoLanguageIDSlovenian";
    case 4122: return "msoLanguageIDBosnian";
    case 1114: return "msoLanguageIDSyriac";
    case 3073: return "msoLanguageIDArabicEgypt";
    case 7177: return "msoLanguageIDEnglishSouthAfrica";
    case 1024: return "msoLanguageIDNoProofing";
    case 2129: return "msoLanguageIDDzongkhaBhutan";
    case 1125: return "msoLanguageIDDivehi";
    case 1118: return "msoLanguageIDAmharic";
    case 1030: return "msoLanguageIDDanish";
    case 1063: return "msoLanguageIDLithuanian";
    case 15361: return "msoLanguageIDArabicBahrain";
    case 11265: return "msoLanguageIDArabicJordan";
    case 13313: return "msoLanguageIDArabicKuwait";
    case 12289: return "msoLanguageIDArabicLebanon";
    case 16385: return "msoLanguageIDArabicQatar";
    case 4105: return "msoLanguageIDEnglishCanadian";
    case 3076: return "msoLanguageIDChineseHongKongSAR";
    case 4097: return "msoLanguageIDArabicLibya";
    case 1050: return "msoLanguageIDCroatian";
    case 5132: return "msoLanguageIDFrenchLuxembourg";
    case 6145: return "msoLanguageIDArabicMorocco";
    case 14345: return "msoLanguageIDEnglishIndonesia";
    case 8193: return "msoLanguageIDArabicOman";
    case 1025: return "msoLanguageIDArabic";
    case 1092: return "msoLanguageIDTatar";
    case 10241: return "msoLanguageIDArabicSyria";
    case 1137: return "msoLanguageIDKanuri";
    case 1029: return "msoLanguageIDCzech";
    case 7169: return "msoLanguageIDArabicTunisia";
    case 14337: return "msoLanguageIDArabicUAE";
    case 9217: return "msoLanguageIDArabicYemen";
    case 1093: return "msoLanguageIDBengali";
    case 1101: return "msoLanguageIDAssamese";
    case 2092: return "msoLanguageIDAzeriCyrillic";
    case 1068: return "msoLanguageIDAzeriLatin";
    case 1069: return "msoLanguageIDBasque";
    case 1136: return "msoLanguageIDIgbo";
    case 1028: return "msoLanguageIDTraditionalChinese";
    case 4100: return "msoLanguageIDChineseSingapore";
    case 1059: return "msoLanguageIDByelorussian";
    case 8218: return "msoLanguageIDBosnianBosniaHerzegovinaCyrillic";
    case 1095: return "msoLanguageIDGujarati";
    case 5146: return "msoLanguageIDBosnianBosniaHerzegovinaLatin";
    case 1138: return "msoLanguageIDOromo";
    case 1026: return "msoLanguageIDBulgarian";
    case 1109: return "msoLanguageIDBurmese";
    case 5130: return "msoLanguageIDSpanishCostaRica";
    case 2067: return "msoLanguageIDBelgianDutch";
    case 1139: return "msoLanguageIDTigrignaEthiopic";
    case 1027: return "msoLanguageIDCatalan";
    case 2060: return "msoLanguageIDBelgianFrench";
    case 5124: return "msoLanguageIDChineseMacaoSAR";
    case 2108: return "msoLanguageIDGaelicIreland";
    case 2052: return "msoLanguageIDSimplifiedChinese";
    case 1080: return "msoLanguageIDFaeroese";
    case 1116: return "msoLanguageIDCherokee";
    case 11274: return "msoLanguageIDSpanishArgentina";
    case 9225: return "msoLanguageIDEnglishCaribbean";
    case 17418: return "msoLanguageIDSpanishElSalvador";
    case 1126: return "msoLanguageIDEdo";
    case 1074: return "msoLanguageIDTswana";
    case 10249: return "msoLanguageIDEnglishBelize";
    case 1086: return "msoLanguageIDMalaysian";
    case 6153: return "msoLanguageIDEnglishIreland";
    case 1087: return "msoLanguageIDKazakh";
    case 8201: return "msoLanguageIDEnglishJamaica";
    case 5129: return "msoLanguageIDEnglishNewZealand";
    case 1061: return "msoLanguageIDEstonian";
    case 13321: return "msoLanguageIDEnglishPhilippines";
    case 11273: return "msoLanguageIDEnglishTrinidadTobago";
    case 1097: return "msoLanguageIDTamil";
    case 2057: return "msoLanguageIDEnglishUK";
    case 4106: return "msoLanguageIDSpanishGuatemala";
    case 1123: return "msoLanguageIDPashto";
    case 1039: return "msoLanguageIDIcelandic";
    case 7180: return "msoLanguageIDFrenchWestIndies";
    case 12297: return "msoLanguageIDEnglishZimbabwe";
    case 1065: return "msoLanguageIDFarsi";
    case 1124: return "msoLanguageIDFilipino";
    case 1035: return "msoLanguageIDFinnish";
    case 2072: return "msoLanguageIDRomanianMoldova";
    case 11276: return "msoLanguageIDFrenchCameroon";
    case 3084: return "msoLanguageIDFrenchCanadian";
    case 12300: return "msoLanguageIDFrenchCotedIvoire";
    case 1036: return "msoLanguageIDFrench";
    case 15372: return "msoLanguageIDFrenchHaiti";
    case 1121: return "msoLanguageIDNepali";
    case 13324: return "msoLanguageIDFrenchMali";
    case 6156: return "msoLanguageIDFrenchMonaco";
    case 1066: return "msoLanguageIDVietnamese";
    case 14348: return "msoLanguageIDFrenchMorocco";
    case 8204: return "msoLanguageIDFrenchReunion";
    case 1096: return "msoLanguageIDOriya";
    case 10252: return "msoLanguageIDFrenchSenegal";
    case 4108: return "msoLanguageIDSwissFrench";
    case 1044: return "msoLanguageIDNorwegianBokmol";
    case 9228: return "msoLanguageIDFrenchZaire";
    case 1038: return "msoLanguageIDHungarian";
    case 1122: return "msoLanguageIDFrisianNetherlands";
    case 1127: return "msoLanguageIDFulfulde";
    case 1084: return "msoLanguageIDGaelicScotland";
    case 1110: return "msoLanguageIDGalician";
    case 1079: return "msoLanguageIDGeorgian";
    case 3079: return "msoLanguageIDGermanAustria";
    case 1031: return "msoLanguageIDGerman";
    case 5127: return "msoLanguageIDGermanLiechtenstein";
    case 4103: return "msoLanguageIDGermanLuxembourg";
    case 2055: return "msoLanguageIDSwissGerman";
    case 1128: return "msoLanguageIDHausa";
    case 1032: return "msoLanguageIDGreek";
    case 1140: return "msoLanguageIDGuarani";
    case 1141: return "msoLanguageIDHawaiian";
    case 1037: return "msoLanguageIDHebrew";
    case 1081: return "msoLanguageIDHindi";
    case 2163: return "msoLanguageIDTigrignaEritrea";
    case 1057: return "msoLanguageIDIndonesian";
    case 1117: return "msoLanguageIDInuktitut";
    case 1040: return "msoLanguageIDItalian";
    case 2064: return "msoLanguageIDSwissItalian";
    case 6154: return "msoLanguageIDSpanishPanama";
    case 1041: return "msoLanguageIDJapanese";
    case 1099: return "msoLanguageIDKannada";
    case 1120: return "msoLanguageIDKashmiri";
    case 2144: return "msoLanguageIDKashmiriDevanagari";
    case 1107: return "msoLanguageIDKhmer";
    case 1088: return "msoLanguageIDKirghiz";
    case 1111: return "msoLanguageIDKonkani";
    case 1042: return "msoLanguageIDKorean";
    case 1142: return "msoLanguageIDLatin";
    case 1108: return "msoLanguageIDLao";
    case 1062: return "msoLanguageIDLatvian";
    case 1071: return "msoLanguageIDMacedonian";
    case 1073: return "msoLanguageIDTsonga";
    case 2110: return "msoLanguageIDMalayBruneiDarussalam";
    case 1100: return "msoLanguageIDMalayalam";
    case 1082: return "msoLanguageIDMaltese";
    case 1112: return "msoLanguageIDManipuri";
    case 1153: return "msoLanguageIDMaori";
    case 1102: return "msoLanguageIDMarathi";
    case 2068: return "msoLanguageIDNorwegianNynorsk";
    case 1045: return "msoLanguageIDPolish";
    case 1046: return "msoLanguageIDBrazilianPortuguese";
    case 2070: return "msoLanguageIDPortuguese";
    case 15370: return "msoLanguageIDSpanishParaguay";
    case 2058: return "msoLanguageIDMexicanSpanish";
    case 1094: return "msoLanguageIDPunjabi";
    case 1131: return "msoLanguageIDQuechuaBolivia";
    case 2155: return "msoLanguageIDQuechuaEcuador";
    case 1049: return "msoLanguageIDRussian";
    case 3179: return "msoLanguageIDQuechuaPeru";
    case 1047: return "msoLanguageIDRhaetoRomanic";
    case 1048: return "msoLanguageIDRomanian";
    case 2073: return "msoLanguageIDRussianMoldova";
    case 1083: return "msoLanguageIDSamiLappish";
    case 1103: return "msoLanguageIDSanskrit";
    case 1132: return "msoLanguageIDSepedi";
    case 7194: return "msoLanguageIDSerbianBosniaHerzegovinaCyrillic";
    case 6170: return "msoLanguageIDSerbianBosniaHerzegovinaLatin";
    case 3098: return "msoLanguageIDSerbianCyrillic";
    case 2074: return "msoLanguageIDSerbianLatin";
    case 1072: return "msoLanguageIDSesotho";
    case 2137: return "msoLanguageIDSindhiPakistan";
    case 1115: return "msoLanguageIDSinhalese";
    case 1051: return "msoLanguageIDSlovak";
    case 1143: return "msoLanguageIDSomali";
    case 1070: return "msoLanguageIDSorbian";
    case 16394: return "msoLanguageIDSpanishBolivia";
    case 13322: return "msoLanguageIDSpanishChile";
    case 9226: return "msoLanguageIDSpanishColombia";
    case 7178: return "msoLanguageIDSpanishDominicanRepublic";
    case 12298: return "msoLanguageIDSpanishEcuador";
    case 18442: return "msoLanguageIDSpanishHonduras";
    case 19466: return "msoLanguageIDSpanishNicaragua";
    case 10250: return "msoLanguageIDSpanishPeru";
    case 20490: return "msoLanguageIDSpanishPuertoRico";
    case 3082: return "msoLanguageIDSpanishModernSort";
    case 1034: return "msoLanguageIDSpanish";
    case 14346: return "msoLanguageIDSpanishUruguay";
    case 8202: return "msoLanguageIDSpanishVenezuela";
    case 1089: return "msoLanguageIDSwahili";
    case 2077: return "msoLanguageIDSwedishFinland";
    case 1053: return "msoLanguageIDSwedish";
    case 1064: return "msoLanguageIDTajik";
    case 1119: return "msoLanguageIDTamazight";
    case 2143: return "msoLanguageIDTamazightLatin";
    case 1098: return "msoLanguageIDTelugu";
    case 1054: return "msoLanguageIDThai";
    case 1105: return "msoLanguageIDTibetan";
    case 1055: return "msoLanguageIDTurkish";
    case 1090: return "msoLanguageIDTurkmen";
    case 1058: return "msoLanguageIDUkrainian";
    case 1056: return "msoLanguageIDUrdu";
    case 1076: return "msoLanguageIDXhosa";
    case 2115: return "msoLanguageIDUzbekCyrillic";
    case 1091: return "msoLanguageIDUzbekLatin";
    case 1075: return "msoLanguageIDVenda";
    case 1106: return "msoLanguageIDWelsh";
    case 1144: return "msoLanguageIDYi";
    case 1130: return "msoLanguageIDYoruba";
    case 1077: return "msoLanguageIDZulu";
    default: {
      StringBuilder sbuf = new StringBuilder();
      sbuf.append("[").append(value).append("=");
      if ((value & 1043) != 0) sbuf.append("|msoLanguageIDDutch");
      if ((value & 5121) != 0) sbuf.append("|msoLanguageIDArabicAlgeria");
      if ((value & -2) != 0) sbuf.append("|msoLanguageIDMixed");
      if ((value & 1052) != 0) sbuf.append("|msoLanguageIDAlbanian");
      if ((value & 1104) != 0) sbuf.append("|msoLanguageIDMongolian");
      if ((value & 2049) != 0) sbuf.append("|msoLanguageIDArabicIraq");
      if ((value & 1078) != 0) sbuf.append("|msoLanguageIDAfrikaans");
      if ((value & 1113) != 0) sbuf.append("|msoLanguageIDSindhi");
      if ((value & 3081) != 0) sbuf.append("|msoLanguageIDEnglishAUS");
      if ((value & 1067) != 0) sbuf.append("|msoLanguageIDArmenian");
      if ((value & 1085) != 0) sbuf.append("|msoLanguageIDYiddish");
      if ((value & 0) != 0) sbuf.append("|msoLanguageIDNone");
      if ((value & 1129) != 0) sbuf.append("|msoLanguageIDIbibio");
      if ((value & 1033) != 0) sbuf.append("|msoLanguageIDEnglishUS");
      if ((value & 1060) != 0) sbuf.append("|msoLanguageIDSlovenian");
      if ((value & 4122) != 0) sbuf.append("|msoLanguageIDBosnian");
      if ((value & 1114) != 0) sbuf.append("|msoLanguageIDSyriac");
      if ((value & 3073) != 0) sbuf.append("|msoLanguageIDArabicEgypt");
      if ((value & 7177) != 0) sbuf.append("|msoLanguageIDEnglishSouthAfrica");
      if ((value & 1024) != 0) sbuf.append("|msoLanguageIDNoProofing");
      if ((value & 2129) != 0) sbuf.append("|msoLanguageIDDzongkhaBhutan");
      if ((value & 1125) != 0) sbuf.append("|msoLanguageIDDivehi");
      if ((value & 1118) != 0) sbuf.append("|msoLanguageIDAmharic");
      if ((value & 1030) != 0) sbuf.append("|msoLanguageIDDanish");
      if ((value & 1063) != 0) sbuf.append("|msoLanguageIDLithuanian");
      if ((value & 15361) != 0) sbuf.append("|msoLanguageIDArabicBahrain");
      if ((value & 11265) != 0) sbuf.append("|msoLanguageIDArabicJordan");
      if ((value & 13313) != 0) sbuf.append("|msoLanguageIDArabicKuwait");
      if ((value & 12289) != 0) sbuf.append("|msoLanguageIDArabicLebanon");
      if ((value & 16385) != 0) sbuf.append("|msoLanguageIDArabicQatar");
      if ((value & 4105) != 0) sbuf.append("|msoLanguageIDEnglishCanadian");
      if ((value & 3076) != 0) sbuf.append("|msoLanguageIDChineseHongKongSAR");
      if ((value & 4097) != 0) sbuf.append("|msoLanguageIDArabicLibya");
      if ((value & 1050) != 0) sbuf.append("|msoLanguageIDCroatian");
      if ((value & 5132) != 0) sbuf.append("|msoLanguageIDFrenchLuxembourg");
      if ((value & 6145) != 0) sbuf.append("|msoLanguageIDArabicMorocco");
      if ((value & 14345) != 0) sbuf.append("|msoLanguageIDEnglishIndonesia");
      if ((value & 8193) != 0) sbuf.append("|msoLanguageIDArabicOman");
      if ((value & 1025) != 0) sbuf.append("|msoLanguageIDArabic");
      if ((value & 1092) != 0) sbuf.append("|msoLanguageIDTatar");
      if ((value & 10241) != 0) sbuf.append("|msoLanguageIDArabicSyria");
      if ((value & 1137) != 0) sbuf.append("|msoLanguageIDKanuri");
      if ((value & 1029) != 0) sbuf.append("|msoLanguageIDCzech");
      if ((value & 7169) != 0) sbuf.append("|msoLanguageIDArabicTunisia");
      if ((value & 14337) != 0) sbuf.append("|msoLanguageIDArabicUAE");
      if ((value & 9217) != 0) sbuf.append("|msoLanguageIDArabicYemen");
      if ((value & 1093) != 0) sbuf.append("|msoLanguageIDBengali");
      if ((value & 1101) != 0) sbuf.append("|msoLanguageIDAssamese");
      if ((value & 2092) != 0) sbuf.append("|msoLanguageIDAzeriCyrillic");
      if ((value & 1068) != 0) sbuf.append("|msoLanguageIDAzeriLatin");
      if ((value & 1069) != 0) sbuf.append("|msoLanguageIDBasque");
      if ((value & 1136) != 0) sbuf.append("|msoLanguageIDIgbo");
      if ((value & 1028) != 0) sbuf.append("|msoLanguageIDTraditionalChinese");
      if ((value & 4100) != 0) sbuf.append("|msoLanguageIDChineseSingapore");
      if ((value & 1059) != 0) sbuf.append("|msoLanguageIDByelorussian");
      if ((value & 8218) != 0) sbuf.append("|msoLanguageIDBosnianBosniaHerzegovinaCyrillic");
      if ((value & 1095) != 0) sbuf.append("|msoLanguageIDGujarati");
      if ((value & 5146) != 0) sbuf.append("|msoLanguageIDBosnianBosniaHerzegovinaLatin");
      if ((value & 1138) != 0) sbuf.append("|msoLanguageIDOromo");
      if ((value & 1026) != 0) sbuf.append("|msoLanguageIDBulgarian");
      if ((value & 1109) != 0) sbuf.append("|msoLanguageIDBurmese");
      if ((value & 5130) != 0) sbuf.append("|msoLanguageIDSpanishCostaRica");
      if ((value & 2067) != 0) sbuf.append("|msoLanguageIDBelgianDutch");
      if ((value & 1139) != 0) sbuf.append("|msoLanguageIDTigrignaEthiopic");
      if ((value & 1027) != 0) sbuf.append("|msoLanguageIDCatalan");
      if ((value & 2060) != 0) sbuf.append("|msoLanguageIDBelgianFrench");
      if ((value & 5124) != 0) sbuf.append("|msoLanguageIDChineseMacaoSAR");
      if ((value & 2108) != 0) sbuf.append("|msoLanguageIDGaelicIreland");
      if ((value & 2052) != 0) sbuf.append("|msoLanguageIDSimplifiedChinese");
      if ((value & 1080) != 0) sbuf.append("|msoLanguageIDFaeroese");
      if ((value & 1116) != 0) sbuf.append("|msoLanguageIDCherokee");
      if ((value & 11274) != 0) sbuf.append("|msoLanguageIDSpanishArgentina");
      if ((value & 9225) != 0) sbuf.append("|msoLanguageIDEnglishCaribbean");
      if ((value & 17418) != 0) sbuf.append("|msoLanguageIDSpanishElSalvador");
      if ((value & 1126) != 0) sbuf.append("|msoLanguageIDEdo");
      if ((value & 1074) != 0) sbuf.append("|msoLanguageIDTswana");
      if ((value & 10249) != 0) sbuf.append("|msoLanguageIDEnglishBelize");
      if ((value & 1086) != 0) sbuf.append("|msoLanguageIDMalaysian");
      if ((value & 6153) != 0) sbuf.append("|msoLanguageIDEnglishIreland");
      if ((value & 1087) != 0) sbuf.append("|msoLanguageIDKazakh");
      if ((value & 8201) != 0) sbuf.append("|msoLanguageIDEnglishJamaica");
      if ((value & 5129) != 0) sbuf.append("|msoLanguageIDEnglishNewZealand");
      if ((value & 1061) != 0) sbuf.append("|msoLanguageIDEstonian");
      if ((value & 13321) != 0) sbuf.append("|msoLanguageIDEnglishPhilippines");
      if ((value & 11273) != 0) sbuf.append("|msoLanguageIDEnglishTrinidadTobago");
      if ((value & 1097) != 0) sbuf.append("|msoLanguageIDTamil");
      if ((value & 2057) != 0) sbuf.append("|msoLanguageIDEnglishUK");
      if ((value & 4106) != 0) sbuf.append("|msoLanguageIDSpanishGuatemala");
      if ((value & 1123) != 0) sbuf.append("|msoLanguageIDPashto");
      if ((value & 1039) != 0) sbuf.append("|msoLanguageIDIcelandic");
      if ((value & 7180) != 0) sbuf.append("|msoLanguageIDFrenchWestIndies");
      if ((value & 12297) != 0) sbuf.append("|msoLanguageIDEnglishZimbabwe");
      if ((value & 1065) != 0) sbuf.append("|msoLanguageIDFarsi");
      if ((value & 1124) != 0) sbuf.append("|msoLanguageIDFilipino");
      if ((value & 1035) != 0) sbuf.append("|msoLanguageIDFinnish");
      if ((value & 2072) != 0) sbuf.append("|msoLanguageIDRomanianMoldova");
      if ((value & 11276) != 0) sbuf.append("|msoLanguageIDFrenchCameroon");
      if ((value & 3084) != 0) sbuf.append("|msoLanguageIDFrenchCanadian");
      if ((value & 12300) != 0) sbuf.append("|msoLanguageIDFrenchCotedIvoire");
      if ((value & 1036) != 0) sbuf.append("|msoLanguageIDFrench");
      if ((value & 15372) != 0) sbuf.append("|msoLanguageIDFrenchHaiti");
      if ((value & 1121) != 0) sbuf.append("|msoLanguageIDNepali");
      if ((value & 13324) != 0) sbuf.append("|msoLanguageIDFrenchMali");
      if ((value & 6156) != 0) sbuf.append("|msoLanguageIDFrenchMonaco");
      if ((value & 1066) != 0) sbuf.append("|msoLanguageIDVietnamese");
      if ((value & 14348) != 0) sbuf.append("|msoLanguageIDFrenchMorocco");
      if ((value & 8204) != 0) sbuf.append("|msoLanguageIDFrenchReunion");
      if ((value & 1096) != 0) sbuf.append("|msoLanguageIDOriya");
      if ((value & 10252) != 0) sbuf.append("|msoLanguageIDFrenchSenegal");
      if ((value & 4108) != 0) sbuf.append("|msoLanguageIDSwissFrench");
      if ((value & 1044) != 0) sbuf.append("|msoLanguageIDNorwegianBokmol");
      if ((value & 9228) != 0) sbuf.append("|msoLanguageIDFrenchZaire");
      if ((value & 1038) != 0) sbuf.append("|msoLanguageIDHungarian");
      if ((value & 1122) != 0) sbuf.append("|msoLanguageIDFrisianNetherlands");
      if ((value & 1127) != 0) sbuf.append("|msoLanguageIDFulfulde");
      if ((value & 1084) != 0) sbuf.append("|msoLanguageIDGaelicScotland");
      if ((value & 1110) != 0) sbuf.append("|msoLanguageIDGalician");
      if ((value & 1079) != 0) sbuf.append("|msoLanguageIDGeorgian");
      if ((value & 3079) != 0) sbuf.append("|msoLanguageIDGermanAustria");
      if ((value & 1031) != 0) sbuf.append("|msoLanguageIDGerman");
      if ((value & 5127) != 0) sbuf.append("|msoLanguageIDGermanLiechtenstein");
      if ((value & 4103) != 0) sbuf.append("|msoLanguageIDGermanLuxembourg");
      if ((value & 2055) != 0) sbuf.append("|msoLanguageIDSwissGerman");
      if ((value & 1128) != 0) sbuf.append("|msoLanguageIDHausa");
      if ((value & 1032) != 0) sbuf.append("|msoLanguageIDGreek");
      if ((value & 1140) != 0) sbuf.append("|msoLanguageIDGuarani");
      if ((value & 1141) != 0) sbuf.append("|msoLanguageIDHawaiian");
      if ((value & 1037) != 0) sbuf.append("|msoLanguageIDHebrew");
      if ((value & 1081) != 0) sbuf.append("|msoLanguageIDHindi");
      if ((value & 2163) != 0) sbuf.append("|msoLanguageIDTigrignaEritrea");
      if ((value & 1057) != 0) sbuf.append("|msoLanguageIDIndonesian");
      if ((value & 1117) != 0) sbuf.append("|msoLanguageIDInuktitut");
      if ((value & 1040) != 0) sbuf.append("|msoLanguageIDItalian");
      if ((value & 2064) != 0) sbuf.append("|msoLanguageIDSwissItalian");
      if ((value & 6154) != 0) sbuf.append("|msoLanguageIDSpanishPanama");
      if ((value & 1041) != 0) sbuf.append("|msoLanguageIDJapanese");
      if ((value & 1099) != 0) sbuf.append("|msoLanguageIDKannada");
      if ((value & 1120) != 0) sbuf.append("|msoLanguageIDKashmiri");
      if ((value & 2144) != 0) sbuf.append("|msoLanguageIDKashmiriDevanagari");
      if ((value & 1107) != 0) sbuf.append("|msoLanguageIDKhmer");
      if ((value & 1088) != 0) sbuf.append("|msoLanguageIDKirghiz");
      if ((value & 1111) != 0) sbuf.append("|msoLanguageIDKonkani");
      if ((value & 1042) != 0) sbuf.append("|msoLanguageIDKorean");
      if ((value & 1142) != 0) sbuf.append("|msoLanguageIDLatin");
      if ((value & 1108) != 0) sbuf.append("|msoLanguageIDLao");
      if ((value & 1062) != 0) sbuf.append("|msoLanguageIDLatvian");
      if ((value & 1071) != 0) sbuf.append("|msoLanguageIDMacedonian");
      if ((value & 1073) != 0) sbuf.append("|msoLanguageIDTsonga");
      if ((value & 2110) != 0) sbuf.append("|msoLanguageIDMalayBruneiDarussalam");
      if ((value & 1100) != 0) sbuf.append("|msoLanguageIDMalayalam");
      if ((value & 1082) != 0) sbuf.append("|msoLanguageIDMaltese");
      if ((value & 1112) != 0) sbuf.append("|msoLanguageIDManipuri");
      if ((value & 1153) != 0) sbuf.append("|msoLanguageIDMaori");
      if ((value & 1102) != 0) sbuf.append("|msoLanguageIDMarathi");
      if ((value & 2068) != 0) sbuf.append("|msoLanguageIDNorwegianNynorsk");
      if ((value & 1045) != 0) sbuf.append("|msoLanguageIDPolish");
      if ((value & 1046) != 0) sbuf.append("|msoLanguageIDBrazilianPortuguese");
      if ((value & 2070) != 0) sbuf.append("|msoLanguageIDPortuguese");
      if ((value & 15370) != 0) sbuf.append("|msoLanguageIDSpanishParaguay");
      if ((value & 2058) != 0) sbuf.append("|msoLanguageIDMexicanSpanish");
      if ((value & 1094) != 0) sbuf.append("|msoLanguageIDPunjabi");
      if ((value & 1131) != 0) sbuf.append("|msoLanguageIDQuechuaBolivia");
      if ((value & 2155) != 0) sbuf.append("|msoLanguageIDQuechuaEcuador");
      if ((value & 1049) != 0) sbuf.append("|msoLanguageIDRussian");
      if ((value & 3179) != 0) sbuf.append("|msoLanguageIDQuechuaPeru");
      if ((value & 1047) != 0) sbuf.append("|msoLanguageIDRhaetoRomanic");
      if ((value & 1048) != 0) sbuf.append("|msoLanguageIDRomanian");
      if ((value & 2073) != 0) sbuf.append("|msoLanguageIDRussianMoldova");
      if ((value & 1083) != 0) sbuf.append("|msoLanguageIDSamiLappish");
      if ((value & 1103) != 0) sbuf.append("|msoLanguageIDSanskrit");
      if ((value & 1132) != 0) sbuf.append("|msoLanguageIDSepedi");
      if ((value & 7194) != 0) sbuf.append("|msoLanguageIDSerbianBosniaHerzegovinaCyrillic");
      if ((value & 6170) != 0) sbuf.append("|msoLanguageIDSerbianBosniaHerzegovinaLatin");
      if ((value & 3098) != 0) sbuf.append("|msoLanguageIDSerbianCyrillic");
      if ((value & 2074) != 0) sbuf.append("|msoLanguageIDSerbianLatin");
      if ((value & 1072) != 0) sbuf.append("|msoLanguageIDSesotho");
      if ((value & 2137) != 0) sbuf.append("|msoLanguageIDSindhiPakistan");
      if ((value & 1115) != 0) sbuf.append("|msoLanguageIDSinhalese");
      if ((value & 1051) != 0) sbuf.append("|msoLanguageIDSlovak");
      if ((value & 1143) != 0) sbuf.append("|msoLanguageIDSomali");
      if ((value & 1070) != 0) sbuf.append("|msoLanguageIDSorbian");
      if ((value & 16394) != 0) sbuf.append("|msoLanguageIDSpanishBolivia");
      if ((value & 13322) != 0) sbuf.append("|msoLanguageIDSpanishChile");
      if ((value & 9226) != 0) sbuf.append("|msoLanguageIDSpanishColombia");
      if ((value & 7178) != 0) sbuf.append("|msoLanguageIDSpanishDominicanRepublic");
      if ((value & 12298) != 0) sbuf.append("|msoLanguageIDSpanishEcuador");
      if ((value & 18442) != 0) sbuf.append("|msoLanguageIDSpanishHonduras");
      if ((value & 19466) != 0) sbuf.append("|msoLanguageIDSpanishNicaragua");
      if ((value & 10250) != 0) sbuf.append("|msoLanguageIDSpanishPeru");
      if ((value & 20490) != 0) sbuf.append("|msoLanguageIDSpanishPuertoRico");
      if ((value & 3082) != 0) sbuf.append("|msoLanguageIDSpanishModernSort");
      if ((value & 1034) != 0) sbuf.append("|msoLanguageIDSpanish");
      if ((value & 14346) != 0) sbuf.append("|msoLanguageIDSpanishUruguay");
      if ((value & 8202) != 0) sbuf.append("|msoLanguageIDSpanishVenezuela");
      if ((value & 1089) != 0) sbuf.append("|msoLanguageIDSwahili");
      if ((value & 2077) != 0) sbuf.append("|msoLanguageIDSwedishFinland");
      if ((value & 1053) != 0) sbuf.append("|msoLanguageIDSwedish");
      if ((value & 1064) != 0) sbuf.append("|msoLanguageIDTajik");
      if ((value & 1119) != 0) sbuf.append("|msoLanguageIDTamazight");
      if ((value & 2143) != 0) sbuf.append("|msoLanguageIDTamazightLatin");
      if ((value & 1098) != 0) sbuf.append("|msoLanguageIDTelugu");
      if ((value & 1054) != 0) sbuf.append("|msoLanguageIDThai");
      if ((value & 1105) != 0) sbuf.append("|msoLanguageIDTibetan");
      if ((value & 1055) != 0) sbuf.append("|msoLanguageIDTurkish");
      if ((value & 1090) != 0) sbuf.append("|msoLanguageIDTurkmen");
      if ((value & 1058) != 0) sbuf.append("|msoLanguageIDUkrainian");
      if ((value & 1056) != 0) sbuf.append("|msoLanguageIDUrdu");
      if ((value & 1076) != 0) sbuf.append("|msoLanguageIDXhosa");
      if ((value & 2115) != 0) sbuf.append("|msoLanguageIDUzbekCyrillic");
      if ((value & 1091) != 0) sbuf.append("|msoLanguageIDUzbekLatin");
      if ((value & 1075) != 0) sbuf.append("|msoLanguageIDVenda");
      if ((value & 1106) != 0) sbuf.append("|msoLanguageIDWelsh");
      if ((value & 1144) != 0) sbuf.append("|msoLanguageIDYi");
      if ((value & 1130) != 0) sbuf.append("|msoLanguageIDYoruba");
      if ((value & 1077) != 0) sbuf.append("|msoLanguageIDZulu");
      return sbuf.toString();
      }
    }
  }
}
