/* ** GENEREATED FILE - DO NOT MODIFY ** */
package com.wilutions.mslib.office;
import com.wilutions.com.*;

/**
 * MsoLanguageID.
 * 
 */
@SuppressWarnings("all")
@CoInterface(guid="{00000000-0000-0000-0000-000000000000}")
public class MsoLanguageID {
  static boolean __typelib__loaded = __TypeLib.load();

  // Typed constants
  public final static MsoLanguageID msoLanguageIDMixed = new MsoLanguageID(-2);
  public final static MsoLanguageID msoLanguageIDNone = new MsoLanguageID(0);
  public final static MsoLanguageID msoLanguageIDNoProofing = new MsoLanguageID(1024);
  public final static MsoLanguageID msoLanguageIDAfrikaans = new MsoLanguageID(1078);
  public final static MsoLanguageID msoLanguageIDAlbanian = new MsoLanguageID(1052);
  public final static MsoLanguageID msoLanguageIDAmharic = new MsoLanguageID(1118);
  public final static MsoLanguageID msoLanguageIDArabicAlgeria = new MsoLanguageID(5121);
  public final static MsoLanguageID msoLanguageIDArabicBahrain = new MsoLanguageID(15361);
  public final static MsoLanguageID msoLanguageIDArabicEgypt = new MsoLanguageID(3073);
  public final static MsoLanguageID msoLanguageIDArabicIraq = new MsoLanguageID(2049);
  public final static MsoLanguageID msoLanguageIDArabicJordan = new MsoLanguageID(11265);
  public final static MsoLanguageID msoLanguageIDArabicKuwait = new MsoLanguageID(13313);
  public final static MsoLanguageID msoLanguageIDArabicLebanon = new MsoLanguageID(12289);
  public final static MsoLanguageID msoLanguageIDArabicLibya = new MsoLanguageID(4097);
  public final static MsoLanguageID msoLanguageIDArabicMorocco = new MsoLanguageID(6145);
  public final static MsoLanguageID msoLanguageIDArabicOman = new MsoLanguageID(8193);
  public final static MsoLanguageID msoLanguageIDArabicQatar = new MsoLanguageID(16385);
  public final static MsoLanguageID msoLanguageIDArabic = new MsoLanguageID(1025);
  public final static MsoLanguageID msoLanguageIDArabicSyria = new MsoLanguageID(10241);
  public final static MsoLanguageID msoLanguageIDArabicTunisia = new MsoLanguageID(7169);
  public final static MsoLanguageID msoLanguageIDArabicUAE = new MsoLanguageID(14337);
  public final static MsoLanguageID msoLanguageIDArabicYemen = new MsoLanguageID(9217);
  public final static MsoLanguageID msoLanguageIDArmenian = new MsoLanguageID(1067);
  public final static MsoLanguageID msoLanguageIDAssamese = new MsoLanguageID(1101);
  public final static MsoLanguageID msoLanguageIDAzeriCyrillic = new MsoLanguageID(2092);
  public final static MsoLanguageID msoLanguageIDAzeriLatin = new MsoLanguageID(1068);
  public final static MsoLanguageID msoLanguageIDBasque = new MsoLanguageID(1069);
  public final static MsoLanguageID msoLanguageIDByelorussian = new MsoLanguageID(1059);
  public final static MsoLanguageID msoLanguageIDBengali = new MsoLanguageID(1093);
  public final static MsoLanguageID msoLanguageIDBosnian = new MsoLanguageID(4122);
  public final static MsoLanguageID msoLanguageIDBosnianBosniaHerzegovinaCyrillic = new MsoLanguageID(8218);
  public final static MsoLanguageID msoLanguageIDBosnianBosniaHerzegovinaLatin = new MsoLanguageID(5146);
  public final static MsoLanguageID msoLanguageIDBulgarian = new MsoLanguageID(1026);
  public final static MsoLanguageID msoLanguageIDBurmese = new MsoLanguageID(1109);
  public final static MsoLanguageID msoLanguageIDCatalan = new MsoLanguageID(1027);
  public final static MsoLanguageID msoLanguageIDChineseHongKongSAR = new MsoLanguageID(3076);
  public final static MsoLanguageID msoLanguageIDChineseMacaoSAR = new MsoLanguageID(5124);
  public final static MsoLanguageID msoLanguageIDSimplifiedChinese = new MsoLanguageID(2052);
  public final static MsoLanguageID msoLanguageIDChineseSingapore = new MsoLanguageID(4100);
  public final static MsoLanguageID msoLanguageIDTraditionalChinese = new MsoLanguageID(1028);
  public final static MsoLanguageID msoLanguageIDCherokee = new MsoLanguageID(1116);
  public final static MsoLanguageID msoLanguageIDCroatian = new MsoLanguageID(1050);
  public final static MsoLanguageID msoLanguageIDCzech = new MsoLanguageID(1029);
  public final static MsoLanguageID msoLanguageIDDanish = new MsoLanguageID(1030);
  public final static MsoLanguageID msoLanguageIDDivehi = new MsoLanguageID(1125);
  public final static MsoLanguageID msoLanguageIDBelgianDutch = new MsoLanguageID(2067);
  public final static MsoLanguageID msoLanguageIDDutch = new MsoLanguageID(1043);
  public final static MsoLanguageID msoLanguageIDDzongkhaBhutan = new MsoLanguageID(2129);
  public final static MsoLanguageID msoLanguageIDEdo = new MsoLanguageID(1126);
  public final static MsoLanguageID msoLanguageIDEnglishAUS = new MsoLanguageID(3081);
  public final static MsoLanguageID msoLanguageIDEnglishBelize = new MsoLanguageID(10249);
  public final static MsoLanguageID msoLanguageIDEnglishCanadian = new MsoLanguageID(4105);
  public final static MsoLanguageID msoLanguageIDEnglishCaribbean = new MsoLanguageID(9225);
  public final static MsoLanguageID msoLanguageIDEnglishIndonesia = new MsoLanguageID(14345);
  public final static MsoLanguageID msoLanguageIDEnglishIreland = new MsoLanguageID(6153);
  public final static MsoLanguageID msoLanguageIDEnglishJamaica = new MsoLanguageID(8201);
  public final static MsoLanguageID msoLanguageIDEnglishNewZealand = new MsoLanguageID(5129);
  public final static MsoLanguageID msoLanguageIDEnglishPhilippines = new MsoLanguageID(13321);
  public final static MsoLanguageID msoLanguageIDEnglishSouthAfrica = new MsoLanguageID(7177);
  public final static MsoLanguageID msoLanguageIDEnglishTrinidadTobago = new MsoLanguageID(11273);
  public final static MsoLanguageID msoLanguageIDEnglishUK = new MsoLanguageID(2057);
  public final static MsoLanguageID msoLanguageIDEnglishUS = new MsoLanguageID(1033);
  public final static MsoLanguageID msoLanguageIDEnglishZimbabwe = new MsoLanguageID(12297);
  public final static MsoLanguageID msoLanguageIDEstonian = new MsoLanguageID(1061);
  public final static MsoLanguageID msoLanguageIDFaeroese = new MsoLanguageID(1080);
  public final static MsoLanguageID msoLanguageIDFarsi = new MsoLanguageID(1065);
  public final static MsoLanguageID msoLanguageIDFilipino = new MsoLanguageID(1124);
  public final static MsoLanguageID msoLanguageIDFinnish = new MsoLanguageID(1035);
  public final static MsoLanguageID msoLanguageIDBelgianFrench = new MsoLanguageID(2060);
  public final static MsoLanguageID msoLanguageIDFrenchCameroon = new MsoLanguageID(11276);
  public final static MsoLanguageID msoLanguageIDFrenchCanadian = new MsoLanguageID(3084);
  public final static MsoLanguageID msoLanguageIDFrenchCotedIvoire = new MsoLanguageID(12300);
  public final static MsoLanguageID msoLanguageIDFrench = new MsoLanguageID(1036);
  public final static MsoLanguageID msoLanguageIDFrenchHaiti = new MsoLanguageID(15372);
  public final static MsoLanguageID msoLanguageIDFrenchLuxembourg = new MsoLanguageID(5132);
  public final static MsoLanguageID msoLanguageIDFrenchMali = new MsoLanguageID(13324);
  public final static MsoLanguageID msoLanguageIDFrenchMonaco = new MsoLanguageID(6156);
  public final static MsoLanguageID msoLanguageIDFrenchMorocco = new MsoLanguageID(14348);
  public final static MsoLanguageID msoLanguageIDFrenchReunion = new MsoLanguageID(8204);
  public final static MsoLanguageID msoLanguageIDFrenchSenegal = new MsoLanguageID(10252);
  public final static MsoLanguageID msoLanguageIDSwissFrench = new MsoLanguageID(4108);
  public final static MsoLanguageID msoLanguageIDFrenchWestIndies = new MsoLanguageID(7180);
  public final static MsoLanguageID msoLanguageIDFrenchZaire = new MsoLanguageID(9228);
  public final static MsoLanguageID msoLanguageIDFrenchCongoDRC = new MsoLanguageID(9228);
  public final static MsoLanguageID msoLanguageIDFrisianNetherlands = new MsoLanguageID(1122);
  public final static MsoLanguageID msoLanguageIDFulfulde = new MsoLanguageID(1127);
  public final static MsoLanguageID msoLanguageIDGaelicIreland = new MsoLanguageID(2108);
  public final static MsoLanguageID msoLanguageIDGaelicScotland = new MsoLanguageID(1084);
  public final static MsoLanguageID msoLanguageIDGalician = new MsoLanguageID(1110);
  public final static MsoLanguageID msoLanguageIDGeorgian = new MsoLanguageID(1079);
  public final static MsoLanguageID msoLanguageIDGermanAustria = new MsoLanguageID(3079);
  public final static MsoLanguageID msoLanguageIDGerman = new MsoLanguageID(1031);
  public final static MsoLanguageID msoLanguageIDGermanLiechtenstein = new MsoLanguageID(5127);
  public final static MsoLanguageID msoLanguageIDGermanLuxembourg = new MsoLanguageID(4103);
  public final static MsoLanguageID msoLanguageIDSwissGerman = new MsoLanguageID(2055);
  public final static MsoLanguageID msoLanguageIDGreek = new MsoLanguageID(1032);
  public final static MsoLanguageID msoLanguageIDGuarani = new MsoLanguageID(1140);
  public final static MsoLanguageID msoLanguageIDGujarati = new MsoLanguageID(1095);
  public final static MsoLanguageID msoLanguageIDHausa = new MsoLanguageID(1128);
  public final static MsoLanguageID msoLanguageIDHawaiian = new MsoLanguageID(1141);
  public final static MsoLanguageID msoLanguageIDHebrew = new MsoLanguageID(1037);
  public final static MsoLanguageID msoLanguageIDHindi = new MsoLanguageID(1081);
  public final static MsoLanguageID msoLanguageIDHungarian = new MsoLanguageID(1038);
  public final static MsoLanguageID msoLanguageIDIbibio = new MsoLanguageID(1129);
  public final static MsoLanguageID msoLanguageIDIcelandic = new MsoLanguageID(1039);
  public final static MsoLanguageID msoLanguageIDIgbo = new MsoLanguageID(1136);
  public final static MsoLanguageID msoLanguageIDIndonesian = new MsoLanguageID(1057);
  public final static MsoLanguageID msoLanguageIDInuktitut = new MsoLanguageID(1117);
  public final static MsoLanguageID msoLanguageIDItalian = new MsoLanguageID(1040);
  public final static MsoLanguageID msoLanguageIDSwissItalian = new MsoLanguageID(2064);
  public final static MsoLanguageID msoLanguageIDJapanese = new MsoLanguageID(1041);
  public final static MsoLanguageID msoLanguageIDKannada = new MsoLanguageID(1099);
  public final static MsoLanguageID msoLanguageIDKanuri = new MsoLanguageID(1137);
  public final static MsoLanguageID msoLanguageIDKashmiri = new MsoLanguageID(1120);
  public final static MsoLanguageID msoLanguageIDKashmiriDevanagari = new MsoLanguageID(2144);
  public final static MsoLanguageID msoLanguageIDKazakh = new MsoLanguageID(1087);
  public final static MsoLanguageID msoLanguageIDKhmer = new MsoLanguageID(1107);
  public final static MsoLanguageID msoLanguageIDKirghiz = new MsoLanguageID(1088);
  public final static MsoLanguageID msoLanguageIDKonkani = new MsoLanguageID(1111);
  public final static MsoLanguageID msoLanguageIDKorean = new MsoLanguageID(1042);
  public final static MsoLanguageID msoLanguageIDKyrgyz = new MsoLanguageID(1088);
  public final static MsoLanguageID msoLanguageIDLatin = new MsoLanguageID(1142);
  public final static MsoLanguageID msoLanguageIDLao = new MsoLanguageID(1108);
  public final static MsoLanguageID msoLanguageIDLatvian = new MsoLanguageID(1062);
  public final static MsoLanguageID msoLanguageIDLithuanian = new MsoLanguageID(1063);
  public final static MsoLanguageID msoLanguageIDMacedonian = new MsoLanguageID(1071);
  public final static MsoLanguageID msoLanguageIDMacedonianFYROM = new MsoLanguageID(1071);
  public final static MsoLanguageID msoLanguageIDMalaysian = new MsoLanguageID(1086);
  public final static MsoLanguageID msoLanguageIDMalayBruneiDarussalam = new MsoLanguageID(2110);
  public final static MsoLanguageID msoLanguageIDMalayalam = new MsoLanguageID(1100);
  public final static MsoLanguageID msoLanguageIDMaltese = new MsoLanguageID(1082);
  public final static MsoLanguageID msoLanguageIDManipuri = new MsoLanguageID(1112);
  public final static MsoLanguageID msoLanguageIDMaori = new MsoLanguageID(1153);
  public final static MsoLanguageID msoLanguageIDMarathi = new MsoLanguageID(1102);
  public final static MsoLanguageID msoLanguageIDMongolian = new MsoLanguageID(1104);
  public final static MsoLanguageID msoLanguageIDNepali = new MsoLanguageID(1121);
  public final static MsoLanguageID msoLanguageIDNorwegianBokmol = new MsoLanguageID(1044);
  public final static MsoLanguageID msoLanguageIDNorwegianNynorsk = new MsoLanguageID(2068);
  public final static MsoLanguageID msoLanguageIDOriya = new MsoLanguageID(1096);
  public final static MsoLanguageID msoLanguageIDOromo = new MsoLanguageID(1138);
  public final static MsoLanguageID msoLanguageIDPashto = new MsoLanguageID(1123);
  public final static MsoLanguageID msoLanguageIDPolish = new MsoLanguageID(1045);
  public final static MsoLanguageID msoLanguageIDBrazilianPortuguese = new MsoLanguageID(1046);
  public final static MsoLanguageID msoLanguageIDPortuguese = new MsoLanguageID(2070);
  public final static MsoLanguageID msoLanguageIDPunjabi = new MsoLanguageID(1094);
  public final static MsoLanguageID msoLanguageIDQuechuaBolivia = new MsoLanguageID(1131);
  public final static MsoLanguageID msoLanguageIDQuechuaEcuador = new MsoLanguageID(2155);
  public final static MsoLanguageID msoLanguageIDQuechuaPeru = new MsoLanguageID(3179);
  public final static MsoLanguageID msoLanguageIDRhaetoRomanic = new MsoLanguageID(1047);
  public final static MsoLanguageID msoLanguageIDRomanianMoldova = new MsoLanguageID(2072);
  public final static MsoLanguageID msoLanguageIDRomanian = new MsoLanguageID(1048);
  public final static MsoLanguageID msoLanguageIDRussianMoldova = new MsoLanguageID(2073);
  public final static MsoLanguageID msoLanguageIDRussian = new MsoLanguageID(1049);
  public final static MsoLanguageID msoLanguageIDSamiLappish = new MsoLanguageID(1083);
  public final static MsoLanguageID msoLanguageIDSanskrit = new MsoLanguageID(1103);
  public final static MsoLanguageID msoLanguageIDSepedi = new MsoLanguageID(1132);
  public final static MsoLanguageID msoLanguageIDSerbianBosniaHerzegovinaCyrillic = new MsoLanguageID(7194);
  public final static MsoLanguageID msoLanguageIDSerbianBosniaHerzegovinaLatin = new MsoLanguageID(6170);
  public final static MsoLanguageID msoLanguageIDSerbianCyrillic = new MsoLanguageID(3098);
  public final static MsoLanguageID msoLanguageIDSerbianLatin = new MsoLanguageID(2074);
  public final static MsoLanguageID msoLanguageIDSesotho = new MsoLanguageID(1072);
  public final static MsoLanguageID msoLanguageIDSindhi = new MsoLanguageID(1113);
  public final static MsoLanguageID msoLanguageIDSindhiPakistan = new MsoLanguageID(2137);
  public final static MsoLanguageID msoLanguageIDSinhalese = new MsoLanguageID(1115);
  public final static MsoLanguageID msoLanguageIDSlovak = new MsoLanguageID(1051);
  public final static MsoLanguageID msoLanguageIDSlovenian = new MsoLanguageID(1060);
  public final static MsoLanguageID msoLanguageIDSomali = new MsoLanguageID(1143);
  public final static MsoLanguageID msoLanguageIDSorbian = new MsoLanguageID(1070);
  public final static MsoLanguageID msoLanguageIDSpanishArgentina = new MsoLanguageID(11274);
  public final static MsoLanguageID msoLanguageIDSpanishBolivia = new MsoLanguageID(16394);
  public final static MsoLanguageID msoLanguageIDSpanishChile = new MsoLanguageID(13322);
  public final static MsoLanguageID msoLanguageIDSpanishColombia = new MsoLanguageID(9226);
  public final static MsoLanguageID msoLanguageIDSpanishCostaRica = new MsoLanguageID(5130);
  public final static MsoLanguageID msoLanguageIDSpanishDominicanRepublic = new MsoLanguageID(7178);
  public final static MsoLanguageID msoLanguageIDSpanishEcuador = new MsoLanguageID(12298);
  public final static MsoLanguageID msoLanguageIDSpanishElSalvador = new MsoLanguageID(17418);
  public final static MsoLanguageID msoLanguageIDSpanishGuatemala = new MsoLanguageID(4106);
  public final static MsoLanguageID msoLanguageIDSpanishHonduras = new MsoLanguageID(18442);
  public final static MsoLanguageID msoLanguageIDMexicanSpanish = new MsoLanguageID(2058);
  public final static MsoLanguageID msoLanguageIDSpanishNicaragua = new MsoLanguageID(19466);
  public final static MsoLanguageID msoLanguageIDSpanishPanama = new MsoLanguageID(6154);
  public final static MsoLanguageID msoLanguageIDSpanishParaguay = new MsoLanguageID(15370);
  public final static MsoLanguageID msoLanguageIDSpanishPeru = new MsoLanguageID(10250);
  public final static MsoLanguageID msoLanguageIDSpanishPuertoRico = new MsoLanguageID(20490);
  public final static MsoLanguageID msoLanguageIDSpanishModernSort = new MsoLanguageID(3082);
  public final static MsoLanguageID msoLanguageIDSpanish = new MsoLanguageID(1034);
  public final static MsoLanguageID msoLanguageIDSpanishUruguay = new MsoLanguageID(14346);
  public final static MsoLanguageID msoLanguageIDSpanishVenezuela = new MsoLanguageID(8202);
  public final static MsoLanguageID msoLanguageIDSutu = new MsoLanguageID(1072);
  public final static MsoLanguageID msoLanguageIDSwahili = new MsoLanguageID(1089);
  public final static MsoLanguageID msoLanguageIDSwedishFinland = new MsoLanguageID(2077);
  public final static MsoLanguageID msoLanguageIDSwedish = new MsoLanguageID(1053);
  public final static MsoLanguageID msoLanguageIDSyriac = new MsoLanguageID(1114);
  public final static MsoLanguageID msoLanguageIDTajik = new MsoLanguageID(1064);
  public final static MsoLanguageID msoLanguageIDTamil = new MsoLanguageID(1097);
  public final static MsoLanguageID msoLanguageIDTamazight = new MsoLanguageID(1119);
  public final static MsoLanguageID msoLanguageIDTamazightLatin = new MsoLanguageID(2143);
  public final static MsoLanguageID msoLanguageIDTatar = new MsoLanguageID(1092);
  public final static MsoLanguageID msoLanguageIDTelugu = new MsoLanguageID(1098);
  public final static MsoLanguageID msoLanguageIDThai = new MsoLanguageID(1054);
  public final static MsoLanguageID msoLanguageIDTibetan = new MsoLanguageID(1105);
  public final static MsoLanguageID msoLanguageIDTigrignaEthiopic = new MsoLanguageID(1139);
  public final static MsoLanguageID msoLanguageIDTigrignaEritrea = new MsoLanguageID(2163);
  public final static MsoLanguageID msoLanguageIDTsonga = new MsoLanguageID(1073);
  public final static MsoLanguageID msoLanguageIDTswana = new MsoLanguageID(1074);
  public final static MsoLanguageID msoLanguageIDTurkish = new MsoLanguageID(1055);
  public final static MsoLanguageID msoLanguageIDTurkmen = new MsoLanguageID(1090);
  public final static MsoLanguageID msoLanguageIDUkrainian = new MsoLanguageID(1058);
  public final static MsoLanguageID msoLanguageIDUrdu = new MsoLanguageID(1056);
  public final static MsoLanguageID msoLanguageIDUzbekCyrillic = new MsoLanguageID(2115);
  public final static MsoLanguageID msoLanguageIDUzbekLatin = new MsoLanguageID(1091);
  public final static MsoLanguageID msoLanguageIDVenda = new MsoLanguageID(1075);
  public final static MsoLanguageID msoLanguageIDVietnamese = new MsoLanguageID(1066);
  public final static MsoLanguageID msoLanguageIDWelsh = new MsoLanguageID(1106);
  public final static MsoLanguageID msoLanguageIDXhosa = new MsoLanguageID(1076);
  public final static MsoLanguageID msoLanguageIDYi = new MsoLanguageID(1144);
  public final static MsoLanguageID msoLanguageIDYiddish = new MsoLanguageID(1085);
  public final static MsoLanguageID msoLanguageIDYoruba = new MsoLanguageID(1130);
  public final static MsoLanguageID msoLanguageIDZulu = new MsoLanguageID(1077);

  // Integer constants for bitsets and switch statements
  public final static int _msoLanguageIDMixed = -2;
  public final static int _msoLanguageIDNone = 0;
  public final static int _msoLanguageIDNoProofing = 1024;
  public final static int _msoLanguageIDAfrikaans = 1078;
  public final static int _msoLanguageIDAlbanian = 1052;
  public final static int _msoLanguageIDAmharic = 1118;
  public final static int _msoLanguageIDArabicAlgeria = 5121;
  public final static int _msoLanguageIDArabicBahrain = 15361;
  public final static int _msoLanguageIDArabicEgypt = 3073;
  public final static int _msoLanguageIDArabicIraq = 2049;
  public final static int _msoLanguageIDArabicJordan = 11265;
  public final static int _msoLanguageIDArabicKuwait = 13313;
  public final static int _msoLanguageIDArabicLebanon = 12289;
  public final static int _msoLanguageIDArabicLibya = 4097;
  public final static int _msoLanguageIDArabicMorocco = 6145;
  public final static int _msoLanguageIDArabicOman = 8193;
  public final static int _msoLanguageIDArabicQatar = 16385;
  public final static int _msoLanguageIDArabic = 1025;
  public final static int _msoLanguageIDArabicSyria = 10241;
  public final static int _msoLanguageIDArabicTunisia = 7169;
  public final static int _msoLanguageIDArabicUAE = 14337;
  public final static int _msoLanguageIDArabicYemen = 9217;
  public final static int _msoLanguageIDArmenian = 1067;
  public final static int _msoLanguageIDAssamese = 1101;
  public final static int _msoLanguageIDAzeriCyrillic = 2092;
  public final static int _msoLanguageIDAzeriLatin = 1068;
  public final static int _msoLanguageIDBasque = 1069;
  public final static int _msoLanguageIDByelorussian = 1059;
  public final static int _msoLanguageIDBengali = 1093;
  public final static int _msoLanguageIDBosnian = 4122;
  public final static int _msoLanguageIDBosnianBosniaHerzegovinaCyrillic = 8218;
  public final static int _msoLanguageIDBosnianBosniaHerzegovinaLatin = 5146;
  public final static int _msoLanguageIDBulgarian = 1026;
  public final static int _msoLanguageIDBurmese = 1109;
  public final static int _msoLanguageIDCatalan = 1027;
  public final static int _msoLanguageIDChineseHongKongSAR = 3076;
  public final static int _msoLanguageIDChineseMacaoSAR = 5124;
  public final static int _msoLanguageIDSimplifiedChinese = 2052;
  public final static int _msoLanguageIDChineseSingapore = 4100;
  public final static int _msoLanguageIDTraditionalChinese = 1028;
  public final static int _msoLanguageIDCherokee = 1116;
  public final static int _msoLanguageIDCroatian = 1050;
  public final static int _msoLanguageIDCzech = 1029;
  public final static int _msoLanguageIDDanish = 1030;
  public final static int _msoLanguageIDDivehi = 1125;
  public final static int _msoLanguageIDBelgianDutch = 2067;
  public final static int _msoLanguageIDDutch = 1043;
  public final static int _msoLanguageIDDzongkhaBhutan = 2129;
  public final static int _msoLanguageIDEdo = 1126;
  public final static int _msoLanguageIDEnglishAUS = 3081;
  public final static int _msoLanguageIDEnglishBelize = 10249;
  public final static int _msoLanguageIDEnglishCanadian = 4105;
  public final static int _msoLanguageIDEnglishCaribbean = 9225;
  public final static int _msoLanguageIDEnglishIndonesia = 14345;
  public final static int _msoLanguageIDEnglishIreland = 6153;
  public final static int _msoLanguageIDEnglishJamaica = 8201;
  public final static int _msoLanguageIDEnglishNewZealand = 5129;
  public final static int _msoLanguageIDEnglishPhilippines = 13321;
  public final static int _msoLanguageIDEnglishSouthAfrica = 7177;
  public final static int _msoLanguageIDEnglishTrinidadTobago = 11273;
  public final static int _msoLanguageIDEnglishUK = 2057;
  public final static int _msoLanguageIDEnglishUS = 1033;
  public final static int _msoLanguageIDEnglishZimbabwe = 12297;
  public final static int _msoLanguageIDEstonian = 1061;
  public final static int _msoLanguageIDFaeroese = 1080;
  public final static int _msoLanguageIDFarsi = 1065;
  public final static int _msoLanguageIDFilipino = 1124;
  public final static int _msoLanguageIDFinnish = 1035;
  public final static int _msoLanguageIDBelgianFrench = 2060;
  public final static int _msoLanguageIDFrenchCameroon = 11276;
  public final static int _msoLanguageIDFrenchCanadian = 3084;
  public final static int _msoLanguageIDFrenchCotedIvoire = 12300;
  public final static int _msoLanguageIDFrench = 1036;
  public final static int _msoLanguageIDFrenchHaiti = 15372;
  public final static int _msoLanguageIDFrenchLuxembourg = 5132;
  public final static int _msoLanguageIDFrenchMali = 13324;
  public final static int _msoLanguageIDFrenchMonaco = 6156;
  public final static int _msoLanguageIDFrenchMorocco = 14348;
  public final static int _msoLanguageIDFrenchReunion = 8204;
  public final static int _msoLanguageIDFrenchSenegal = 10252;
  public final static int _msoLanguageIDSwissFrench = 4108;
  public final static int _msoLanguageIDFrenchWestIndies = 7180;
  public final static int _msoLanguageIDFrenchZaire = 9228;
  public final static int _msoLanguageIDFrenchCongoDRC = 9228;
  public final static int _msoLanguageIDFrisianNetherlands = 1122;
  public final static int _msoLanguageIDFulfulde = 1127;
  public final static int _msoLanguageIDGaelicIreland = 2108;
  public final static int _msoLanguageIDGaelicScotland = 1084;
  public final static int _msoLanguageIDGalician = 1110;
  public final static int _msoLanguageIDGeorgian = 1079;
  public final static int _msoLanguageIDGermanAustria = 3079;
  public final static int _msoLanguageIDGerman = 1031;
  public final static int _msoLanguageIDGermanLiechtenstein = 5127;
  public final static int _msoLanguageIDGermanLuxembourg = 4103;
  public final static int _msoLanguageIDSwissGerman = 2055;
  public final static int _msoLanguageIDGreek = 1032;
  public final static int _msoLanguageIDGuarani = 1140;
  public final static int _msoLanguageIDGujarati = 1095;
  public final static int _msoLanguageIDHausa = 1128;
  public final static int _msoLanguageIDHawaiian = 1141;
  public final static int _msoLanguageIDHebrew = 1037;
  public final static int _msoLanguageIDHindi = 1081;
  public final static int _msoLanguageIDHungarian = 1038;
  public final static int _msoLanguageIDIbibio = 1129;
  public final static int _msoLanguageIDIcelandic = 1039;
  public final static int _msoLanguageIDIgbo = 1136;
  public final static int _msoLanguageIDIndonesian = 1057;
  public final static int _msoLanguageIDInuktitut = 1117;
  public final static int _msoLanguageIDItalian = 1040;
  public final static int _msoLanguageIDSwissItalian = 2064;
  public final static int _msoLanguageIDJapanese = 1041;
  public final static int _msoLanguageIDKannada = 1099;
  public final static int _msoLanguageIDKanuri = 1137;
  public final static int _msoLanguageIDKashmiri = 1120;
  public final static int _msoLanguageIDKashmiriDevanagari = 2144;
  public final static int _msoLanguageIDKazakh = 1087;
  public final static int _msoLanguageIDKhmer = 1107;
  public final static int _msoLanguageIDKirghiz = 1088;
  public final static int _msoLanguageIDKonkani = 1111;
  public final static int _msoLanguageIDKorean = 1042;
  public final static int _msoLanguageIDKyrgyz = 1088;
  public final static int _msoLanguageIDLatin = 1142;
  public final static int _msoLanguageIDLao = 1108;
  public final static int _msoLanguageIDLatvian = 1062;
  public final static int _msoLanguageIDLithuanian = 1063;
  public final static int _msoLanguageIDMacedonian = 1071;
  public final static int _msoLanguageIDMacedonianFYROM = 1071;
  public final static int _msoLanguageIDMalaysian = 1086;
  public final static int _msoLanguageIDMalayBruneiDarussalam = 2110;
  public final static int _msoLanguageIDMalayalam = 1100;
  public final static int _msoLanguageIDMaltese = 1082;
  public final static int _msoLanguageIDManipuri = 1112;
  public final static int _msoLanguageIDMaori = 1153;
  public final static int _msoLanguageIDMarathi = 1102;
  public final static int _msoLanguageIDMongolian = 1104;
  public final static int _msoLanguageIDNepali = 1121;
  public final static int _msoLanguageIDNorwegianBokmol = 1044;
  public final static int _msoLanguageIDNorwegianNynorsk = 2068;
  public final static int _msoLanguageIDOriya = 1096;
  public final static int _msoLanguageIDOromo = 1138;
  public final static int _msoLanguageIDPashto = 1123;
  public final static int _msoLanguageIDPolish = 1045;
  public final static int _msoLanguageIDBrazilianPortuguese = 1046;
  public final static int _msoLanguageIDPortuguese = 2070;
  public final static int _msoLanguageIDPunjabi = 1094;
  public final static int _msoLanguageIDQuechuaBolivia = 1131;
  public final static int _msoLanguageIDQuechuaEcuador = 2155;
  public final static int _msoLanguageIDQuechuaPeru = 3179;
  public final static int _msoLanguageIDRhaetoRomanic = 1047;
  public final static int _msoLanguageIDRomanianMoldova = 2072;
  public final static int _msoLanguageIDRomanian = 1048;
  public final static int _msoLanguageIDRussianMoldova = 2073;
  public final static int _msoLanguageIDRussian = 1049;
  public final static int _msoLanguageIDSamiLappish = 1083;
  public final static int _msoLanguageIDSanskrit = 1103;
  public final static int _msoLanguageIDSepedi = 1132;
  public final static int _msoLanguageIDSerbianBosniaHerzegovinaCyrillic = 7194;
  public final static int _msoLanguageIDSerbianBosniaHerzegovinaLatin = 6170;
  public final static int _msoLanguageIDSerbianCyrillic = 3098;
  public final static int _msoLanguageIDSerbianLatin = 2074;
  public final static int _msoLanguageIDSesotho = 1072;
  public final static int _msoLanguageIDSindhi = 1113;
  public final static int _msoLanguageIDSindhiPakistan = 2137;
  public final static int _msoLanguageIDSinhalese = 1115;
  public final static int _msoLanguageIDSlovak = 1051;
  public final static int _msoLanguageIDSlovenian = 1060;
  public final static int _msoLanguageIDSomali = 1143;
  public final static int _msoLanguageIDSorbian = 1070;
  public final static int _msoLanguageIDSpanishArgentina = 11274;
  public final static int _msoLanguageIDSpanishBolivia = 16394;
  public final static int _msoLanguageIDSpanishChile = 13322;
  public final static int _msoLanguageIDSpanishColombia = 9226;
  public final static int _msoLanguageIDSpanishCostaRica = 5130;
  public final static int _msoLanguageIDSpanishDominicanRepublic = 7178;
  public final static int _msoLanguageIDSpanishEcuador = 12298;
  public final static int _msoLanguageIDSpanishElSalvador = 17418;
  public final static int _msoLanguageIDSpanishGuatemala = 4106;
  public final static int _msoLanguageIDSpanishHonduras = 18442;
  public final static int _msoLanguageIDMexicanSpanish = 2058;
  public final static int _msoLanguageIDSpanishNicaragua = 19466;
  public final static int _msoLanguageIDSpanishPanama = 6154;
  public final static int _msoLanguageIDSpanishParaguay = 15370;
  public final static int _msoLanguageIDSpanishPeru = 10250;
  public final static int _msoLanguageIDSpanishPuertoRico = 20490;
  public final static int _msoLanguageIDSpanishModernSort = 3082;
  public final static int _msoLanguageIDSpanish = 1034;
  public final static int _msoLanguageIDSpanishUruguay = 14346;
  public final static int _msoLanguageIDSpanishVenezuela = 8202;
  public final static int _msoLanguageIDSutu = 1072;
  public final static int _msoLanguageIDSwahili = 1089;
  public final static int _msoLanguageIDSwedishFinland = 2077;
  public final static int _msoLanguageIDSwedish = 1053;
  public final static int _msoLanguageIDSyriac = 1114;
  public final static int _msoLanguageIDTajik = 1064;
  public final static int _msoLanguageIDTamil = 1097;
  public final static int _msoLanguageIDTamazight = 1119;
  public final static int _msoLanguageIDTamazightLatin = 2143;
  public final static int _msoLanguageIDTatar = 1092;
  public final static int _msoLanguageIDTelugu = 1098;
  public final static int _msoLanguageIDThai = 1054;
  public final static int _msoLanguageIDTibetan = 1105;
  public final static int _msoLanguageIDTigrignaEthiopic = 1139;
  public final static int _msoLanguageIDTigrignaEritrea = 2163;
  public final static int _msoLanguageIDTsonga = 1073;
  public final static int _msoLanguageIDTswana = 1074;
  public final static int _msoLanguageIDTurkish = 1055;
  public final static int _msoLanguageIDTurkmen = 1090;
  public final static int _msoLanguageIDUkrainian = 1058;
  public final static int _msoLanguageIDUrdu = 1056;
  public final static int _msoLanguageIDUzbekCyrillic = 2115;
  public final static int _msoLanguageIDUzbekLatin = 1091;
  public final static int _msoLanguageIDVenda = 1075;
  public final static int _msoLanguageIDVietnamese = 1066;
  public final static int _msoLanguageIDWelsh = 1106;
  public final static int _msoLanguageIDXhosa = 1076;
  public final static int _msoLanguageIDYi = 1144;
  public final static int _msoLanguageIDYiddish = 1085;
  public final static int _msoLanguageIDYoruba = 1130;
  public final static int _msoLanguageIDZulu = 1077;

  // Value, readonly field.
  public final int value;

  // Private constructor, use valueOf to create an instance.
  private MsoLanguageID(int value) { this.value = value; }

  // Return one of the predefined typed constants for the given value or create a new object.
  public static  MsoLanguageID valueOf(int value) {
    switch(value) {
    case -2: return msoLanguageIDMixed;
    case 0: return msoLanguageIDNone;
    case 1024: return msoLanguageIDNoProofing;
    case 1078: return msoLanguageIDAfrikaans;
    case 1052: return msoLanguageIDAlbanian;
    case 1118: return msoLanguageIDAmharic;
    case 5121: return msoLanguageIDArabicAlgeria;
    case 15361: return msoLanguageIDArabicBahrain;
    case 3073: return msoLanguageIDArabicEgypt;
    case 2049: return msoLanguageIDArabicIraq;
    case 11265: return msoLanguageIDArabicJordan;
    case 13313: return msoLanguageIDArabicKuwait;
    case 12289: return msoLanguageIDArabicLebanon;
    case 4097: return msoLanguageIDArabicLibya;
    case 6145: return msoLanguageIDArabicMorocco;
    case 8193: return msoLanguageIDArabicOman;
    case 16385: return msoLanguageIDArabicQatar;
    case 1025: return msoLanguageIDArabic;
    case 10241: return msoLanguageIDArabicSyria;
    case 7169: return msoLanguageIDArabicTunisia;
    case 14337: return msoLanguageIDArabicUAE;
    case 9217: return msoLanguageIDArabicYemen;
    case 1067: return msoLanguageIDArmenian;
    case 1101: return msoLanguageIDAssamese;
    case 2092: return msoLanguageIDAzeriCyrillic;
    case 1068: return msoLanguageIDAzeriLatin;
    case 1069: return msoLanguageIDBasque;
    case 1059: return msoLanguageIDByelorussian;
    case 1093: return msoLanguageIDBengali;
    case 4122: return msoLanguageIDBosnian;
    case 8218: return msoLanguageIDBosnianBosniaHerzegovinaCyrillic;
    case 5146: return msoLanguageIDBosnianBosniaHerzegovinaLatin;
    case 1026: return msoLanguageIDBulgarian;
    case 1109: return msoLanguageIDBurmese;
    case 1027: return msoLanguageIDCatalan;
    case 3076: return msoLanguageIDChineseHongKongSAR;
    case 5124: return msoLanguageIDChineseMacaoSAR;
    case 2052: return msoLanguageIDSimplifiedChinese;
    case 4100: return msoLanguageIDChineseSingapore;
    case 1028: return msoLanguageIDTraditionalChinese;
    case 1116: return msoLanguageIDCherokee;
    case 1050: return msoLanguageIDCroatian;
    case 1029: return msoLanguageIDCzech;
    case 1030: return msoLanguageIDDanish;
    case 1125: return msoLanguageIDDivehi;
    case 2067: return msoLanguageIDBelgianDutch;
    case 1043: return msoLanguageIDDutch;
    case 2129: return msoLanguageIDDzongkhaBhutan;
    case 1126: return msoLanguageIDEdo;
    case 3081: return msoLanguageIDEnglishAUS;
    case 10249: return msoLanguageIDEnglishBelize;
    case 4105: return msoLanguageIDEnglishCanadian;
    case 9225: return msoLanguageIDEnglishCaribbean;
    case 14345: return msoLanguageIDEnglishIndonesia;
    case 6153: return msoLanguageIDEnglishIreland;
    case 8201: return msoLanguageIDEnglishJamaica;
    case 5129: return msoLanguageIDEnglishNewZealand;
    case 13321: return msoLanguageIDEnglishPhilippines;
    case 7177: return msoLanguageIDEnglishSouthAfrica;
    case 11273: return msoLanguageIDEnglishTrinidadTobago;
    case 2057: return msoLanguageIDEnglishUK;
    case 1033: return msoLanguageIDEnglishUS;
    case 12297: return msoLanguageIDEnglishZimbabwe;
    case 1061: return msoLanguageIDEstonian;
    case 1080: return msoLanguageIDFaeroese;
    case 1065: return msoLanguageIDFarsi;
    case 1124: return msoLanguageIDFilipino;
    case 1035: return msoLanguageIDFinnish;
    case 2060: return msoLanguageIDBelgianFrench;
    case 11276: return msoLanguageIDFrenchCameroon;
    case 3084: return msoLanguageIDFrenchCanadian;
    case 12300: return msoLanguageIDFrenchCotedIvoire;
    case 1036: return msoLanguageIDFrench;
    case 15372: return msoLanguageIDFrenchHaiti;
    case 5132: return msoLanguageIDFrenchLuxembourg;
    case 13324: return msoLanguageIDFrenchMali;
    case 6156: return msoLanguageIDFrenchMonaco;
    case 14348: return msoLanguageIDFrenchMorocco;
    case 8204: return msoLanguageIDFrenchReunion;
    case 10252: return msoLanguageIDFrenchSenegal;
    case 4108: return msoLanguageIDSwissFrench;
    case 7180: return msoLanguageIDFrenchWestIndies;
    case 9228: return msoLanguageIDFrenchZaire;
    //se 9228: return msoLanguageIDFrenchCongoDRC; // same as msoLanguageIDFrenchZaire
    case 1122: return msoLanguageIDFrisianNetherlands;
    case 1127: return msoLanguageIDFulfulde;
    case 2108: return msoLanguageIDGaelicIreland;
    case 1084: return msoLanguageIDGaelicScotland;
    case 1110: return msoLanguageIDGalician;
    case 1079: return msoLanguageIDGeorgian;
    case 3079: return msoLanguageIDGermanAustria;
    case 1031: return msoLanguageIDGerman;
    case 5127: return msoLanguageIDGermanLiechtenstein;
    case 4103: return msoLanguageIDGermanLuxembourg;
    case 2055: return msoLanguageIDSwissGerman;
    case 1032: return msoLanguageIDGreek;
    case 1140: return msoLanguageIDGuarani;
    case 1095: return msoLanguageIDGujarati;
    case 1128: return msoLanguageIDHausa;
    case 1141: return msoLanguageIDHawaiian;
    case 1037: return msoLanguageIDHebrew;
    case 1081: return msoLanguageIDHindi;
    case 1038: return msoLanguageIDHungarian;
    case 1129: return msoLanguageIDIbibio;
    case 1039: return msoLanguageIDIcelandic;
    case 1136: return msoLanguageIDIgbo;
    case 1057: return msoLanguageIDIndonesian;
    case 1117: return msoLanguageIDInuktitut;
    case 1040: return msoLanguageIDItalian;
    case 2064: return msoLanguageIDSwissItalian;
    case 1041: return msoLanguageIDJapanese;
    case 1099: return msoLanguageIDKannada;
    case 1137: return msoLanguageIDKanuri;
    case 1120: return msoLanguageIDKashmiri;
    case 2144: return msoLanguageIDKashmiriDevanagari;
    case 1087: return msoLanguageIDKazakh;
    case 1107: return msoLanguageIDKhmer;
    case 1088: return msoLanguageIDKirghiz;
    case 1111: return msoLanguageIDKonkani;
    case 1042: return msoLanguageIDKorean;
    //se 1088: return msoLanguageIDKyrgyz; // same as msoLanguageIDKirghiz
    case 1142: return msoLanguageIDLatin;
    case 1108: return msoLanguageIDLao;
    case 1062: return msoLanguageIDLatvian;
    case 1063: return msoLanguageIDLithuanian;
    case 1071: return msoLanguageIDMacedonian;
    //se 1071: return msoLanguageIDMacedonianFYROM; // same as msoLanguageIDMacedonian
    case 1086: return msoLanguageIDMalaysian;
    case 2110: return msoLanguageIDMalayBruneiDarussalam;
    case 1100: return msoLanguageIDMalayalam;
    case 1082: return msoLanguageIDMaltese;
    case 1112: return msoLanguageIDManipuri;
    case 1153: return msoLanguageIDMaori;
    case 1102: return msoLanguageIDMarathi;
    case 1104: return msoLanguageIDMongolian;
    case 1121: return msoLanguageIDNepali;
    case 1044: return msoLanguageIDNorwegianBokmol;
    case 2068: return msoLanguageIDNorwegianNynorsk;
    case 1096: return msoLanguageIDOriya;
    case 1138: return msoLanguageIDOromo;
    case 1123: return msoLanguageIDPashto;
    case 1045: return msoLanguageIDPolish;
    case 1046: return msoLanguageIDBrazilianPortuguese;
    case 2070: return msoLanguageIDPortuguese;
    case 1094: return msoLanguageIDPunjabi;
    case 1131: return msoLanguageIDQuechuaBolivia;
    case 2155: return msoLanguageIDQuechuaEcuador;
    case 3179: return msoLanguageIDQuechuaPeru;
    case 1047: return msoLanguageIDRhaetoRomanic;
    case 2072: return msoLanguageIDRomanianMoldova;
    case 1048: return msoLanguageIDRomanian;
    case 2073: return msoLanguageIDRussianMoldova;
    case 1049: return msoLanguageIDRussian;
    case 1083: return msoLanguageIDSamiLappish;
    case 1103: return msoLanguageIDSanskrit;
    case 1132: return msoLanguageIDSepedi;
    case 7194: return msoLanguageIDSerbianBosniaHerzegovinaCyrillic;
    case 6170: return msoLanguageIDSerbianBosniaHerzegovinaLatin;
    case 3098: return msoLanguageIDSerbianCyrillic;
    case 2074: return msoLanguageIDSerbianLatin;
    case 1072: return msoLanguageIDSesotho;
    case 1113: return msoLanguageIDSindhi;
    case 2137: return msoLanguageIDSindhiPakistan;
    case 1115: return msoLanguageIDSinhalese;
    case 1051: return msoLanguageIDSlovak;
    case 1060: return msoLanguageIDSlovenian;
    case 1143: return msoLanguageIDSomali;
    case 1070: return msoLanguageIDSorbian;
    case 11274: return msoLanguageIDSpanishArgentina;
    case 16394: return msoLanguageIDSpanishBolivia;
    case 13322: return msoLanguageIDSpanishChile;
    case 9226: return msoLanguageIDSpanishColombia;
    case 5130: return msoLanguageIDSpanishCostaRica;
    case 7178: return msoLanguageIDSpanishDominicanRepublic;
    case 12298: return msoLanguageIDSpanishEcuador;
    case 17418: return msoLanguageIDSpanishElSalvador;
    case 4106: return msoLanguageIDSpanishGuatemala;
    case 18442: return msoLanguageIDSpanishHonduras;
    case 2058: return msoLanguageIDMexicanSpanish;
    case 19466: return msoLanguageIDSpanishNicaragua;
    case 6154: return msoLanguageIDSpanishPanama;
    case 15370: return msoLanguageIDSpanishParaguay;
    case 10250: return msoLanguageIDSpanishPeru;
    case 20490: return msoLanguageIDSpanishPuertoRico;
    case 3082: return msoLanguageIDSpanishModernSort;
    case 1034: return msoLanguageIDSpanish;
    case 14346: return msoLanguageIDSpanishUruguay;
    case 8202: return msoLanguageIDSpanishVenezuela;
    //se 1072: return msoLanguageIDSutu; // same as msoLanguageIDSesotho
    case 1089: return msoLanguageIDSwahili;
    case 2077: return msoLanguageIDSwedishFinland;
    case 1053: return msoLanguageIDSwedish;
    case 1114: return msoLanguageIDSyriac;
    case 1064: return msoLanguageIDTajik;
    case 1097: return msoLanguageIDTamil;
    case 1119: return msoLanguageIDTamazight;
    case 2143: return msoLanguageIDTamazightLatin;
    case 1092: return msoLanguageIDTatar;
    case 1098: return msoLanguageIDTelugu;
    case 1054: return msoLanguageIDThai;
    case 1105: return msoLanguageIDTibetan;
    case 1139: return msoLanguageIDTigrignaEthiopic;
    case 2163: return msoLanguageIDTigrignaEritrea;
    case 1073: return msoLanguageIDTsonga;
    case 1074: return msoLanguageIDTswana;
    case 1055: return msoLanguageIDTurkish;
    case 1090: return msoLanguageIDTurkmen;
    case 1058: return msoLanguageIDUkrainian;
    case 1056: return msoLanguageIDUrdu;
    case 2115: return msoLanguageIDUzbekCyrillic;
    case 1091: return msoLanguageIDUzbekLatin;
    case 1075: return msoLanguageIDVenda;
    case 1066: return msoLanguageIDVietnamese;
    case 1106: return msoLanguageIDWelsh;
    case 1076: return msoLanguageIDXhosa;
    case 1144: return msoLanguageIDYi;
    case 1085: return msoLanguageIDYiddish;
    case 1130: return msoLanguageIDYoruba;
    case 1077: return msoLanguageIDZulu;
    default: return new MsoLanguageID(value);
    }
  }
}
