/* ** GENEREATED FILE - DO NOT MODIFY ** */
package com.wilutions.mslib.outlook;
import com.wilutions.com.*;

/**
 * _AppointmentItem.
 * 
 */
@CoInterface(guid="{00063033-0000-0000-C000-000000000046}")
public interface _AppointmentItem extends IDispatch {
  static boolean __typelib__loaded = __TypeLib.load();
  @DeclDISPID(61440)  public _Application getApplication() throws ComException;
  @DeclDISPID(61450)  public OlObjectClass getClass_() throws ComException;
  @DeclDISPID(61451)  public _NameSpace getSession() throws ComException;
  @DeclDISPID(61441)  public IDispatch getParent() throws ComException;
  @DeclDISPID(63511)  public Actions getActions() throws ComException;
  @DeclDISPID(63509)  public Attachments getAttachments() throws ComException;
  @DeclDISPID(34101)  public String getBillingInformation() throws ComException;
  @DeclDISPID(34101)  public void setBillingInformation(final String value) throws ComException;
  @DeclDISPID(37120)  public String getBody() throws ComException;
  @DeclDISPID(37120)  public void setBody(final String value) throws ComException;
  @DeclDISPID(36865)  public String getCategories() throws ComException;
  @DeclDISPID(36865)  public void setCategories(final String value) throws ComException;
  @DeclDISPID(34107)  public String getCompanies() throws ComException;
  @DeclDISPID(34107)  public void setCompanies(final String value) throws ComException;
  @DeclDISPID(64192)  public String getConversationIndex() throws ComException;
  @DeclDISPID(112)  public String getConversationTopic() throws ComException;
  @DeclDISPID(12295)  public java.util.Date getCreationTime() throws ComException;
  @DeclDISPID(61470)  public String getEntryID() throws ComException;
  @DeclDISPID(61589)  public FormDescription getFormDescription() throws ComException;
  @DeclDISPID(61502)  public _Inspector getGetInspector() throws ComException;
  @DeclDISPID(23)  public OlImportance getImportance() throws ComException;
  @DeclDISPID(23)  public void setImportance(final OlImportance value) throws ComException;
  @DeclDISPID(12296)  public java.util.Date getLastModificationTime() throws ComException;
  @DeclDISPID(26)  public String getMessageClass() throws ComException;
  @DeclDISPID(26)  public void setMessageClass(final String value) throws ComException;
  @DeclDISPID(34100)  public String getMileage() throws ComException;
  @DeclDISPID(34100)  public void setMileage(final String value) throws ComException;
  @DeclDISPID(34062)  public Boolean getNoAging() throws ComException;
  @DeclDISPID(34062)  public void setNoAging(final Boolean value) throws ComException;
  @DeclDISPID(34130)  public Integer getOutlookInternalVersion() throws ComException;
  @DeclDISPID(34132)  public String getOutlookVersion() throws ComException;
  @DeclDISPID(61603)  public Boolean getSaved() throws ComException;
  @DeclDISPID(54)  public OlSensitivity getSensitivity() throws ComException;
  @DeclDISPID(54)  public void setSensitivity(final OlSensitivity value) throws ComException;
  @DeclDISPID(3592)  public Integer getSize() throws ComException;
  @DeclDISPID(55)  public String getSubject() throws ComException;
  @DeclDISPID(55)  public void setSubject(final String value) throws ComException;
  @DeclDISPID(61468)  public Boolean getUnRead() throws ComException;
  @DeclDISPID(61468)  public void setUnRead(final Boolean value) throws ComException;
  @DeclDISPID(63510)  public UserProperties getUserProperties() throws ComException;
  @DeclDISPID(61475)  public void Close(final OlInspectorClose SaveMode) throws ComException;
  @DeclDISPID(61490)  public IDispatch Copy() throws ComException;
  @DeclDISPID(61514)  public void Delete() throws ComException;
  @DeclDISPID(61606)  public void Display(final Object Modal) throws ComException;
  @DeclDISPID(61492)  public IDispatch Move(final MAPIFolder DestFldr) throws ComException;
  @DeclDISPID(61491)  public void PrintOut() throws ComException;
  @DeclDISPID(61512)  public void Save() throws ComException;
  @DeclDISPID(61521)  public void SaveAs(final String Path, final Object Type) throws ComException;
  @DeclDISPID(33301)  public Boolean getAllDayEvent() throws ComException;
  @DeclDISPID(33301)  public void setAllDayEvent(final Boolean value) throws ComException;
  @DeclDISPID(33285)  public OlBusyStatus getBusyStatus() throws ComException;
  @DeclDISPID(33285)  public void setBusyStatus(final OlBusyStatus value) throws ComException;
  @DeclDISPID(33299)  public Integer getDuration() throws ComException;
  @DeclDISPID(33299)  public void setDuration(final Integer value) throws ComException;
  @DeclDISPID(33294)  public java.util.Date getEnd() throws ComException;
  @DeclDISPID(33294)  public void setEnd(final java.util.Date value) throws ComException;
  @DeclDISPID(33315)  public Boolean getIsRecurring() throws ComException;
  @DeclDISPID(33288)  public String getLocation() throws ComException;
  @DeclDISPID(33288)  public void setLocation(final String value) throws ComException;
  @DeclDISPID(33303)  public OlMeetingStatus getMeetingStatus() throws ComException;
  @DeclDISPID(33303)  public void setMeetingStatus(final OlMeetingStatus value) throws ComException;
  @DeclDISPID(3587)  public String getOptionalAttendees() throws ComException;
  @DeclDISPID(3587)  public void setOptionalAttendees(final String value) throws ComException;
  @DeclDISPID(66)  public String getOrganizer() throws ComException;
  @DeclDISPID(63508)  public Recipients getRecipients() throws ComException;
  @DeclDISPID(62789)  public OlRecurrenceState getRecurrenceState() throws ComException;
  @DeclDISPID(34049)  public Integer getReminderMinutesBeforeStart() throws ComException;
  @DeclDISPID(34049)  public void setReminderMinutesBeforeStart(final Integer value) throws ComException;
  @DeclDISPID(34076)  public Boolean getReminderOverrideDefault() throws ComException;
  @DeclDISPID(34076)  public void setReminderOverrideDefault(final Boolean value) throws ComException;
  @DeclDISPID(34078)  public Boolean getReminderPlaySound() throws ComException;
  @DeclDISPID(34078)  public void setReminderPlaySound(final Boolean value) throws ComException;
  @DeclDISPID(34051)  public Boolean getReminderSet() throws ComException;
  @DeclDISPID(34051)  public void setReminderSet(final Boolean value) throws ComException;
  @DeclDISPID(34079)  public String getReminderSoundFile() throws ComException;
  @DeclDISPID(34079)  public void setReminderSoundFile(final String value) throws ComException;
  @DeclDISPID(33312)  public java.util.Date getReplyTime() throws ComException;
  @DeclDISPID(33312)  public void setReplyTime(final java.util.Date value) throws ComException;
  @DeclDISPID(3588)  public String getRequiredAttendees() throws ComException;
  @DeclDISPID(3588)  public void setRequiredAttendees(final String value) throws ComException;
  @DeclDISPID(3586)  public String getResources() throws ComException;
  @DeclDISPID(3586)  public void setResources(final String value) throws ComException;
  @DeclDISPID(99)  public Boolean getResponseRequested() throws ComException;
  @DeclDISPID(99)  public void setResponseRequested(final Boolean value) throws ComException;
  @DeclDISPID(33304)  public OlResponseStatus getResponseStatus() throws ComException;
  @DeclDISPID(33293)  public java.util.Date getStart() throws ComException;
  @DeclDISPID(33293)  public void setStart(final java.util.Date value) throws ComException;
  @DeclDISPID(61605)  public void ClearRecurrencePattern() throws ComException;
  @DeclDISPID(62791)  public MailItem ForwardAsVcal() throws ComException;
  @DeclDISPID(61604)  public RecurrencePattern GetRecurrencePattern() throws ComException;
  @DeclDISPID(62722)  public MeetingItem Respond(final OlMeetingResponse Response, final Object fNoUI, final Object fAdditionalTextDialog) throws ComException;
  @DeclDISPID(61557)  public void Send() throws ComException;
  @DeclDISPID(64009)  public ItemProperties getItemProperties() throws ComException;
  @DeclDISPID(64077)  public OlDownloadState getDownloadState() throws ComException;
  @DeclDISPID(64011)  public void ShowCategoriesDialog() throws ComException;
  @DeclDISPID(16350)  public Integer getInternetCodepage() throws ComException;
  @DeclDISPID(16350)  public void setInternetCodepage(final Integer value) throws ComException;
  @DeclDISPID(34161)  public OlRemoteStatus getMarkForDownload() throws ComException;
  @DeclDISPID(34161)  public void setMarkForDownload(final OlRemoteStatus value) throws ComException;
  @DeclDISPID(64164)  public Boolean getIsConflict() throws ComException;
  @DeclDISPID(33289)  public String getMeetingWorkspaceURL() throws ComException;
  @DeclDISPID(64186)  public Boolean getAutoResolvedWinner() throws ComException;
  @DeclDISPID(64187)  public Conflicts getConflicts() throws ComException;
  @DeclDISPID(64253)  public PropertyAccessor getPropertyAccessor() throws ComException;
  @DeclDISPID(64209)  public Account getSendUsingAccount() throws ComException;
  @DeclDISPID(64209)  public void setSendUsingAccount(final Account value) throws ComException;
  @DeclDISPID(64509)  public String getGlobalAppointmentID() throws ComException;
  @DeclDISPID(62778)  public Boolean getForceUpdateToAllAttendees() throws ComException;
  @DeclDISPID(62778)  public void setForceUpdateToAllAttendees(final Boolean value) throws ComException;
  @DeclDISPID(33384)  public java.util.Date getStartUTC() throws ComException;
  @DeclDISPID(33384)  public void setStartUTC(final java.util.Date value) throws ComException;
  @DeclDISPID(33385)  public java.util.Date getEndUTC() throws ComException;
  @DeclDISPID(33385)  public void setEndUTC(final java.util.Date value) throws ComException;
  @DeclDISPID(33382)  public java.util.Date getStartInStartTimeZone() throws ComException;
  @DeclDISPID(33382)  public void setStartInStartTimeZone(final java.util.Date value) throws ComException;
  @DeclDISPID(33383)  public java.util.Date getEndInEndTimeZone() throws ComException;
  @DeclDISPID(33383)  public void setEndInEndTimeZone(final java.util.Date value) throws ComException;
  @DeclDISPID(64551)  public _TimeZone getStartTimeZone() throws ComException;
  @DeclDISPID(64551)  public void setStartTimeZone(final _TimeZone value) throws ComException;
  @DeclDISPID(64552)  public _TimeZone getEndTimeZone() throws ComException;
  @DeclDISPID(64552)  public void setEndTimeZone(final _TimeZone value) throws ComException;
  @DeclDISPID(64596)  public _Conversation GetConversation() throws ComException;
  @DeclDISPID(64629)  public String getConversationID() throws ComException;
  @DeclDISPID(64274)  public _AppointmentItem CopyTo(final MAPIFolder DestinationFolder, final OlAppointmentCopyOptions CopyOptions) throws ComException;
  @DeclDISPID(64644)  public Object getRTFBody() throws ComException;
  @DeclDISPID(64644)  public void setRTFBody(final Object value) throws ComException;
  @DeclDISPID(64648)  public AddressEntry GetOrganizer() throws ComException;
}
